### ISSUE TITLE
Hover broken for points from history

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1003]
When hovering over points added to a 3D view through history, data is missing from the hover preview.

To reproduce:

1. Run `./examples/colmap/main.py` 
2. Increase the history for points in the "world" space.
3. Hover over individual points in the 3D "world" space view
4. Most points will be missing data (colorrgba and point3d) in the hover.

https://user-images.githubusercontent.com/2624717/215713162-ff1cb0d8-af49-4a33-94dc-b17f324db179.mov

**Comment by Wumpf** [comment]
Superseeded by https://github.com/rerun-io/rerun/issues/1627
(pretty much the exact samie problem, but with a newer screenshot)
