### ISSUE TITLE
Hover over image under point / rect as well

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1021]
When hovering over an image with points or rectangles on it, the image hover preview suddenly disappears when we hover over a point or rectangle. This is particularly annoying because the position of the point or rectangle boundary is usually the most interesting place to inspect the image.

![hover points on image](https://user-images.githubusercontent.com/2624717/215887882-c7896e46-5c67-4531-876e-d9de21899b31.gif)

**Comment by emilk** [comment]
Will fix after
* #1615
