### ISSUE TITLE
Finish documentation "Concepts" section

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1048]
See:
 - https://github.com/rerun-io/rerun-docs/blob/main/docs/concepts.md
 - https://github.com/rerun-io/rerun-docs/blob/main/docs/concepts/

Concepts to cover:
 - [x] Entities and Components: https://github.com/rerun-io/rerun-docs/pull/8
 - [x] Path Hierarchy: https://github.com/rerun-io/rerun-docs/pull/8
 - [x] Spaces
 - [x] Blueprints
 - [x] Events and Timelines
 - [x] Transforms
 - [x] Batch Data
 - [x] Selections
 - [x] Apps and Sessions

**Comment by Wumpf** [comment]
batch data & apps and sessions went in as well now. DONE!!!! :)
