### ISSUE TITLE
Time indicator in plots view looks draggable but isn't

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1074]
![Screenshot 2023-02-03 at 10 04 08](https://user-images.githubusercontent.com/2624717/216558091-dcf31c67-a561-4888-bb73-e17964b088ff.png)

Quick solution is probably to just drop the triangle in the top of the time indicator for plots. Better solution would be to make it possible to drag the time slider in the plots view as well.
![Screenshot 2023-02-03 at 10 06 11](https://user-images.githubusercontent.com/2624717/216558152-d152ae6c-f36f-4759-b928-554f4ff1d51c.png)

**Comment by emilk** [comment]
We should be able to use `ui.interact` for a rectangle covering the time cursor. It will steal all interaction from the underlying `egui::Plot` widget.

**Comment by emilk** [comment]
Requires some egui work: `egui::Plot` needs to return the `plot_from_screen` transform.
