### ISSUE TITLE
Set app-id properly in wayland

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1115]
With the new native window frame support from https://github.com/rerun-io/rerun/pull/1094 it would be nice to be able to strip off the wayland-provided titlebar in some contexts. The mechanism wayland exposes for doing this is a configuration that filters applications based on app-id, which seems not to be set.

It looks like we want to be making a call to:
https://docs.rs/winit/latest/winit/platform/wayland/trait.WindowBuilderExtWayland.html#tymethod.with_name

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/1063

**Comment by emilk** [comment]
We do this via `eframe` now! Our app-id is `rerun`

**Comment by jleibs** [comment]
Confirmed this is there and works as expected.

**Comment by teh-cmc** [comment]
:partying_face:
