### ISSUE TITLE
Depth map hover preview doesn't apply color map

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1116]
**Describe the bug**
When hovering over a depth map we show the  "original data" in grey instead of what is visible on the screen

**Screenshots**
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1220815/217192980-21e9d3d4-b677-45dd-a7ed-1d6acee9fac5.png">

**Comment by teh-cmc** [comment]
Fixed by recent colormapping work.
