### ISSUE TITLE
Examples: implement new polyglot organization

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#1122]
Expected layout:
```
- examples/python/my_example
- examples/python/my_other_example
- examples/rust/my_example
- examples/rust/my_other_example
- examples/datasets/my_example
- examples/datasets/my_other_example
```

- Python is sole responsible for downloading and caching assets for the time being, Rust examples merely feed off that cache.
-  ?

**Comment by Wumpf** [comment]
we settled on a structure, but we don't have anything downloading data so far in Rust. I'd call that a separate ticket though
