### ISSUE TITLE
Examples: feature matrix table to know what's where

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#1123]
Akin to e.g. [wgpu's feature matrix](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples#feature-matrix)

**Comment by Wumpf** [comment]
we have an [example doc](https://www.rerun.io/docs/getting-started/examples) page by now but a feature matrix would still be nice

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/2270

**Comment by abey79** [comment]
I think the proper way to achieve this would be to have either a dedicated front matter property in the examples, or some custom `feat:point3d`-style tags. What do you think @jprochazk?
