### ISSUE TITLE
`api_demo`: set different `app_id` depending on what demo is being run

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#1125]
What the title says.

- Avoids a poor user experience where one ends up with a bunch of zombie space views
- Provides interesting analytics for official examples

**Comment by Wumpf** [comment]
went in!

**Comment by teh-cmc** [comment]
lies!

**Comment by emilk** [comment]
I don't understand this issues.

What does "active demo/recording/scene" refer to? The currently open recording in the viewer?

When should `app_id` take it into account? When the example sets the `app_it` in `init`? In analytics?

**Comment by teh-cmc** [comment]
> What does "active demo/recording/scene" refer to? The currently open recording in the viewer?

It refers to the application-specific notion of "what's the current dataset", e.g.:
- For objectron, the app_id should change depending on the dataset being visualized (e.g. `book` vs `bike`)
- For api_demo, the app_id should change depending on the `--demo` flag
- etc

**Comment by emilk** [comment]
I don't agree on the `objectron` example - it is the same application regardless of what you visualize, and you should expect to have the same blueprint regardless if you are "scanning" a book or a bike.

For `api_demo`: for this one I agree (though it is not really an example, and we should either turn it into many small examples or make it into a test)
