### ISSUE TITLE
Highlight SpaceView tab when corresponding SpaceView is hovered elsewhere (e.g. in blueprint tree UI)

### ISSUE THREAD

**Issue by jondo2010** [rerun-io/rerun#1129]
Hovering over a SpaceView in the blueprint tree should highlight the title of the corresponding `TabViewer` tab and vice-versa.

Digging a little into the codebase, it looks like `egui_dock::TabViewer` needs to be modified to support drawing an arbitrary widget for the tab title, instead of just `egui::WidgetText`. See `egui_dock::TabViewer::title`.

**Comment by abey79** [comment]
We now have custom tab header widget. Icons are there, but it could indeed be somehow highlighted when the corresponding entry is hovered in the blueprint tree UI.

**Comment by abey79** [comment]
This has been done at some point recently.
