### ISSUE TITLE
Space views with a single object should be collapsed by default in the blueprint

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1134]
These two here for example should be collapsed
![image](https://user-images.githubusercontent.com/1220815/217346563-9ac2d818-5b1d-45aa-aedb-ff37ec7d5245.png)

**Comment by meehawk** [comment]
Hey @Wumpf would love contribute. Can I take this up? Any pointers would be awesome

**Comment by Wumpf** [comment]
@meehawk awesome! Absolutely, go ahead!
You need to modify the code somewhere around here https://github.com/rerun-io/rerun/blob/main/crates/re_viewer/src/ui/viewport.rs#L143, where the blueprint tree is built up

**Comment by meehawk** [comment]
Thanks a tonne @Wumpf will open up a PR for this!
