### ISSUE TITLE
Documentation on Memory Usage / out-of-memory behavior

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1138]
There's enough nuance here to potentially make for a good how-to guide?
- Identifying that rerun is using too much memory
- The UIs involved in inspecting/debugging
- The flags involved in configuring the behavior
- Some best practices for reducing overhead

**Comment by emilk** [comment]
Related:
* #1736

**Comment by emilk** [comment]
This is now documented in https://www.rerun.io/docs/howto/limit-ram
