### ISSUE TITLE
Make sure users are running examples that match their installed rerun package

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1152]
Now that users are expected to be running rerun packages from pypi, simply having users `git clone git@github.com:rerun-io/rerun.git` in order to access examples is eventually going to break.

The examples in the repo need to be version matched with head of main, and API incompatibilities will eventually show up.

There are a few options for this ranging from checking out a tagged branch.

Something like:
```
git checkout `rerun --git-tag`
```

To downloading the examples as a .zip from the release page.

**Comment by Wumpf** [comment]
We're using `latest` branch for this and use this in all example descriptions.
