### ISSUE TITLE
Consider introducing System as a concept to fully align with ECS model.

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1155]
At the moment our `Scenes` act in a "System-like" way, but without the formalism or framework support that one might find in a true ECS.

Given we are already using the terminology Entity and Component and doing System-like things it could be beneficial to go the rest of the way here. Systems could be a nice way to reconcile some other ideas we have discussed such as:
 - Application of annotations
 - Derived component values
 - Data filtering / highlighting

**Comment by Wumpf** [comment]
We introduced Systems by now in the form of `ViewPartSystem` and `ContextSystem`. In the future we'll formalize this more, but `System` already started to become a building block in our architecture.

Se also https://github.com/rerun-io/rerun/blob/main/design/space_views.md
