### ISSUE TITLE
Incorrect heuristic for text-logs separated by an unknown tranform

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1159]
Admittedly a bit of a strange use-case, but if you have two separate log streams that should never be mixed in the same view, the only way to annotate that is with an unknown transform. Although the notion of transforms between text spaces is a bit weird, I believe this validly maps to our "Space" concepts (and it works!... aside from the heuristic issue).

Minimal repro:
```
rr.init("text", True)
rr.log_text_entry("foo", "Hello")
rr.log_unknown_transform("foo/bar")
rr.log_text_entry("foo/bar", "World")
```

The heuristic here creates and defaults to a spatial transform for the foo/bar space which seems wrong.
![image](https://user-images.githubusercontent.com/3312232/217683479-45741cd0-ecb8-46e4-a320-2fe0df686bff.png)

The expected behavior should be:
![image](https://user-images.githubusercontent.com/3312232/217683599-5ca25628-7392-4ed3-9301-6d8358b163e0.png)

Also the fact that we have two "foo" spaces here seems wrong as well:
![image](https://user-images.githubusercontent.com/3312232/217683771-8de23646-b572-4ea1-8507-7c841c23969b.png)

**Comment by Wumpf** [comment]
We no longer have unknown transforms, been like that for quite a while
