### ISSUE TITLE
Editable & user defined Data Blueprint Groups

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1174]
Currently, blueprint groups are automatically created upon adding Entities to a Space View.

Various improvements to groups are missing:
* add/remove objects easily (drag drop)
* allow user defined groups
* `Data` sections on groups to inform about data within a group

**Comment by teh-cmc** [comment]
That seems done-ish?

**Comment by Wumpf** [comment]
Wouldn't say so: There is pretty much nothing that can be user defined about blueprint groups, none of the bullet points in the ticket are fullfilled. The only thing one can do with groups is to set properties.
The goal here is to be able to regroup and create your own groups that aren't controlled by the heuristic

**Comment by Wumpf** [comment]
Obsoleted by
* #4128
