### ISSUE TITLE
When visibile history is on, point radius changes based on timeline selection

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1215]
**Describe the bug**
When I scrub through time with visible history turned on, the radius of the points change.

**To Reproduce**
Run colmap, and then increase history for points. The radius jumped up, but then goes down as you scrub through time.

**Expected behavior**
If I have logged my points with a specific radius, the size of the points should not change.

**Screenshots**

https://user-images.githubusercontent.com/3312232/218285193-93934a62-d0f7-4051-9ce2-a7173cdf6df5.mov

**Comment by abey79** [comment]
I can't repro, is this still a thing?

**Comment by jleibs** [comment]
Closing as fixed for now
