### ISSUE TITLE
Point radius not correctly transformed during projection.

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1219]
Currently, when we project points from 3d -> 2d they continue to be rendered with a screenspace radius. Since most geometric spaces are in meters, but image-spaces are in pixels this makes it nearly impossible to have a single radius size that looks good in both.

I had set the point radius in colmap to 1cm and thought it had broken the projection. However when I turned off the image I noticed I did have super tiny projections that just weren't visible in the image.

These scenes mostly demonstrate the problem
* Upper-left: 3d scene w/ points at 1cm
* Upper-right: view from camera, which has proper projection since it's a true 3D scene
* Lower-left: 2D view with projected points. Image hidden so you can see the point sizes.
* Lower-right: The scene where I was hoping to see projected points

![image](https://user-images.githubusercontent.com/3312232/218286521-b91a197e-1d98-4320-9e56-847cccd7a13a.png)

Ideally the lower right and upper right would have the same-sized points.

**Comment by nikolausWest** [comment]
Is this fixed?

**Comment by rangsjo** [comment]
I see this problem in version 0.8.2.

**Comment by nikolausWest** [comment]
> I see this problem in version 0.8.2.

Ouch, that looks super bad
