### ISSUE TITLE
Terminal output shows escape characters in windows powershell

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1279]
Windows powershell default configuration doesn't know about the color escape sequences so we get log lines like:
```
←[2m2023-02-14T18:24:48.227979Z←[0m ←[32m INFO←[0m ←[2mrerun::run←[0m←[2m:←[0m Loading "C:\\Users\\jleibs\\venv\\Lib\\site-packages\\rerun_sdk\\rerun_demo\\demo.rrd"…
```

Workaround is to use windows Terminal program instead of Powershell.

**Comment by emilk** [comment]
I wonder if this is still a problem now that we've switched to `env_logger`

**Comment by Wumpf** [comment]
Might depend on the terminal etc. but for me stuff renders fine on Windows these days! All nice and colorful
