### ISSUE TITLE
Improved support for running rerun through WSL2 

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1285]
Rerun does not officially support running from inside of WSL2 on windows. 

This issue is tracking some of the things that would need to be cleaned up to make this work nicely out of the box.

A few missing packages need to be installed;
```
 libvulkan1 libxcb-randr0 mesa-vulkan-drivers
 ```

Cursor setting is currently broken:
```
2023-02-14T19:39:26.162762Z ERROR sctk_adwaita::pointer: Failed to set cursor
2023-02-14T19:39:26.162882Z  WARN winit::platform_impl::platform::wayland::seat::pointer: Failed to set cursor to Default
2023-02-14T19:40:45.025764Z ERROR sctk_adwaita::pointer: Failed to set cursor
2023-02-14T19:40:45.313754Z  WARN winit::platform_impl::platform::wayland::seat::pointer: Failed to set cursor to Default
```
This might be a matter of installing some missing packages.

Performance feels sluggish. Maybe it's defaulting to a CPU renderer, though folks have had success with hardware rendering support in other contexts. Might even just a WSL config/documentation issue:
 - https://github.com/godotengine/godot-proposals/discussions/4335#discussioncomment-3110853

![image](https://user-images.githubusercontent.com/3312232/218770799-b2ecd377-420a-4290-97e6-52a461709113.png)

**Comment by jleibs** [comment]
One more package to add to the docs: `adwaita-icon-theme-full`

**Comment by traversaro** [comment]
> Performance feels sluggish. Maybe it's defaulting to a CPU renderer, though folks have had success with hardware rendering support in other contexts. Might even just a WSL config/documentation issue:

Sorry for commenting on a closed issue, but experienced the same issue and I landed here, so I guess future users may experience the same problem. As of early 2024 Vulkan support in WSL2 is still kind of a work in progress, while d3d12 (i.e. OpenGL implemented on top of Direct3D 12) is much more mature, especially in Mesa 24 where it reached compatibility over OpenGL 4.6 (if the GPU on which it runs supports it). I was able to run the the view reducing a lot the sluggish behavior by passing by forcing the use of OpenGL by passing `--renderer=gl` to the `rerun` invocation.

**Comment by Wumpf** [comment]
Hmm we could consider also compiling in wgpu's d3d12 support. But the flip side here is that wgpu's support for d3d12 isn't that mature yet. Could likely be better than the GL backend though (which has to do quite expensive things to emulate the more modern API of wgpu/webgpu)

>  I was able to run the the view reducing a lot the sluggish behavior by passing by forcing the use of OpenGL by passing --renderer=gl to the rerun invocation.

glad to hear that.
Overall confirms for me that #5596 is necessary

**Comment by Wumpf** [comment]
ah 🤦 of course. Yeah what I wrote there made no sense. Thanks for clarifying!

**Comment by traversaro** [comment]
I guess something else WSL users may be interested in is to have the process saving data in WSL, and just the viewer on proper Windows. I still need to look into that, if I get it to work probably I can document it somewhere.

**Comment by Wumpf** [comment]
Yes, that _should_ work fine already, but I haven't tried it myself yet. From WSL's point of view that's just a Viewer sitting on another machine - so calling `connect` with the host machine's IP (and a Viewer running there) is all that's needed.
