### ISSUE TITLE
Make explicit logging of Instance Keys consistent and less error prone

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1309]
The point and rect APIs currently allow logging Instance Keys by using the (now inappropriately named) "identifiers" field. Additionally if instance keys are logged without meeting sorting and uniqueness constraints we end up with either poor performance or possible dropped data depending on which API paths are being used.

All of this needs to be cleaned up to really advertise user-provided instance keys as a meaningful feature.

**Comment by teh-cmc** [comment]
- Fixed by #5395
