### ISSUE TITLE
Viewer freezes/crashes on save

### ISSUE THREAD

**Issue by AnkeAnke** [rerun-io/rerun#1315]
**Describe the bug**
Clicking on the `Save...` menu item or keying `ctrl+S`, the viewer crashes. 

**To Reproduce**
1. Log some data (via connecting from other process)
2. Try to save (`Save...` or `ctrl+S`)
3. Process crashes

**Expected behavior**
No crash, preferably even a save file.

**Backtrace**
Couldn't get a backtrace (even with `RUST_BACKTRACE=1`). But here's the terminal output:
```
(python3:8726): GLib-GObject-WARNING **: 13:42:26.828: cannot register existing type 'GdkDisplayManager'

(python3:8726): GLib-CRITICAL **: 13:42:26.828: g_once_init_leave: assertion 'result != 0' failed

(python3:8726): GLib-GObject-CRITICAL **: 13:42:26.828: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault (core dumped)
```

**Desktop:**
- OS: Pop! OS 22.04 LTS (Ubuntu with benefits)
- Windowing system: X11
- Python: 3.10.4 (June 22, GCC 11.2)
- GLib: Ubuntu GLIBC 2.35-0ubuntu3

**Comment by emilk** [comment]
> No crash, preferably even a save file.
😆

**Comment by emilk** [comment]
Likely fix:
* https://github.com/rerun-io/rerun/pull/1402
