### ISSUE TITLE
Mechanism to force image to be treated as a tensor

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1323]
Not all 2D tensors are images. Data like an [stft](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html) looks like an image but doesn't play nicely with the image viewer.

The tensor viewer has a number of nice features like:
 - support for f64 data
 - the ability to not lock the aspect ratio
 - support for colormaps

We can trick the viewer into creating a tensor by adding a trivial outer dimension, but it would be nice not to need to do this:

Example:
```
f, t, Zxx = scipy.signal.stft(x, fs, nperseg=1000)
Zxx_image = np.abs(Zxx).astype(np.float32)
Zxx_tensor = np.expand_dims(np.abs(Zxx), axis=0)

rr.init("stft_test", spawn=True)
rr.log_tensor("stft_image", Zxx_image)
rr.log_tensor("stft_tensor", Zxx_tensor)
```
![image](https://user-images.githubusercontent.com/3312232/219267607-710e1fe4-984f-4948-b8ef-275fb10d513f.png)

**Comment by Wumpf** [comment]
Related to https://github.com/rerun-io/rerun/issues/1164

**Comment by jleibs** [comment]
```
rr.log("stft_tensor", rr.Tensor(Zxx_image))
```
now does exactly what this describes
