### ISSUE TITLE
Parallelize space views

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1325]
The Rerun viewer needs to run in Wasm on the browser. This limits our threading ability. `std::thread` is, for instance, not available. At the same time we want to make sure our viewer achieves good frame rate when compiled natively.

## Parallelism on native, with single-threaded fallback on web
`rayon` is the go-to Rust crate for fine-grained parallelism. It is commonly used by library crates (behind a feature flag).
Currently `rayon` does not run in wasm in the browser, but this might change soon:

* https://github.com/rayon-rs/rayon/issues/861
* https://github.com/rayon-rs/rayon/pull/1019

In the mean-time we can also define our own helpers for parallelism, e.g.:

``` rust
/// Run two things in parallel
#[cfg(not(target_arch = "wasm32"))]
fn parallel<A: Send, B: Send>(
    a: impl Send + FnOnce() -> A,
    b: impl Send + FnOnce() -> B,
) -> (A, B) {
    rayon::join(a, b)
}

// Serial-fallback for wasm32
#[cfg(target_arch = "wasm32")]
fn parallel2<A: Send, B: Send>(
    a: impl Send + FnOnce() -> A,
    b: impl Send + FnOnce() -> B,
) -> (A, B) {
    ((a)(), (b)()) 
}
```

See https://github.com/rerun-io/rerun/pull/1041 for an experiment along these lines

## Parallelism on wasm32
With a bit of work, one can spawn wasm32 threads in the browser with shared memory. Unfortunately, this requires a nightly compiler (for `-Z build-std=std,panic_abort`). 

I think it could be fine for use to rely on the nightly compiler for just wasm32.

I suggest we keep this use-case in mind, but focus on the native performance for now.

Se also: 
* https://github.com/rustwasm/wasm-bindgen/tree/main/examples/raytrace-parallel
* https://rustwasm.github.io/docs/wasm-bindgen/examples/raytrace.html
* https://twitter.com/rikarends/status/1626144062737620994
* https://www.tweag.io/blog/2022-11-24-wasm-threads-and-messages/

**Comment by emilk** [comment]
Thanks @RReverser - I forgot to mention that! We experimented with [wasm-bindgen-rayon](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon) last autumn but decided we didn't want to commit to nightly back then.

**Comment by RReverser** [comment]
Yeah fair enough, I wish rebuilding standard library wasn't necessary. There is one trick you can use to build even on stable, although it's not particularly recommended: https://twitter.com/RReverser/status/1608840842654908419

**Comment by emilk** [comment]
We have started using `rayon` in a few places in the viewer, relying on its single-threaded fallback on web.

In order to get a proper speedup we need to make our `RenderContext` sync
