### ISSUE TITLE
Wasm blobs should have different names in debug vs. release

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#1327]
Our build scripts generate a wasm blob to embed into the web server, but right now this blob will be named identically whether you're building in debug or release... which can lead to pretty nasty bugs to track down (e.g. a background `cargo check` overwriting your release blob without you knowing...).

**Comment by emilk** [comment]
With this, we now include both the release and debug wasm files when we publish our crates, which more than doubles the crate size (the debug build is larger). Ideally we should only include the release build.
