### ISSUE TITLE
Make `web` feature default when using `rerun` as a dependency

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#1328]
[Quoting @emilk](https://github.com/rerun-io/rerun-docs/pull/45#discussion_r1108247205): 
> off-topic: in the repository, the web feature is expensive, since it compiles the wasm. For crate users it is cheap, since the web-viewer comes pre-packaged as wasm. We should look into making web default for users (at least once it is more stable).

**Comment by Wumpf** [comment]
This got pretty much obsoleted by the fact that we now have `rerun-sdk` which comes without the viewer. The viewer install via `cargo install` on the other hand _does_ come with the webviewer (it can do `--serve` and all), so this has been solved in essence.
