### ISSUE TITLE
Publish crates on CI

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1343]
We still want to be able to publish locally (in case of emergency), but the default should be that the crates are published on CI.

- [x] wrap the versioning and publishing logic in a script https://github.com/rerun-io/rerun/pull/2604
- [x] publish `alpha` versions of crates every week
  - https://github.com/rerun-io/rerun/pull/2710 + follow ups
- [x] publish release versions of crates in the `manual_release` workflow https://github.com/rerun-io/rerun/pull/2629

We'll have to do a topological sort of crates for the `cargo publish`.

**Comment by emilk** [comment]
We have a `scripts/publish_crates.sh` script which could perhaps be replaced with a 3rd party helper that finds all the crates that should be published, and publish them in a topological order.

There are things like `cargo-release` that does this and more, and we could perhaps use that if we could get rid of the "and more" part :)

**Comment by emilk** [comment]
We could for-loop-publish all our crates until they all succeed. No need for topological sort. Could be a simple python script.

**Comment by jleibs** [comment]
Another idea, similar to how we handle the wheel files, would be to publish these crates initially to gcloud. That would allow us to use the final version numbers during the testing phase and then only re-publish them to crates.io when we're happy with them.

**Comment by jprochazk** [comment]
- [ ] add as many checks from `cargo publish` to our checks workflows as possible (probably can't match it exactly- that's fine)
- [ ] use `cargo package` on the crates and publish them to `build.rerun.io` for every commit (`build.rerun.io` becomes our own miny-registry)
- [ ] publish crates in the `manual_release` workflow

**Comment by jprochazk** [comment]
Finished in https://github.com/rerun-io/rerun/pull/2721
