### ISSUE TITLE
Simple example to log URDF models to Rerun

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1362]
See:
 - https://docs.ros.org/en/humble/Tutorials/Intermediate/URDF/Building-a-Visual-Robot-Model-with-URDF-from-Scratch.html

Would benefit from: https://github.com/rerun-io/rerun/issues/1361 since these are models that URDF supports.

Should include example of subscribing to the robot-state publisher and use it to update transforms of the linkages.

**Comment by teh-cmc** [comment]
That feels done?

https://github.com/rerun-io/rerun-loader-python-example-urdf
