### ISSUE TITLE
Switch the `re_sdk_comms` network code to use Tokio

### ISSUE THREAD

**Issue by jondo2010** [rerun-io/rerun#1366]
<@U02US1A9RA9> probably a question for you: In `crates/re_sdk_comms/src/server.rs` , `serve()` spawns a thread waiting for incoming connections, and then 1 thread per connection from an incoming SDK. Is there any special reason this isn’t implemented with Tokio?

[Slack Message](https://rerunio.slack.com/archives/C033K5VS2KD/p1676894114791509?thread_ts=1676894114.791509&cid=C033K5VS2KD)

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/1633
