### ISSUE TITLE
Save .rrd from store instead of saving `LogMsg`:es.

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1394]
Currently the viewer stores all `LogMsg`:ed it receives in order to be able to save them as a `.rrd` file.

This leads to a lot of extra memory user, often at 2x or more, since the same data is also stored in the data store.

We need to support:
* Saving the entire store
* Saving a time-range of one timeline

We should implement batch ingestion before we work on this, as it affects how data is stored in an `.rrd` file.

Blocked on:
* #589 
* https://github.com/rerun-io/rerun/issues/1395

**Comment by teh-cmc** [comment]
Fixed by #1535, which went the other route instead (https://github.com/rerun-io/rerun/issues/1397), for the reasons explained in detail in #1535.
