### ISSUE TITLE
Turn off store archiving to hotfix memory duplication issue

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1397]
Maybe we need both that and:
* https://github.com/rerun-io/rerun/pull/1375

**Comment by emilk** [comment]
The way to accomplish this is to set

```
DataStoreConfig {
    component_bucket_size_bytes: u64::MAX,
    component_bucket_nb_rows: u64::MAX,
    …
}
```

but according to the docs, that stops the GC from doing anything.

However, considering we don't really have a working GC right now, maybe it doesn't matter:
* https://github.com/rerun-io/rerun/issues/1414
* https://github.com/rerun-io/rerun/issues/1412

**Comment by emilk** [comment]
No - we want memory pruning

**Comment by teh-cmc** [comment]
This turned out to be the right strategy in the end.

It need not break garbage collection: we can disable archiving without necessarily breaking the bucketing system.
