### ISSUE TITLE
Use CpuWriteGpuReadBuffer for all cpu->gpu transfers

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1398]
Followup on #1382 

Turns out this does have some ripple effects on how we pass around `RenderContext` - generally we should try to pass immutable reference and takes locks internally where needed (as short lived as possible without too much hassle). This is a refactor we need to do anyways for better multitreadability

**Comment by jleibs** [comment]
@Wumpf is this done?

**Comment by Wumpf** [comment]
No, afaik most RenderData is still using the queue and neither the LineBuilder nor the PointBuilder write to belt memory directly.
