### ISSUE TITLE
CI: clippy isn't run for `re_sdk` ?

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1446]
![image](https://user-images.githubusercontent.com/1148717/221913262-1a775d2f-77a2-415e-8b76-b60194b7d85b.png)

**Comment by teh-cmc** [comment]
Apparently we have a new one this morning...
![image](https://user-images.githubusercontent.com/2910679/222367520-e8ca105e-f535-41b5-b0a9-5f99c46c803b.png)

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/1447
