### ISSUE TITLE
Add larger hover-area + delay to hover pop-up on timeline

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1469]
The rapid flashing when hovering over items on the timeline is somewhat disconcerting. 

It actually looks worse than this locally but it seems my screen recorder is dropping frames. Still the basic idea comes through:
[Screencast from 03-01-2023 07:15:33 PM.webm](https://user-images.githubusercontent.com/3312232/222297423-7dbe2451-e451-4ab8-838d-e0b84456f4a6.webm)

**Comment by emilk** [comment]
Related: https://github.com/rerun-io/rerun/pull/1557
