### ISSUE TITLE
Github latest release page connected to wrong commit-hash

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1470]
https://github.com/rerun-io/rerun/releases/tag/latest now has just the artifacts from the most recent build, but it's still connected to a stale hash.

This means it incorrectly shows "84 commits since this release"
![image](https://user-images.githubusercontent.com/3312232/222299098-47aca6f0-6b5b-4b07-a5cd-5d6890b1bf14.png)

And also the attached Source archive is incorrect.

**Comment by jleibs** [comment]
I'm not seeing an option to support this in: https://github.com/ncipollo/release-action

We may need to just use a separate action to manually update the git tag itself.

**Comment by emilk** [comment]
It's weird that `latest` has the artifacts from the most recent build - `latest` is the tag we use for proper releases
