### ISSUE TITLE
Serve our web-viewer with one example somewhere

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1494]
Done when we can send a link to a friend without feeling embarrassed about it:

* [x] We have a nice URL with the web demo
    * [x] Serve it as a static site using HTTPS load balancing ([guide](https://cloud.google.com/storage/docs/hosting-static-website))
        * [x] Point it to `app.rerun.io ` 
        * [x] Turn on CDN
* [x] Our CI publish a new web-viewer and example `.rrd` files on each new release
    * [x] Both are put in versioned locations in their respective buckets. These versions end up as part of the url
* ~~We warn about slowness on chrome (or fix it)~~ (Chrome issue doesn't impact small rrds served over http. Only websockets.)
   * https://github.com/rerun-io/rerun/issues/963
* [x] We warn about problems on Windows (or fix them)
* [x] We warn on mobile (our UI isn't designed for mobile yet)
* ~~We have links back to our landing page, github, and doc~~ (Handle separately: https://github.com/rerun-io/rerun/issues/1669)
* [x] Make sure analytics works so we can follow to what extent this feature is used

### Potential complexities
- SSL certificates: Should this use the same SSL certificate as our main site or not? If it should, that will require some extra work on the main site. If not, how will that work when we want to use this viewer to show Rerun examples on the main site?

### Alternative approach to serving via a bucket
- Serve with Netlify: We could use Netlify to serve the static web viewer. Would need to consider:
    - How would we set it up to work correctly with versions?
    - What would the deploy pipeline look like? Go through a separate repository?
    - This would remove the ssl certificate issue

**Comment by jleibs** [comment]
Note that the slowness of chrome is specifically related to the websocket data path. The url-downloading logic could still use a bit of optimization, but is not nearly as bad. Also it behaves much more similarly between firefox and chrome.

The 250-meg `rusty_car.rrd` takes 9 seconds to load on firefox, and 11 seconds to load on chrome.  About 4 seconds of that is pre-fetching the 250-meg rrd, and the remaining 5-6 seconds are processing.
