### ISSUE TITLE
Move crate publishing to to CI

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1525]
Currently, we're doing publishing for crates.io locally. We should move this to a CI job that is triggered in the same way for alpha & final releases as our python publishing CI!
Special care has to be taken that the publishing script may fail whenever crate dependencies changed or new crates are added.

**Comment by emilk** [comment]
> Special care has to be taken that the publishing script may fail whenever crate dependencies changed or new crates are added.

This is quite a big one. I suspect we will have snowflake problems on each new release for the next few releases.

There are quite a several tools that can help with publishing, like [`cargo-release`](https://github.com/crate-ci/cargo-release)
