### ISSUE TITLE
Create script to help with changelog writing

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1526]
It would be great if we had a script that extracts all the PRs since last commit and buckets them by labels.
For 0.3.0 I used `git fetch --tags --force && git log --pretty=format:%s v0.2.0..HEAD` and then sorted manually.

**Comment by teh-cmc** [comment]
Feels like we should go one step further and have a special set of "category" labels that A) match 1-to-1 with the categories in our changelogs and B) are mandatory to have at least 1 of them set on every PR.

Coupled with keeping changelogs in mind when writing our PR titles, we should be able to cut down the editing to almost zero.
