### ISSUE TITLE
Python `log_mesh` does not support textures

### ISSUE THREAD

**Issue by pablovela5620** [rerun-io/rerun#1570]
**Describe the annoyance**

Using the [log_mesh](https://ref.rerun.io/docs/python/v0.3.0/common/spatial_primitives/#rerun.log_mesh) does not support textures 

**To Reproduce**
1.  Load Mesh using Trimesh library
2.  extract faces and verts
3.  log via `log_mesh`

```python
ply = trimesh.load(str(ply_path))
verts = ply.vertices
faces = ply.faces

# Log the mesh
rr.log_mesh("world/mesh_log", positions=verts, indices=faces, timeless=True)
```

**Expected behavior**

Should support textures

**Your goals**

Trying to log a colored mesh, I think in general this should just easily be handled by the `log_mesh_file` but it currently only supports OBJ and GLB formats. I could convert it from PLY -> OBJ but that's an extra step that doesn't seem like it should be necessary

**Screenshots**

Here is the original .ply mesh
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/25287427/224508487-65c60c45-8a6b-40df-b884-fc79c813081b.png">
Here is what is looks like in rerun
<img width="397" alt="image" src="https://user-images.githubusercontent.com/25287427/224508505-0472fad1-5357-4eeb-b97e-389363275cd4.png">

**Desktop (please complete the following information):**
 - OS:  macOS 13.2.1 M1 Macbook pro

**Additional context**

**Comment by nikolausWest** [comment]
The arkitscene example actually needed support for vertex colors (https://github.com/rerun-io/rerun/issues/1580) so I'm closing this for now since general texture support is a much bigger task
