### ISSUE TITLE
log_mesh_file does not support PLY files

### ISSUE THREAD

**Issue by pablovela5620** [rerun-io/rerun#1571]
**Describe the annoyance**

Trying to log a .ply mesh file using the `log_mesh_file` but there is only support for obj/glb

**Expected behavior**

There should be a way to log a .ply file via `log_mesh_file` without needing to load the file and use `log_mesh` or converting the .ply file into a obj/glb format

**Your goals**

Trying to log a colored mesh along with bounding 3d bounding boxes/camera/images/depths

**Desktop (please complete the following information):**
 - OS:  macOS 13.2.1 M1 Pro

**Additional context**

related to #1570 because there is no ply file support, had to load in the mesh using trimesh and use `log_mesh` instead

**Comment by teh-cmc** [comment]
#4519 adds a simple `DataLoader` for 3D point clouds in `ply` files, but that won't be usable from the SDKs until #4526 is solved.
- #4519 
- #4526
