### ISSUE TITLE
Project all 3D primitives to 2D views

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1581]
Right now, a core value proposition of Rerun is how easy we make it to visualize the combination of 2D and 3D. However, we can currently only project 3D points to 2D views.

Done when we can project the following 3D primitives to 2D views:

- [ ] Box 3D
- [ ] Mesh
- [ ] Line 3D
- [ ] Transform (at least consider if it makes sense)

In the presence of a valid transform path ending in a pinhole projection, it should be possible to add these primitives from a 3D space to a 2D space view.

**Comment by Wumpf** [comment]
Related to #1219
In particular my comment there talks about what we need to do to fix this https://github.com/rerun-io/rerun/issues/1219#issuecomment-1427028634
