### ISSUE TITLE
2D label projected to incorrect location in 3D view

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1593]
Can repro with
```
python .\examples\python\car\main.py
```

![image](https://user-images.githubusercontent.com/3312232/225259301-746512d1-7399-4222-a6d6-03c7bb0bc650.png)

The "a car" label appears to be in the wrong location.

**Comment by nnop** [comment]
Could you provide the code of `examples\python\car\main.py`? It's not in the repo now.

**Comment by Wumpf** [comment]
@nnop we removed that a while ago. What are you looking for?

**Comment by nnop** [comment]
I want to know how to show text in 3d scene.

**Comment by Wumpf** [comment]
the picture above shows a bug situation where the label was _not_ supposed to be in the 3D view.
Labels can be added to various archetypes that show in 3D, e.g. 3D points
