### ISSUE TITLE
`request_repaint_after` does not work when processing incoming messages from websocket

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1607]
As part of investigating: https://github.com/rerun-io/rerun/issues/963, I changed decode_log_msg to use `request_repaint_after`, however on web this prevents any painting from ever happening until the user interacts with the UI or triggers painting in some other fashion.

**Comment by emilk** [comment]
This is a bug in `eframe`:
* https://github.com/emilk/egui/issues/2674

**Comment by emilk** [comment]
Fixed upstream
