### ISSUE TITLE
Meshes don't show up on Chrome on Windows

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1620]
Fixed by https://github.com/gfx-rs/wgpu/pull/3597 / https://github.com/gfx-rs/wgpu/pull/3596

Need a workaround meanwhile - render a second invisible instance on chrome+windows 😕

**Comment by Wumpf** [comment]
Fixed in upstream chrome https://bugs.chromium.org/p/chromium/issues/detail?id=1425606 !
