### ISSUE TITLE
Whenever the browser looses focus, camera rotates on click+drag

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1681]
It seems browser-based rerun thinks the Alt modifier key is pressed until one presses & releases it. This causes camera control to rotate on drag whenever the browser looses focus. Once I press `alt` it behaves as it should again.

May need to revert  #1659 if we don't find a proper fix

Observed so far on Firefox @ Windows.

**Comment by emilk** [comment]
This sort of "sticky-modifiers" bug is very common. Please check if you have the issue on egui.rs:



![Image](https://user-images.githubusercontent.com/1148717/227210925-2c38ee56-1e0e-4036-9dc3-3ae07817fd49.png)

**Comment by Wumpf** [comment]
confirmed that it is a sticky modifier problem

**Comment by emilk** [comment]
Fixed upstream in https://github.com/emilk/egui/pull/2857
