### ISSUE TITLE
Bounding boxes are half the size they are supported to be

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1701]
Documentation clearly indicates bounding box dimensions are specified in half-sizes:
https://ref.rerun.io/docs/python/v0.3.0/common/spatial_primitives/#rerun.log_obb

Sample code:
```
rr.log_obb("world/obb", [1, 2, 3], [0, 0, 0], None, color=[255, 0, 0])

expected_corners = [[d0, d1, d2] for d0 in (-1, 1) for d1 in (-2, 2) for d2 in (-3, 3)]
rr.log_points("world/corners", positions=expected_corners, colors=[0, 255, 0])
```

However, the resultant bounding box appears to have sides of the provided dimensions:
![image](https://user-images.githubusercontent.com/3312232/227344858-6d97292b-6bd9-4c2f-b6ce-ee0ef1e01617.png)

**Comment by nikolausWest** [comment]
Does #1749 close this or do we also need to make updates to examples or elsewhere?
