### ISSUE TITLE
Make timezone used to display time configurable

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#1714]
It's annoying to have to mentally convert between UTC time and my local timezone when looking at timestamps in the UI.

**Comment by emilk** [comment]
The minimal version of this should provide a global option of showing times either as UTC, or in the local timezone.

This should be applied to all times in the UI, which means everywhere we call `time::format_description`, and most of the interface of `re_log_types::Time`

**Comment by ParthJadhav** [comment]
Where would that option should be @emilk ?

**Comment by emilk** [comment]
It should be in `AppOptions` in `crates/re_viewer/src/misc/app_options.rs`

(sorry for the late reply - I missed this one 😬)

**Comment by jparismorgan** [comment]
Hey @nikolausWest / @emilk, took a pass at addressing this here: https://github.com/rerun-io/rerun/pull/3530 - and also had a few questions & comments on there as well!
