### ISSUE TITLE
Allow setting memory limits from SDK

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1736]
We have `--memory-limit` option, but there is no easy way to use it when you're inside Python or Rust.
We need to add this to both APIs and do a way better job documenting this feature!

**Comment by Wumpf** [comment]
Missing documentation is tracked by #1138

**Comment by emilk** [comment]
Eventually it should go in the blueprint store, I think

**Comment by emilk** [comment]
Let's start by fixing this for `rr.spawn` and perhaps add a UI for it
