### ISSUE TITLE
`connect()` blocking when called for the second time without viewer open

### ISSUE THREAD

**Issue by Sjouks** [rerun-io/rerun#1781]
**Describe the bug**

The `connect()` function is blocking when it is called for the second time in the same process without a viewer open.

**To Reproduce**
```
import rerun
rerun.init("foo", spawn=False)
rerun.connect()
rerun.connect()
```

and make sure you **don't** have the viewer running.

**Expected behavior**
I would expect the second `connect()` to exert the same behavior as the first `connect()`

**Screenshots**

**Backtrace**

**Desktop (please complete the following information):**
 - OS:  pop-os 22.04

**Additional context**

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/1830
