### ISSUE TITLE
Rerun packages available on conda

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1816]
There's already a good starting point to build off of: https://github.com/conda-forge/staged-recipes/pull/22471

TODO:
 - [ ] Finish the recipes for Mac & Windows support.
 - [ ] Add to our release flow 
 - [ ] Update docs

**Comment by emilk** [comment]
How will this be maintained?

**Comment by ruben-arts** [comment]
Hey, I could give you some extra info. 

The staged-recipes result in a feedstock, which automates build setup regeneration based on GitHub releases completely in their CI. 

The testing part can be extended with CI tests and/or you can make the merge of the generated update manual. Then the package can be tested locally first. 

In my experience, it can require some time to do the initial setup but updates are straightforward afterward, it's a simple push of a button. Plus there is a helpful community where issues get resolved easily. 

If you would be afraid of ever pushing bad code/product there is a system in place to deal with that check: [Conda-forge Repodata Patches](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock)
This system avoids installation on systems without the sdk in a lockfile, while maintaining lockfile functionality.

**Comment by ruben-arts** [comment]
Hey, we just worked on fixing the feedstock pull request. 

It now works on `windows` `osx-64` and `linux-64`. `osx-arm64` can be done after the first build. 

Currently I'm the only maintainer but it would be nice if one of you joined. 

https://github.com/conda-forge/staged-recipes/pull/22471
