### ISSUE TITLE
Web viewer broken: panic due to `'fwidth' : no matching overloaded function`

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1858]
![image](https://user-images.githubusercontent.com/3312232/232159818-1fc21817-02a2-465f-9600-297ab8594eef.png)

Confirmed this is a regression due to:
 - https://github.com/rerun-io/rerun/pull/1850

**Comment by Wumpf** [comment]
quick google search revealed this ticket which is the likely cause https://github.com/gfx-rs/naga/issues/1743

**Comment by emilk** [comment]
My bad for not testing this on web 🤦
