### ISSUE TITLE
Can't zoom UI with ctrl and numpad +/- on Windows

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1868]
Via @martinkeefe here https://github.com/rerun-io/rerun/pull/265#issuecomment-1509928532

**Comment by emilk** [comment]
This is the global zoom shortcuts using ctrl +/-

**Comment by emilk** [comment]
May require fixes in egui

**Comment by Wumpf** [comment]
Works on my windows & numpad by now. Guess some winit/egui update fixed this
