### ISSUE TITLE
Multiprocessing with start-method "fork" results in hang on shutdown

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1921]
Can be reproduced with the multiprocessing demo.

Current workaround is to always force "spawn":
```
multiprocessing.set_start_method("spawn")
```

However, needing to do this will definitely bite Linux users since "fork" is the default.

See: https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

**Comment by emilk** [comment]
We have a user that is affected by this; they can't use `spawn`, so they can't update Rerun right now.
