### ISSUE TITLE
Consider accepting backslashes as path separators in object paths

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1937]
Recently ran into a silly bug where a python path got converted to string and then used as an entity path

![image](https://user-images.githubusercontent.com/1220815/233168545-7c462c88-ca09-4e83-8c00-37c257a00044.png)

We should consider converting backslashes internally to slashes and maybe even accept `pathlib.Path`

**Comment by emilk** [comment]
Backslashes are also used for escape sequences, which would make using `\` for separators confusing imho

**Comment by Wumpf** [comment]
agreed, backslashes is probably a bad idea. Also, thinking about it again taking a python `Path` is misleading as well - we're not dealing with file paths, so we also shouldn't take one. We could instead provide a simple `EntityPath` class that allows operations like `parent` etc.

**Comment by Wumpf** [comment]
not doing this any time soon, likely to make things worse
