### ISSUE TITLE
`run_all_examples.py` helper script

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1945]
We currently have a set of `just py-run-all*` commands that should be combined into a single helper script that can:

* Run different sub-sets of the examples ("all", "fast", "tests", …)

For each example, either:
* Run it and view it
* Run and save as .rrd files
* Load existing .rrd files

And view the examples either as:
* All the examples in a single Rerun viewer
* All the examples in separate Rerun viewers
* All the examples in a single Web Viewer

**Comment by jprochazk** [comment]
- [ ] Run different sub-sets of the examples ("all", "fast", "tests", …)
- [x] Run and view each example
- [x] Run and save as .rrd files
- [ ] Load existing .rrd files (not as a separate command)
- [x] All the examples in a single Rerun viewer
- [ ] All the examples in separate Rerun viewers
- [x] All the examples in a single Web Viewer
