### ISSUE TITLE
Replace `actions-rs/toolchain`

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#1961]
It appears `actions-rs/toolchain` is generating numerous warnings and otherwise unmaintained:
 - https://github.com/actions-rs/toolchain/issues/219

We need to identify (or create) an alternative action.

**Comment by teh-cmc** [comment]
Didn't we agree to just drop it altogether (https://github.com/rerun-io/rerun/pull/1935)? :thinking:
