### ISSUE TITLE
Jump to latest added timeline whenever a new timeline is added

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#1967]
Otherwise we're showing `log_time` all the time and this is unlikely of interest once there is a new one.

Also, this is another thing that should go to blueprint configuration!

**Comment by emilk** [comment]
Some caveats:

* `log_time` has all the logged data. Any other timeline could be missing a lot of the logged data, making users wonder "why isn't my logged data showing up!?
* Switching timeline at runtime (when a new timeline is added) can be quite annoying/distruptive ("why did my UI change!?")

To make this good I think we should separate the two cases:
* Selecting a default timeline
* Automatically switching to a new timeline

For the second case, we should `re_log::info!` the switch, which will show a little toast notification to the user, making it less surprising.

We should also make sure that any Space View which lacks data _because there is none on the current timeline_ should communicate that by showing some text "No data for this view on the current timeline ${name}. Click here to switch to the `log_time` timeline instead." or similar.

**Comment by Wumpf** [comment]
seems at some point we implemented this without any extra logging
