### ISSUE TITLE
Ping us on Slack when `main` CI is red

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1987]
We don't always notice when `main` is red. Let's get on top of it.

**Comment by emilk** [comment]
3. sounds good to me!

**Comment by teh-cmc** [comment]
Done, but waiting for `main` to fail so that we can be sure it's done

**Comment by jprochazk** [comment]
[This `main` failure](https://github.com/rerun-io/rerun/actions/runs/4926156512) was correctly reported, so closing this. 🎉
