### ISSUE TITLE
2D primitives ordering/layering

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#1988]
We don't currently define which order 2D shapes are painted. Once we support more primitives like filled rectangles, circles, text etc, it will be very important to be able to specify what is on top of what.

We also need good default, e.g. images should probably be furthest down whatever happens.
We should maybe default to painters-algorithm (whatever is logged first is painted furthest back), as that is what many users are used to from e.g. opencv.

Let's investigate nomenclature other libraries and tools use.

- [x] Rust
- [ ] Python

**Comment by Wumpf** [comment]
related to
* #702 
* #1025

**Comment by emilk** [comment]
Let's avoid confusion by not calling this "Z". A depth-image contains Z-values, but can also have a draw-order/layer which is completely unrelated.

**Comment by emilk** [comment]
proposal: `DrawOrder(f32)` component

**Comment by emilk** [comment]
We should also have a default `DrawOrder` for all the 3D stuff projected into 2D, so that you can specify:

* Paint my image
* Project 3D stuff on top of the image
* Paint these rectangles on top of everything else
