### ISSUE TITLE
Release updated Gradio Support

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2013]
### Background
A few of the complexities to figure out with Gradio:
(1) Gradio (and in particular hugging face spaces) run as a persistent service even across multiple users.  This means we need to avoid, or at least **be able** to avoid global session state interfering across multiple user sessions.
(2) In Gradio's normal execution model, jobs fully execute, then produce an output. This is somewhat similar to how our current notebook cells works with a single static resource output. Instead, we would like the embedded rerun viewer context to exist the whole time the job is running with data incrementally streaming to it. Gradio already has its own incremental streaming mechanism used for things like streaming audio or video, so tying into this framework would be nice.
(3) HF spaces, including Gradio, do everything over a single port. This means we really don't want to depend on running our own websocket server. Somehow retrieving the data-stream back from Rerun and tunneling it through Gradios websocket, as done with the other data that Gradio transmits, would simplify integration. This is also somewhat related to user-isolation, since Gradio already manages user session context.

### Next Steps
All of the above are functional in our PR: https://github.com/radames/gradio-rerun-viewer/pull/1

Need to clean up PR to get it into a final state and then merge.

Live demonstration: https://huggingface.co/spaces/jleibs/rerun_streaming_poc

**Comment by emilk** [comment]
https://x.com/radamar/status/1785066677706928326
https://huggingface.co/spaces/radames/gradio_rerun

**Comment by jleibs** [comment]
Reminder to self: give the gradio component a blueprint argument that does the right thing.

**Comment by jleibs** [comment]
https://github.com/radames/gradio-rerun-viewer/pull/1

**Comment by jleibs** [comment]
This has been published.
