### ISSUE TITLE
Allow (some) plots to aggregate / downsample data automatically based on zoom-level.

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2015]
There are many cases where plots over long regions of times become too noisy to visualize nicely. In these cases it would be nice to have different policies for aggregating multiple samples into a single visualize representation.

An example from a user:
> I have a data of product sales of from a store and I would like to see bars of whole month and when zoomed in I would like to see the composition of the sold products on an hourly basis.

This is probably another area where a "System" (https://github.com/rerun-io/rerun/issues/1155) plugin could make sense. This is similar in concept to a "derived component" but changes the way we think about time and instance-identity a bit so it's worth thinking about as we scope out that work in the future.

Doing this dynamically based on zoom-level adds another twist to this but could be quite impressive from a UI experience perspective. In essence this would require making the view configuration parameterizable based on a combination of the time-query and the data. I doubt we would want to do this fully automatically but I can imagine setting up a view explicitly to have this behavior with will specified bounds for when to make the transition.

**Comment by emilk** [comment]
Downsampling is also crucial for performance when plotting 100k+ datapoints

**Comment by jleibs** [comment]
Dupe of: https://github.com/rerun-io/rerun/issues/4271
