### ISSUE TITLE
0.5.1 patch release

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2018]
Cherry-pick

* https://github.com/rerun-io/rerun/pull/2007
* https://github.com/rerun-io/rerun/pull/2014
* https://github.com/rerun-io/rerun/pull/1984
* https://github.com/rerun-io/rerun/pull/1969

**Comment by Wumpf** [comment]
Proposing to also add:
* #1969
* #1947

**Comment by emilk** [comment]
I agree - let's add #1969 but not #1947

**Comment by jleibs** [comment]
Also needed to add #1951
