### ISSUE TITLE
Tracking Issue: Store Façade

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2019]
We need an interface in front of the data store and blueprint store that handles:

* ergonomic read/write of common types
* blueprint overrides/fallbacks for entity components values
* component transforms (jpeg -> tensor)
* Rework `re_query` to be object centered (`store.query(…)` instead of `re_query::query(store, …)`)

Let's start with the first two points

**Comment by Wumpf** [comment]
`HybridResults` is pretty much doing this now. It also takes into account blueprint store.
We don't have an immediate need for a Facade on the store itself anymore. Closing this as outdated.
