### ISSUE TITLE
Fix inconsistency in version number specification on build jobs

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2030]
Some build jobs have an input such as `RELEASE_VERSION`. It's not clear or consistent whether this should be "v0.5.1" or "0.5.1"

We want to use `v0.5.1` for things like tagging but currently need to use 0.5.1 for things like version checks. Resulting in errors like:
![image](https://user-images.githubusercontent.com/3312232/235918772-f7f45ae6-3e3b-4e24-ae6e-f184b216782d.png)

**Comment by jleibs** [comment]
@jprochazk is this still an issue?

**Comment by jprochazk** [comment]
I haven't run into any issues with something using a `v` prefix for version names
