### ISSUE TITLE
Make it possible to hide or move legend in a plot

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2049]
several users say it is in the way of their data
should for starters expose position (corners?) and a way to hide it

Should also consider to do what we do in the tensor view and show it only on hover (as an option and/or the default?)

**Comment by PeterMitrano** [comment]
Here's an example of this, where on the left side plot "costs" I'd like to be able to see the stuff currently covered up by the legend

![Screenshot from 2023-05-04 14-45-34](https://user-images.githubusercontent.com/4010770/236299595-63f9d2e6-3079-40c1-8c42-30dfb680157e.png)
