### ISSUE TITLE
Play button should toggle when no data is streamed

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2077]
Via Kai on Discord https://discord.com/channels/1062300748202921994/1062300748777529379/1105509445137608724

In cases where we *know* no new data is streamed in (i.e. just loading a file / closed connection), the play button should toggle and not keep playing. More like a video player

**Comment by emilk** [comment]
Makes sense. Related to:
* https://github.com/rerun-io/rerun/issues/1964

**Comment by jleibs** [comment]
The fix for this was more complicated than anticipated and introduced a bug where the viewer would prematurely pause if playback caught up with the recording timeline during log-ingestion. Re-opening this and reverting this fix...

**Comment by jleibs** [comment]
Fix for the regression: https://github.com/rerun-io/rerun/pull/2106
