### ISSUE TITLE
"Play" mode repaints gui each frame

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2083]
Try running `examples/python/notebook/cube.ipynb` and turn on the performance metrics, and you'll see:

![repaint-play-bug](https://github.com/rerun-io/rerun/assets/1148717/0a6d1e3b-7dfb-4aa2-9b12-0360712555a4)

(see top left corner)

When "Play" hits the end it should probably stop, or at least we shouldn't be calling `request_repaint` unless there are new log events arriving.

**Comment by emilk** [comment]
The fix should be the same as for https://github.com/rerun-io/rerun/issues/2077

**Comment by emilk** [comment]
This regression happened in a recent refactor of re_viewer, where the `request_repaint` was moved

**Comment by jleibs** [comment]
The fix for this regressed other behavior.
See: https://github.com/rerun-io/rerun/pull/2103

**Comment by jleibs** [comment]
Fix for the regression: https://github.com/rerun-io/rerun/pull/2106
