### ISSUE TITLE
"Is shown in" section is unstable

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2104]
https://github.com/rerun-io/rerun/assets/2910679/e36fb35f-d8fa-4a04-871f-efe9328ba463

**Comment by emilk** [comment]
Just need to add a sort by `display_name` in `list_existing_data_blueprints` in `crates/re_viewer/src/ui/selection_panel.rs`

**Comment by Wumpf** [comment]
this got fixed it seems, can't repro it anymore
