### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2113]
Prerequisites:
* [x] Look into rerun crash analytics for 0.5.0
  * https://github.com/rerun-io/rerun/pull/2168
* [x] Publish egui 0.22
* [x] Publish egui_tiles 0.1
* [x] Update some dependencies
  * [x] https://github.com/rerun-io/rerun/pull/2161
  * [x] https://github.com/rerun-io/rerun/pull/2196
* [x] https://github.com/rerun-io/rerun/pull/2205
* [x] https://github.com/rerun-io/rerun/pull/2198
* [x] https://github.com/rerun-io/rerun/pull/2125
* [x] https://github.com/rerun-io/rerun/issues/2150
* [x] https://github.com/rerun-io/rerun/issues/2178
* [x] A lot of testing, including ergonomics of `rerun foo.png` and friends
* [x] #2050 
* [x] Update https://app.rerun.io/ with all examples

**Comment by Wumpf** [comment]
Requires https://github.com/gfx-rs/wgpu/pull/3774 unless we do some workarounds

**Comment by emilk** [comment]
it's done
