### ISSUE TITLE
Design and implement: app / recording / blueprint selection GUI

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2127]
Rerun currently has 3 related concepts relevant to the given state of the viewer: "app", "recording" and "blueprint."

The current naive implementation has 2 menu items: 1 for recordings and 1 for blueprints.  Nothing precludes you from manually selecting incompatible recordings and blueprints.

There are still lots of open questions and ideas around how to handle this.  3 proposals that have come up so far:

Proposal 1: Recording-centric
 - https://github.com/rerun-io/rerun/issues/1905
 - Each recording always gets its own tab
 - Within a recording tab, only show the matching blueprints based on app-id
 - Open question: what happens if you load a blueprint or run a blueprint-app with a different app-id?

Proposal 2: App-centric
- Each *app* gets its own tab
- When a new recording or blueprint associated with a specific app comes in or is opened, auto-switch to that app:
- Within the context of an app, by default, you only see the Recordings/Blueprints of the matching app.
- Open questions: how do you show two recordings of the same app?

**Comment by emilk** [comment]
We've decided on limiting each Rerun Viewer to only have one blueprint loaded at a time. This means each recording can get its own tab. Mårten is in the process of designing that.
