### ISSUE TITLE
Control tile layout containers via blueprint code

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2128]
Tile layout containers are a good first contender for expanding the blueprint APIs. Needs to represet:
 - Layout type (horiz / vert / grid)
 - IDs, and weights of sub-containers and panes

Some decisions to be made about what information is stored as path vs stored as components. Children could be sub-paths or batch-components.

**Comment by emilk** [comment]
We should do this first:
* #2140

**Comment by abey79** [comment]
- Depends on #4285

**Comment by jleibs** [comment]
Done in:
 - https://github.com/rerun-io/rerun/pull/5408
