### ISSUE TITLE
Move non-blueprint state out of the blueprint

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2130]
As of https://github.com/rerun-io/rerun/pull/2010 the entirety of the blueprint is serialized and then reloaded on every frame. This means that anything marked `serde(skip)` ends up being reset on every frame. This is related to some rendering helper state, some of the hover selection logic pieces, etc.  This behavior complicates the logic of saving/restoring blueprint and clouds the understanding what things are for configuration vs what things are for operation.

All of this needs to move to a different runtime-persistent storage which is used in conjunction with the blueprint to drive the layout and behavior of the views.

**Comment by emilk** [comment]
Related: https://github.com/rerun-io/rerun/issues/2142
