### ISSUE TITLE
Make it easy to zoom in on only a single axis in a plot

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2148]
We have selection rectangle based selection that can change the ratio between the axis but there's no scroll + X shortcut to zoom in just Y or X axis.

**Comment by MichalLebeda** [comment]
I suggest CTRL + Scroll for Y axis and CTRL + Shift + Scroll for X axis but others may have different preferences. Would suggest to keep normal scroll scale both axes.

**Comment by Wumpf** [comment]
ended up using a different shortcut, see #2742
