### ISSUE TITLE
`re_build_build_info`: PR builds fail in CI

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2172]
See for example:
https://github.com/rerun-io/rerun/actions/runs/5024217902/jobs/9009702716?pr=2161

Specific error:
```
  --- stderr
  thread 'main' panicked at 'Failed to run 'git ["symbolic-ref", "--short", "HEAD"]':

  fatal: ref HEAD is not a symbolic ref

  ', crates/re_build_build_info/src/lib.rs:103:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: The process '/usr/local/cargo/bin/cargo' failed with exit code 101
```

I believe is another problem stemming from similar conditions as what caused:
 - https://github.com/rerun-io/rerun/issues/2155

In this particular case, during certain pull-request builds, the build does *not* take place on the branch commit, but rather an ephemeral merge-commit derived from merging the PR into main.

However, regardless, `re_build_build_info` needs to be robust to all manner of weird git environments.

I was hoping merging main into the branch would prevent this from happening but it seems not to be the case.

**Comment by emilk** [comment]
Already broken in https://github.com/rerun-io/rerun/pull/2173

**Comment by emilk** [comment]
This was because I pushed a ill-thought-through `assert` to the PR in question. I'll do something better in #2173 instead
