### ISSUE TITLE
Standardize and generalize out-of-tree transforms

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2197]
- We have in-tree transforms today: "mono" components that affect the transform of a given entity as well as all of its children
- We also need some way of specifying out-of-tree transforms: transforms that only apply to a single entity (or rather, a single instance of that entity), without affecting its chidren
  - E.g. logging an array of 3D boxes that have different orientations
  - E.g. scaling a mesh without affecting its children

The alternative is to add extra layers of empty nodes, which quickly gets less ergonomic, especially with batches.

**Comment by jleibs** [comment]
I believe we can consider this done as part of:
- https://github.com/rerun-io/rerun/pull/7143
