### ISSUE TITLE
Flickering 3D frame when moving camera

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2201]
**Describe the annoyance**
The 3D frame that appears when moving the camera flickers.

This seems to happen only in the prerelease right now.

**Video**

https://github.com/rerun-io/rerun/assets/9785832/2a534dc1-b49d-42c5-92db-e3a218003711

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - `rerun-sdk 0.6.0a0+2023.5.24.043b7a3`

**Comment by Wumpf** [comment]
closed the wrong issue!
