### ISSUE TITLE
manual_build_release job should generate the index page at a discoverable location

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2223]
When we build the artifacts for a release using: https://github.com/rerun-io/rerun/actions/workflows/manual_build_release.yml we end up with a minimum pip index, for example: https://build.rerun.io/commit/0b2c9a9/wheels/index.html

However, you need special knowledge to knowledge to find it.

We should have a landing page that conveniently links us to the different pre-released artifacts, and could also consider storing them based on version. For example: https://build.rerun.io/prerelease/0.6.0-alpha.1/wheels/index.html

**Comment by jprochazk** [comment]
Release artifacts are linked in a table on the release PR
