### ISSUE TITLE
Numpad enter not working

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2224]
**Describe the annoyance**
Numpad enter does not work to confirm / exit text edits (same with space view name and playback speed).

**To Reproduce**
1. Go to playback speed text edit
2. Type something
3. Press numpad enter (nothing happens)
4. Press return (gets confirmed)

**Expected behavior**
Same behavior as for return.

**Desktop:**
 - OS: Ubuntu 20.04
 - `rerun-sdk 0.5.1`

**Comment by emilk** [comment]
Will be fixed once we update to https://github.com/emilk/egui/pull/3285
