### ISSUE TITLE
2D image detail is half a pixel off

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2236]
The little popup showing information around the current pixel seems to be half a pixel off.

**To Reproduce**
1. Log image
2. Zoom in

**Video**

https://github.com/rerun-io/rerun/assets/9785832/721a0661-093c-48b9-9faa-18d2ee2aff8f

Note the cursor is never leaving the pixel, while the information changes. Bottom right of the popup, shows the corner of four pixels, instead of just one color as the text above suggests.

**Expected behavior**
I guess only a single color should be shown in the preview on the right side (same color as in text description), and the color above should correspond to the color of the pixel the cursor is in.

**Desktop**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.6.0 [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu release-0.6 643dea9, built 2023-05-25T20:35:24Z
```

**Comment by Wumpf** [comment]
nice catch!
