### ISSUE TITLE
Can't remove group and all descendants from space view

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2237]
It's possible to add a group and all its descendants, but afterwards it's not possible to remove them again. Instead the plus will be greyed out and it says "Entity does not have any components."

Especially annoying if I log a large number of entities such as 
```
world/lines/#1
world/lines/#2
world/lines/#3
...
```
You can add all lines with a single press, but you have to remove one-by-one.

This video demonstrates this with the world path. Can add all descendants, but can't remove them all again.

https://github.com/rerun-io/rerun/assets/9785832/4f9f418a-b541-44a6-8d98-9ba9df2cb0c1

**Expected behavior**
Show the minus and allow removing all descendants.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun Version**
```
rerun_py 0.6.0 [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu release-0.6 643dea9, built 2023-05-25T20:35:24Z
```

**Comment by Wumpf** [comment]
all of this works quite differently by now, don't think this issue applies any longer
