### ISSUE TITLE
Add lock-file for our Python dependencies

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2253]
We often have problems with Python dependencies breaking because of differing versions.

All our Python dependencies (both for dev and examples) should be in a `Pipfile.lock`, or something similar. Maybe look into Poetry?

**Comment by abey79** [comment]
I can vouch for poetry, I use it for my personal projects.

**Comment by emilk** [comment]
Relevant for the upcoming numpy 2.0 release: https://pythonspeed.com/articles/numpy-2/

**Comment by emilk** [comment]
Closing in favor of the better written issue:
* https://github.com/rerun-io/rerun/issues/5862
