### ISSUE TITLE
Improve example naming

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2259]
The example names should be more descriptive about what they contain. For instance, `colmap` should have "slam" in the name and `opencv_canny` should probably focus less on the "canny" and more that it is a live camera example.

The names are important both in the repository and for https://demo.rerun.io

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/2270

**Comment by nikolausWest** [comment]
Closed by #2416
