### ISSUE TITLE
Improve the example data on demo.rerun.io

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2260]
In particular COLMAP is a huge file, taking way to long to download.

The selected demos could use a bit more curation too.

**Comment by emilk** [comment]
Looking through https://www.rerun.io/docs/getting-started/examples I think these are the visually appealing examples we want:

* dna
* minimal
* arkit
* colmap
* dicom
* mp pose
* nyud
* lego car
* segment anything
* tracking hf opencv
* plots

**Comment by nikolausWest** [comment]
Ok to just build these examples on manually and on release
