### ISSUE TITLE
Improve loading screen in web and in the viewer

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2261]
We have two loading screens:

* In our `index.html` we show a spinner waiting for the `.wasm` do download and load
* In `app.rs` we show a wait text while waiting for a stream of file to be parsed

Both these should be nicer looking, and ideally more similarly looking to

**Comment by emilk** [comment]
Needs design, Mårten is working on it

**Comment by emilk** [comment]
Bevy has a nice progress bar while the wasm is being downloaded

**Comment by emilk** [comment]
There is a design here: https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?type=design&node-id=2709-19054&t=tDADACn3sWKeBVYM-0

**Comment by jprochazk** [comment]
Resolved by https://github.com/rerun-io/rerun/pull/2421
