### ISSUE TITLE
Searchable docs

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2263]
Add a search-field to https://www.rerun.io/docs

**Comment by jprochazk** [comment]
We have some constraints for how search should work:
- It should be versioned, or require minimal effort to make it versioned.
- We may want to re-use it for in-app documentation.
- It must be able to ingest not only the docs/examples on `rerun.io`, but also our API references (e.g. https://ref.rerun.io/docs/python,  for any present and future languages)

We've decided to use [meilisearch](https://www.meilisearch.com/) as the search engine. It's fast, flexible enough, and they have SDKs for all the languages we'll be using to interact with it (Rust, JS). We can use [instantsearch](https://github.com/meilisearch/meilisearch-js-plugins/tree/main/packages/instant-meilisearch) to integrate it into our frontend.

The content indexing part most of the work here. For our markdown docs/examples, we just need to collect titles, content, and URLs of each document and example, and all the infrastructure there is already in place. But for API references, we need to use an external tool to generate machine-readable "documentation", load it, and extract what we need out of it. We'll use the following tools for our currently supported languages:
- Rust: rustdoc's nightly JSON output via [rustdoc_json](https://docs.rs/rustdoc-json/latest/rustdoc_json/) and [rustdoc_types](https://docs.rs/rustdoc-types/latest/rustdoc_types/)
- Python: mkdocs backend [`griffe`](https://pypi.org/project/griffe/), with our own type definitions
- C/C++: doxygen's [XML output](https://www.doxygen.nl/manual/customize.html#xmlgenerator), also with our own type definitions

**Comment by emilk** [comment]
Some notes:
* In the search window, we should clearly show what type each hit is (which language API, or neither), e.g. with an icon for each language
* When searching for some archetype, we should make sure the search window shows the high-level archetype doc first, followed by the API docs for each subsequent language
