### ISSUE TITLE
2D line segments with `stroke_width != None`  show up wrong in 3D frustum 

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2279]
**Describe the bug**
```python
import rerun as rr

rr.init("2D Projection", spawn=True)
rr.log_pinhole("world/camera/image", child_from_parent=[[300.0, 0, 150],
                                                        [  0, 300, 150],
                                                        [  0,   0,  1]],
               width=300, height=300)
rr.log_view_coordinates("world/camera", xyz="RDF")
rr.log_line_segments("world/camera/image/lines", positions=[[400.0, 150], [200, 200]], stroke_width=3)
```
With `stroke_width=None` everything works fine. However if `stroke_width` is set to any (?) value other than none the line will not be on the image plane anymore and moves.

**Expected behavior**
I guess `stroke_width` for 2D should be width in pixels, and it should show up accordingly on the image plane in 3D.

**Video**

https://github.com/rerun-io/rerun/assets/9785832/054e4f71-84c0-4a94-9985-95b5dd468ca7

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**

```
rerun_py 0.7.0-alpha.0+ [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu main b263b9f, built 2023-05-29T18:38:22Z
```

**Comment by roym899** [comment]
Same happens with `radius` and points.

**Comment by Wumpf** [comment]
Related to #2494

**Comment by Wumpf** [comment]
![image](https://github.com/rerun-io/rerun/assets/1220815/4967e333-2856-4c69-9718-2fe68a1f4017)

looks like this got fixed a while ago!

ported code I used for this

```
import rerun as rr

rr.init("2D Projection", spawn=True)

rr.log("world", rr.ViewCoordinates.RDF)
rr.log(
    "world/camera",
    rr.Pinhole(
        image_from_camera=[[300.0, 0, 150], [0, 300, 150], [0, 0, 1]],
        width=300,
        height=300,
    ),
)
rr.log(
    "world/camera/lines",
    rr.LineStrips2D([[400.0, 150], [200, 200]], radii=3),
)
```
