### ISSUE TITLE
`rr.log_cleared()` is missing from the "Common API" section of the documentation

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#2348]
**Describe the bug**

`rr.log_cleared()` is missing from the "Common API" section of the documentation. It does show up when searching, in the "Package listing" section (under `clear.py`).

Happens both in 0.6 and HEAD version of the docs.

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/2400
