### ISSUE TITLE
Handle builtin `deprecated` fbs attribute

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2366]
Flatbuffers has a builtin `deprecated` attribute that we currently parse, but don't do anything with.

We need to update the codegen so that:
- Rust yields the appropriate `#[deprecated]` clauses
- Python does whatever is idiomatic there

**Comment by Wumpf** [comment]
since it doesn't have a string it's kinda unusable for us imho. When would we ever want to deprecate something without specifying a reason
