### ISSUE TITLE
Annotation context display is unstable with multiple classes

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#2403]
**Describe the annoyance**

When annotation contexts have multiple classes, their display is flickering due to random ordering of the classes.

https://github.com/rerun-io/rerun/assets/49431240/2a3f025e-701b-43a9-b202-808116ba1a6d

**To Reproduce**

This demo RRD: 
[demo.rrd.zip](https://github.com/rerun-io/rerun/files/11732017/demo.rrd.zip)

Also, the `mp_face` example (#2338) can be used:

```python
examples/python/face_tracking/main.py --demo-image
```

In the timeline, click "video/landmarker/annotation_context" to display the glitch.

**Comment by emilk** [comment]
This is really weird. The UI comes from `ClassDescription::keypoint_connections` which is defined as:

```rs
pub keypoint_connections: Vec<(KeypointId, KeypointId)>
```

So there is no hashmap there. It must somehow get populated in a random order, but I don't immediately see how.

**Comment by abey79** [comment]
I can't reproduce anymore, this has likely been fixed.
