### ISSUE TITLE
Bad CSS for the code block "copy" button

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#2436]
There is a "copy" button there, in the top right corner the code snippet. But you can't see it...

<img width="821" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/dd8729d2-c5c6-4c8c-aa8d-be5f072ca8de">

...unless you happen to hover on it:

<img width="813" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/f4c6f656-aae5-4933-9fc6-14572fdb67a3">

**Comment by JosephMorgan-115** [comment]
URL to specific section: https://www.rerun.io/examples/setup
For me, hovering on the div makes the copy visible and hovering on the actual copy highlights it.

![image](https://github.com/rerun-io/rerun/assets/132992035/fe889941-3502-45f5-a5c1-5eb6ddb748e7)

Do you think it should be visible independent of any hovering?

**Comment by abey79** [comment]
@JosephMorgan-115 I have the same behaviour now (the copy button appears when hovering on the div). Maybe the CSS has been fixed already? @jprochazk can you confirm that?
