### ISSUE TITLE
Use log_transform3d instead of log_rigid3 docs "Spaces and Transforms" docs.

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2472]
Our [Spaces and Transforms](https://www.rerun.io/docs/concepts/spaces-and-transforms) documentation currently uses the depreciated api `rr.log_rigid3` instead of the new `rr.log_transform3d`.

**Comment by abey79** [comment]
Is that fixed by https://github.com/rerun-io/rerun/pull/2496?

**Comment by Wumpf** [comment]
still referenced in:
* `transform3d.md`
* `ros2-nav-turtlebot.md`

consider removing it from the overview of python doc?
