### ISSUE TITLE
Keypoint skeleton is not visible in human-motion demo on web

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2483]
Seems like a layering issue.

If the image is visible we can see keypoints but no skeleton:
![image](https://github.com/rerun-io/rerun/assets/3312232/85c993a7-640d-4edd-8daa-29c9c2f2d815)

If we hide the image and mask then the skeleton is visible:
![image](https://github.com/rerun-io/rerun/assets/3312232/6d2a49c0-e87c-40ef-a2a7-816eb3b49bd0)

**Comment by emilk** [comment]
I can reproduce on Safari on Mac.
On Firefox and Chromium on Mac it works.

Lowering (!) the `w_scale_bias` multiplier in `crates/re_renderer/shader/utils/depth_offset.wgsl` seem to help.

Original: 1000.0.
Works: 100.0
