### ISSUE TITLE
2D point radius != None shows up inconsistently in 2D and 3D view

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2494]
**Describe the bug**
Logging 2D points to an image plane they show up as huge 3D points (pixels converted to meters?). Things look fine as long as `radii=None`.

**To Reproduce**
```python
import numpy as np
import rerun as rr

rr.init("projection", spawn=True)

rr.log_view_coordinates("world/camera", xyz="RDF", timeless=True)

rr.log_pinhole(
    "world/camera/image",
    child_from_parent=np.array([[500, 0, 250], [0, 500, 250], [0, 0, 1]]),
    width=500,
    height=500,
)
rr.log_image("world/camera/image/rgb", np.ones((500, 500, 3)))
rr.log_points("world/camera/image/points", np.random.uniform(0, 500, (30, 2)), radii=1)
```

**Expected behavior**
![good](https://github.com/rerun-io/rerun/assets/9785832/59a52fc6-b7a9-4619-80a8-e0035cb33b5a)

**Actual behavior**
![bad](https://github.com/rerun-io/rerun/assets/9785832/5c8e636b-249b-44e7-8bd8-eb0e7322af81)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.7.0 [rustc 1.69.0 (84c898d65 2023-04-16), LLVM 15.0.7] x86_64-unknown-linux-gnu prepare-0.7 9cf3033, built 2023-06-16T15:47:32Z
```

**Comment by roym899** [comment]
Maybe related to #2279.

**Comment by emilk** [comment]
It seems all points in 2D views have too small radius, at least on retina displays

**Comment by abey79** [comment]
This issue has been encountered and reported by some of our users. IMHO, since the 2D point radius correspond to "pixel" units in the 2D space view, and these pixels have a defined size in the 3D space view (on the pinhole widget projection plan), we should be able to adjust the 3D radius to be consistant. That would involve taking into account both the pinhole project itself and the "Image plan distance" parameter.

#### Expected

<img width="704" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/8612d52d-423b-4d37-ad12-0bbce72ec458">

#### Actual

<img width="706" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/4ac35250-9a59-4a28-a26c-d49e9239b5db">

**Comment by abey79** [comment]
Fun fact: setting the "Image plan distance" to the same value as the pinhole focal yields the correct behaviour:

<img width="1054" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/3ec88869-a296-488d-8828-1747d62fbd78">

**Comment by SeaOtocinclus** [comment]
@abey79  FYI, it seems to happen too if you are logging a Boxes2D, so the problem is most likely happening for more than one archetype.

**Comment by abey79** [comment]
Indeed, and the glitches are... interesting:

<img width="1786" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/298f4e2d-fc5a-47e8-b4b7-8fd459adc5a2">

Again, like for points, better handling of "Image plan distance" might improve on this issue:

<img width="1742" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/d5cf0dae-39dd-4599-bf69-0eecc80d966c">

<details>
<summary>Code</summary>

```python
import numpy as np
import rerun as rr

rr.init("rerun_example_pinhole")
rr.connect()

rng = np.random.default_rng(12345)

image = rng.uniform(10, 30, size=[200, 300, 3])
rr.log("world/image", rr.Pinhole(focal_length=300, width=300, height=200))
rr.log("world/image", rr.Image(image))
rr.log("world/image/point", rr.Points2D([50, 70], radii=5))
rr.log("world/image/box", rr.Boxes2D(centers=[100, 100], half_sizes=[20, 30], radii=2))
```
</details>
