### ISSUE TITLE
3D Affine transforms should be represented correctly by three arrows

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2503]
Follow on to https://github.com/rerun-io/rerun/issues/753.

Since we now support full 3D affine transforms, and these transforms should be represented in 3D by a set of three colored arrows, the arrows should represent not just the rigid transform but also shearing and scaling. For instance:

- If the transform involves scaling in the x-axis by a factor of 2, the red arrow should be two times longer than the other two.
- If the transform isn't orthogonal, the arrows shouldn't be orthogonal either.
- If one transform scales points uniformly by a factor of 2, and another transform is a pure rotation, the three arrows of the first should be two times as long as the three arrows of the second.
    - Corollary: Any configurable sizing of the transforms should be set globally for the whole view.
    - It may be difficult to have these make sense to express in screen space sizes.

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/1111
