### ISSUE TITLE
Display help content on the empty screen after startup

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#2513]
The empty state of the viewer is currently a huge wasted opportunity. 

![image](https://github.com/rerun-io/rerun/assets/2624717/ee93a897-7118-4b57-a146-ea86eed62f20)
This screen does convey that you can connect to it ("listening on port ...") and that nothing is broken ("Ready") but not much else.  We could do a much better job of conveying what Rerun is and how to use it by showing what actions are available to take. This could e.g. be a grid of big buttons that might have helpful text and illustrations.

### Possible actions
- Open a recording
    - Shows that there are recordings that can be saved, and that the Rerun viewer is something that could view it
    - Should also indicate that you can drag and drop a recording file into the window
- Open a data file
    - Shows that Rerun is also a versatile data viewer
    - Currently just images and meshes
    - Once #2229 has landed should also indicate you can drag and drop
- Go to docs
- Start onboarding tour
    - #2699
- load an example dataset
    - #2699
- Connect from an SDK
   - The port we're currently listening on + instructions on how to send data  with the SDK from your code
- Connect to a websocket stream?
   - Don't even know if this is possible right now from the native viewer but if it is there should be instructions for that too

**Comment by emilk** [comment]
Let's wait for a design from Mårten
