### ISSUE TITLE
Return iterators rather than vectors when deserializing in Rust backend

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2523]
TODO:
- [ ] Support for end-to-end iterators (`dyn`)
- [ ] Integrate fallible iterators
- [ ] Generate fully typed associated iterator types

---

The deserialization routines for components and datatypes in the Rust backend currently return full-on `Vec`s, while there is in fact nothing preventing us from returning lazy iterators.

Current:
```rust
pub trait Datatype {
    // [...]

    fn from_arrow_opt(data: &dyn ::arrow2::array::Array) -> Vec<Option<Self>>
    where
        Self: Sized;

    // [...]
}

pub trait Component {
    // [...]

    fn from_arrow_opt(data: &dyn ::arrow2::array::Array) -> Vec<Option<Self>>
    where
        Self: Sized;

    // [...]
}
```

`impl trait` is still unstable when used in a return position in traits, but it wouldn't be too much work to add an associated type, especially now that we have GATs! e.g.:
```rust
pub trait Datatype {
    type Iterator<T> = /* ... */

    // [...]

    fn from_arrow_opt(data: &dyn ::arrow2::array::Array) -> Self::Iterator<Option<Self>>
    where
        Self: Sized;

    // [...]
}

pub trait Component {
    // [...]

    fn from_arrow_opt(data: &dyn ::arrow2::array::Array) -> Self::Iterator<Option<Self>>
    where
        Self: Sized;

    // [...]
}
```

Of course we could also settle for a boxed trait object (`Box<dyn Iterator<Item = Self>>`) instead, but why do a half arsed job when it's all codegen'd anyway :upside_down_face:

**Comment by teh-cmc** [comment]
Update: we now know for a fact that `Box<dyn Iterator>` is not viable.

**Comment by jleibs** [comment]
This will be a blocker for 0.9 but doesn't need to block landing into main once we've cut 0.8.

**Comment by teh-cmc** [comment]
Also, we need to take care of fallibility, e.g. by using something like https://docs.rs/fallible-iterator/latest/fallible_iterator/index.html

**Comment by emilk** [comment]
Probably related: `just py-build --release && ./examples/python/open_photogrammetry_format/main.py` is ~100x slower than it should be (10s/frame)

**Comment by emilk** [comment]
If this helps as much as we hope, we can then revert the central commit of https://github.com/rerun-io/rerun/pull/2950 (the added aching)

**Comment by nikolausWest** [comment]
Let's discuss if we even need this at all. Most of the performance problems have already been fixed.

**Comment by emilk** [comment]
I think we should do this instead:
* https://github.com/rerun-io/rerun/issues/3109
