### ISSUE TITLE
Re-enable codegen on Windows

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2591]
Codegen (specifically, `re_types_builder/build.rs` & `re_types/build.rs`) has been disabled on Windows in #2592 because it was somehow computing different sha256 sums (??) and thus breaking the CI.

This isn't too bad of an issue as it only affects contributors on windows that are trying to modify IDL definitions but should nonetheless be fixed sooner than later.

**Comment by jleibs** [comment]
The sha-mismatch is likely another case where we are likely hitting line-ending inconsistencies introduced by git.

Also, when generating the files on windows we need to take care to normalize our path-separators. Running `cargo codegen` on windows now modifies the path comment in every file.

**Comment by emilk** [comment]
`re_types/build.rs` is gone, and the hashing is completely client-side (no hashes checked in), so I think this issue no longer applies.
