### ISSUE TITLE
Rust SDK silently drops data in some situations

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2627]
Minimal reproduce:

```rust
use rerun::{
    components::{ColorRGBA, Point3D},
    time::{TimeType, Timeline},
    MsgSender, RecordingStreamBuilder,
};

fn main() -> anyhow::Result<()> {
    rerun::external::re_log::setup_native_logging();

    let (rec_stream, storage) = RecordingStreamBuilder::new("images").memory()?;
    let timeline = Timeline::new("keyframe", TimeType::Sequence);

    let pt = Point3D {
        x: 1.0,
        y: 1.0,
        z: 1.0,
    };

    MsgSender::new("world/pts")
        .with_time(timeline, 1)
        .with_component(&[pt])?
        .with_splat(ColorRGBA::from_rgb(161, 34, 212))?
        .send(&rec_stream)?;

    rerun::native_viewer::show(storage.take())?;

    Ok(())
}
```

Results in this:

![image](https://github.com/rerun-io/rerun/assets/1148717/f42d27ee-83f2-4f75-a8ed-3e8121ca024a)

Seems like data is lost somehow. Some flushing that is not being done?

**Comment by emilk** [comment]
Adding a call to `rec_stream.flush_blocking();` before `storage.take();` solves it.

Seems like we should at least warn when data is being silently lost, or better yet: make `take()` block until data is flushed.

**Comment by teh-cmc** [comment]
Yeah, I think the most user-friendly solution here would be to do the same thing we do in the jupyter notebook internals in Python, namely: internally keep track of the `RecordingStream` associated with this `MemorySinkStorage`, and flush on behalf of the user where it makes sense.

It's a bit blurry how all of this works though, I'll have a quick look to see what's possible.
