### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#2635]
The CI is so slow these days. I can't take it.

* Build Web Wasm 4m20s
* Build wheels: 11m
    * Building: 5m30s
    * e2e roundtrip tests: 3m30s
* Build Web Demo 4m40s
* Upload Web Demo: 40s

Ideas:
* Is the web-viewer built twice (again in "Build wheels")?
* Can we speed up e2e roundtrip tests? And/or just run on `main` - they seldom catch anything anyway
* What is slow when building web demo? Can we put the required datasets on the Docker image instead of downloading them?
* We can use a smaller/faster set of examples for `test.rerun.io`
  * #2566

**Comment by abey79** [comment]
I just noticed that, is it known?

<img width="1038" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/2a667566-e9a0-4c64-8c53-9aeb2b65b123">

**Comment by jprochazk** [comment]
After a few PRs:
- https://github.com/rerun-io/rerun/pull/2740
- https://github.com/rerun-io/rerun/pull/2753

I'm happy to report that we have shaved off anywhere from 8 to 12 minutes from the "main" path of the PR CI runs. 

- before: https://github.com/rerun-io/rerun/actions/runs/5554804192
- after: https://github.com/rerun-io/rerun/actions/runs/5613492308

What this means is `build web + build wheel -> build demo app -> upload web demo` takes about 8-12 minutes, where previously it took about 17-20 minutes. (Side note: rendering done by GHA here is not great, jobs overlap in strange ways, you have to hover a job to see the actual dependency path between some subset of the jobs)

There's still a lot of room for improvement. Most of it will come from https://github.com/rerun-io/rerun/issues/2762.

I believe we can squeeze much more performance out of GHA with some better job sequencing and/or (ab)using Docker.

**Comment by Wumpf** [comment]
Lot of work done this cycle. Let's create a new tracking issue for remaining items @jprochazk

**Comment by jprochazk** [comment]
https://github.com/rerun-io/rerun/issues/2776
