### ISSUE TITLE
Frustum lines flicker in and out when tracking 3D camera

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2651]
See post by @javrtg in https://github.com/rerun-io/rerun/issues/2638#issuecomment-1628627942

**Comment by Wumpf** [comment]
This seems to be happening due to some frame delay. We can probably fix this by piping through the information to the camera scene part if it is tracked and then simply not render the frustum lines - they are annoying in any case while tracking a camera

**Comment by nikolausWest** [comment]
![output](https://github.com/rerun-io/rerun/assets/71815905/62c74b68-196e-439e-afb8-ce6f2a2dcc7c)

**Comment by emilk** [comment]
Was this solved by https://github.com/rerun-io/rerun/pull/2667?
* https://github.com/rerun-io/rerun/pull/2667

**Comment by Wumpf** [comment]
PR linked to the wrong issue. this one here is fixed.
