### ISSUE TITLE
Consistent way to add/remove views and data to the blueprint in the UI

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2697]
Adding and removing views to the viewport or data to views is currently very hard to find, inconsistent, and hard to understand (see screenshots of current state below).

### What is currently possible
- Add a new space view to the viewport
- Add or remove an new entity to a space view
- Clone a space view

### We also need to be able to

- [ ] Change the type of a space view
    - Note: This will actually entail creating a new space view with the new type, including all the blueprint settings (both for the view and any data) that make sense for the new type and then removing the old view (i.e. we don't persist old settings)
    - This means the UI should somehow indicate what blueprint settings will be lost when changing types
- [ ] Clone a space view as another type (i.e. same as above but keep the current space view as well)

The design should take into consideration that we will have more expressive data blueprints in the relatively near future. (Check out the different types of `Data` blueprint objects proposed in the [Blueprint Store RFC](https://github.com/rerun-io/rerun/blob/main/design/blueprint_store.md#blueprint-apis))

### Screenshots from current state
**Adding a new view**
<img width="874" alt="Screenshot 2023-07-14 at 13 05 43" src="https://github.com/rerun-io/rerun/assets/2624717/3e48113d-24a9-420e-b46c-f31997b891f0">
<img width="790" alt="Screenshot 2023-07-14 at 13 12 50" src="https://github.com/rerun-io/rerun/assets/2624717/473b826e-fff0-42f6-bbe6-80e0fd1e3304">

**Adding a new entity (data) to a view**
<img width="874" alt="Screenshot 2023-07-14 at 13 06 40" src="https://github.com/rerun-io/rerun/assets/2624717/00d88b2a-3db6-40bc-9a29-686655203871">
<img width="775" alt="Screenshot 2023-07-14 at 13 08 48" src="https://github.com/rerun-io/rerun/assets/2624717/b0aefa8e-eb7b-4153-91cf-a9b1375cf943">

**Comment by abey79** [comment]
* duplicated by #4492
