### ISSUE TITLE
No way to deselect

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#2709]
**Describe the annoyance**
Once an entity is selected, I couldn't figure out a way to deselect it, other than selecting another entity. So to have nothing highlighted I have to select an entity that isn't in the view or delete the entity that is currently selected.

Generally this feels a bit unintuitive. I think most other programs would, for example, deselect when clicking into any white space.

**Comment by roym899** [comment]
Seems like this mostly applies to the 2D cases, because in 3D clicking into empty 3D space does deselect. Still, white space of the UI seems reasonable to deselect as well.

**Comment by abey79** [comment]
Clicking in left panel's empty space should deselect

**Comment by abey79** [comment]
Also, command-clicking on the item in the left panel deselects it.

**Comment by roym899** [comment]
On the command clicking: this actually also works for entities inside the views, so this works well, once you know about it. However, it does not work for the title of the views. I would expect selection / deselection of the title to behave similar to the title in the left panel.

**Comment by roym899** [comment]
Reopening since clicking in empty space in 3D view doesn't deselect anymore. 

Could we add deselect when clicking in the empty space right of the rerun.io text?

**Comment by emilk** [comment]
I'll can add to hitting escape deselects. That makes sense imho.
