### ISSUE TITLE
Don't inline recursive datatypes, defer a runtime call to the child type instead

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2759]
The Rust backend currently inline child datatypes into their parent, leading to giant `to_arrow_datatype()` that both bloat the code and are unreadable.

Replace the inlining with a runtime call to the child's `to_arrow_datatype()` method instead, akin to what we do on the serialization/deserialization path.

**Comment by Wumpf** [comment]
Same on Cpp backend
