### ISSUE TITLE
Generate archetype docs

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2775]
We require 3 different kinds of docs for our archetypes:
- Native language docs (docstrings)
This is automatically handled by codegen already.
- [Doc reference](https://www.rerun.io/docs/reference/data_types)
We need to completely overhaul this for the new type-based APIs, and as much as possible automate it via codegen or it's going to be out-of-sync _very fast_.
- High-level example page (doesn't exist yet!)
Needs to show a thumbnail for all archetypes and link to the reference.

---

API references are already taken care of by the language-specific codegen backends, but we still need a codegen backend that takes IDL definitions in and turn them into documentation for the website (e.g. [all the archetype related pages](https://www.rerun.io/docs/reference/data_types)).

Contents of:
`docs/content/reference/data_types`

**Comment by emilk** [comment]
Related: the doc-examples should be auto-included. No need to add manual `\cpp ## Example` to all our archetypes imho
