### ISSUE TITLE
Release: 0.8

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2779]
## Things to cover in release notes
 - Blueprint storage disabled on web.
 - transform visualization
 - highlight some bugfixes?
 - pinhole XYZ viewcoordinates stuff
 - extrinsics and intrinsics can be logged on same path
 - upcoming python & c++ apis
 - 2D / 3D Space Views are now separate types
 - Rust serve api

## Regressions to fix before release:
 - [x] https://github.com/rerun-io/rerun/issues/2758
 - [x] https://github.com/rerun-io/rerun/issues/2537
 - [x] https://github.com/rerun-io/rerun/issues/2232
 - [x] #2507
 - [x] #2556
 - [x] #2808
 - [x] #2690
 - [x] #2811
 - [x] #2819
 - [ ] [anything tagged with milestone 0.8](https://github.com/rerun-io/rerun/milestone/2)

## Other easy bugs to fix before release
- [x] #2575

**Comment by Wumpf** [comment]
it was done!
