### ISSUE TITLE
`Mesh` migration to archetypes

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2788]
Turn into sub-issues as needed.

- [x] Python support
  - [x] Extensions
  - [x] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Rust support
  - [x] Extensions
  - [x] Unit test (constructors, rust-to-rust roundtrip)
  - [x] Doc example
- [x] C++ support
  - [x] Extensions
  - [x] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Cross-language roundtrip test
- [x] Remove old components
  - [x] Clean up `re_components`
  - [x] Port viewer to use new types and queries

**Comment by nikolausWest** [comment]
The intention is to split into multiple components
