### ISSUE TITLE
`Tensor` (and its many friends) migration to archetypes

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2792]
Turn into sub-issues as needed.

- [x] Implement `jpeg_quality`
- [x] Implement `f16`
- [x] Python support
  - [x] Extensions
  - [x] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Rust support
  - [x] Extensions
  - [x] Unit test (constructors, rust-to-rust roundtrip)
  - [x] Doc example
- [ ] C++ support
  - [ ] Extensions
  - [ ] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Cross-language roundtrip test
- [x] Remove old components
  - [x] Clean up `re_components`
  - [x] Port viewer to use new types and queries

**Comment by jleibs** [comment]
Split C++ out into its own issue:
https://github.com/rerun-io/rerun/issues/3380
