### ISSUE TITLE
Rerun python package readme renderes poorly in PyCharm

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2812]
<img width="2314" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/a01630b8-ff9a-4e50-b572-28136417db45">

No idea why, other markdowns seems to look fine

**Comment by abey79** [comment]
Looks fine in PyCharm 2024.2

<img width="1830" alt="image" src="https://github.com/user-attachments/assets/310b659e-ff38-443c-93e3-337c9dff8eb6">
