### ISSUE TITLE
Location of transform visualization controls is unintuitive

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2840]
**Describe the bug**
Based on https://github.com/rerun-io/rerun/pull/2577
I was expecting to be able to turn on transform visualization in the api transform_3d demo.

**To Reproduce**
```
python tests/python/test_api/main.py --test transforms_rigid_3d
```

**Expected behavior**
Expect to find an entity property to enable / disable visualization of the transforms, but no such option exists.

**Comment by Wumpf** [comment]
They are apparently just not where you expect them?
![image](https://github.com/rerun-io/rerun/assets/1220815/6bad2a25-518c-4715-9835-11d1672e3818)

![image](https://github.com/rerun-io/rerun/assets/1220815/ee17616f-902d-407c-9884-6ca9544f4ca4)

**Comment by Wumpf** [comment]
we don't inheritance/global options on this one yet, that's probably what we're missing? I'm a bit worried our systems aren't up for the task there yet - we already have the problem that disabling interactivity on a group correctly propagates but still shows as "enabled" on all children (on an individual basis they are!)

**Comment by Wumpf** [comment]
This is one of the many problems related to how we do grouping. We need to rethink that in general which is a different issue than just any particularities on transform controls.
