### ISSUE TITLE
Transform arrow length jumps to 10000000 when selecting first transform

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#2841]
To reproduce:
```
python tests/python/test_api/main.py --test transform_test
```
Click a transform, such as `rigid3`

Immediately upon selection the transforms arrow length property jumps to 10000000
![image](https://github.com/rerun-io/rerun/assets/3312232/57cc0aad-4b46-4b72-ba6a-12dfe860732e)

This only happens for the first transform selected after resetting the scene.

**Comment by Wumpf** [comment]
I saw this before fixing the heuristic issue in #2808 but didn't notice it afterwards anymore
