### ISSUE TITLE
Expand clickable area in blueprints list

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2855]
It seems that the area indicated in red can't be clicked. However, it has a hover effect which indicated that it's clickable.

I found this confusing when I was quickly clicking through the items — sometimes my click wouldn't register.

<img width="298" alt="Component 3 (1)" src="https://github.com/rerun-io/rerun/assets/875708/3034b62a-c9c3-41d2-8533-e360e9bdf9e0">

**Comment by abey79** [comment]
I suspect that the area covered by the 2px expansion is not actually clickable. This control will need a complete rewrite I believe:
- it needs the proper triangle (#2738)
- it needs suppression of the expansion effect on the triangle
- it needs better control the highlight area (which is negatively affected by suppressing the expansion, and is hard to work around)

**Comment by abey79** [comment]
Fixed by https://github.com/rerun-io/rerun/pull/3118
