### ISSUE TITLE
Disable text selection in demo HTML header

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2856]
Tiny issue: Sometimes when clicking things in the topbar, I accidentally move my cursor 1px and select (as in text selection) something in it. That's OK for websites, but in apps, it often makes the UI feel a bit...flaky. A simple `user-select: none` on all the items in the top bar would disable text selection there.

<img width="484" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/5f007b2e-cacc-4995-8429-bbd67ccfec06">

**Comment by faizalmsdev** [comment]
Did anyone changed it?
