### ISSUE TITLE
Lines in timeline should go between data, not through it

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2860]
(Unless someone genuinely thinks the current way is better!)

Current (lines go _through_ the data)

<img width="762" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/f1c670ee-6bb9-4f0c-8487-85452f886e0e">

Desired (lines sit between the data)

<img width="654" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/1dde5931-dc99-432f-9534-8b5846c62cec">

**Comment by abey79** [comment]
That blue line when selected should be gone as well, I suppose?

<img width="469" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/3abca5ac-0c92-4b14-b23b-657e291a4537">

**Comment by martenbjork** [comment]
> That blue line when selected should be gone as well, I suppose?

Yes! I think the highlighting can be done in better ways (like highlighting the data, or the row's background)

**Comment by emilk** [comment]
I changed from "lines as separators" to "lines as things upon which data hangs" as part of https://github.com/rerun-io/rerun/pull/1557 as I think it looked better with the new data density graphs
