### ISSUE TITLE
Use correct unicode symbols for keyboard shortcut hints

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#2862]
We currently use the wrong symbol for `ctrl`. It's not the thin caret that we have on our keyboards, it's a wider, more geometric arrow.

<img width="460" alt="image" src="https://github.com/rerun-io/rerun/assets/875708/8421f844-99c5-4984-855b-5220d855bd0d">

## TODO
Update the text strings to use the correct unicode symbol
- [x] Tooltips
- [x] Menus

Tip: Maybe create a helper function for this to avoid hard coding the unicode symbol everywhere?

`keyboard_shortcut(["ctrl", "command", "P")` => `⌘⇧P`?

## Reference
For reference, these are the correct unicode symbols (they can be copy/pasted)

Command (or Cmd) ⌘
Shift ⇧
Option (or Alt) ⌥
Control (or Ctrl) ⌃
Caps Lock ⇪

**Comment by abey79** [comment]
This needs fixing in egui, and then it'll be fool-proof. It'll take an egui release *and* a dependency version bump here for this to show up in demos, though.
