### ISSUE TITLE
`raw_mesh --scene buggy` keeps repainting even when nothing changes

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#2888]
Repro:
```sh
$ cargo r -p raw_mesh
# watch your CPU burn
```

This seems to be a regression introduced by https://github.com/rerun-io/rerun/pull/2846.

**Comment by Wumpf** [comment]
we had a redraw bug that was fixed in 0.8.1. Could be that this got fixed with that, need to confirm.

**Comment by emilk** [comment]
Confirmed fixed (at least I fail to reproduce on latest `main`)

**Comment by emilk** [comment]
I interpreted the original title as a freeze (infinite loop), but it is really an unnecessary repaint, and yes, it is still there.
