### ISSUE TITLE
Make rerun_c smaller

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#2905]
`rerun_c` depends on `re_types` through `re_sdk`All it needs is like `Data{Cell/Row}` and `RecordingStream`. Maybe we should have an option an `re_sdk` to discard all of the archetype stuff.

_Originally posted by @teh-cmc in https://github.com/rerun-io/rerun/pull/2901#discussion_r1282992216_

**Comment by emilk** [comment]
Note: cargo features should be additive, and `--all-features` should enable the maximum set, hence we should not have features to _disable_ stuff, instead we should have an opt-out (default) feature for all the standard datatypes/components/archetypes.

**Comment by emilk** [comment]
This should be fairly easy now - I think it only needs to depend on `re_types_core`

**Comment by Wumpf** [comment]
apparently there's no easy way to change linker settings per crate. Guess this part is less important anyways since we're not shipping a shared library but just a static one which can be stripped during _actual_ linking (static libraries are typically just packaged up object files with minimal to no linking)
