### ISSUE TITLE
Docs links to GH are broken

### ISSUE THREAD

**Issue by banisadr** [rerun-io/rerun#2911]
**Describe the bug**
If you click "Edit page" on any of the doc pages, it takes you to a Github page with 404.

**To Reproduce**
1. Go to https://www.rerun.io/docs
2. Click "Edit page"

**Expected behavior**
Doesn't 404

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/12058745/2d870bca-a92f-4d57-b51d-b8dbfe5e57c5)

**Comment by nikolausWest** [comment]
Wow, what a miss, thanks for reporting @banisadr

**Comment by jprochazk** [comment]
These were not updated after our docs migration, it should be fine now.
