### ISSUE TITLE
Add section to examples docs with external examples

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2928]
There are a bunch of great external examples (not included in the Rerun repo) that are currently hard for users to find. We should add them all to the examples page.

This requires:
- Taking new screenshots
- Which in turn requires recording new rrd files for all the examples

Would be nice if:
- We could update these to use the new object oriented api's that are coming in 0.9

**Comment by nikolausWest** [comment]
External examples:
- https://github.com/rerun-io/tapnet
- https://github.com/rerun-io/point-shap-e
- https://github.com/rerun-io/limap
- https://github.com/rerun-io/simplerecon
- https://github.com/rerun-io/MCC
- https://github.com/rerun-io/slahmr
- https://github.com/rerun-io/grounding-sam
-

**Comment by roym899** [comment]
Closed by #3020
