### ISSUE TITLE
Docs show live web viewer where possible

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#2935]
Wherever practical (for instance small enough rrd file), our examples and docs on rerun.io should embed a live web viewer that shows the results.

We want the output to be completely deterministic, which requires blueprints.

**Comment by emilk** [comment]
Related work:
* https://github.com/rerun-io/rerun/pull/6419
* https://github.com/rerun-io/rerun/pull/6409
* https://github.com/rerun-io/rerun/pull/6407

**Comment by jprochazk** [comment]
The infrastructure to build the doc snippets and upload them to GCS was done in:
- https://github.com/rerun-io/rerun/pull/5438

**Comment by jprochazk** [comment]
- https://github.com/rerun-io/rerun/pull/6504

**Comment by emilk** [comment]
Done! See for instance https://rerun.io/docs/reference/types/archetypes/arrows3d
