### ISSUE TITLE
Build wheels for abi3-manylinux_2_31_aarch64

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#2951]
As the title say, we should generate wheels for abi3-manylinux_2_31_aarch64

**Comment by Wumpf** [comment]
Replaces #2355

**Comment by emilk** [comment]
* Related to https://github.com/rerun-io/rerun/issues/2628

**Comment by Wumpf** [comment]
This keeps coming up and we also have the first asks for a C++ arm64 linux version! (https://discord.com/channels/1062300748202921994/1169763840607653910/1169763840607653910)

**Comment by Wumpf** [comment]
Related to
* #4136

**Comment by emilk** [comment]
We should be able to do this pretty easy with cross-compilation

**Comment by emilk** [comment]
This is also very relevant for Android

**Comment by chengguizi** [comment]
Would also like to express the interests on arm64 linux pre-build!

Before it happens, is there anyway to get it working? Say compiling natively on an arm64 platform?

**Comment by emilk** [comment]
Yes, checking out the repository and compiling it yourself should work. I believe @abey79 has experimented with this.

**Comment by chengguizi** [comment]
Yes, I have successfully done it! On x11 gui it works, but on wayland it crashes. Good enough

**Comment by Wumpf** [comment]
* Resolved in #5543
