### ISSUE TITLE
Improve changelog generation

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#2955]
- Add support for commit annotations:
  - [ ] https://github.com/rerun-io/rerun/pull/2958
  - [ ] `[changelog:link(<commit hash>)]` - group together with `<commit hash>`

Use the above annotations to improve the generated part of the changelog

**Comment by emilk** [comment]
We have made several improvements to `generate_changelog.py`. It is now very nice to use it, and the manual work needed to group similar entries in the changelog is, I believe, easier to do at release time than using custom annotations when building PRs.
