### ISSUE TITLE
`ClearEntity` Archetype & migration

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3023]
In the new APIs style we don't have a way yet to clear entities. We decided to emulate this behavior with a special kind of archetype, getting rid of `EntityPathOpMsg` in the process.

- [x] Python support
  - [ ] Extensions
  - [ ] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Rust support
  - [x] Extensions
  - [x] Unit test (constructors, rust-to-rust roundtrip)
  - [x] Doc example
- [x] C++ support
  - [x] Extensions
  - [x] Unit test (constructors, serialization)
  - [x] Doc example
- [x] Cross-language roundtrip test
- [x] Remove old components
  - [x] Clean up `re_components`
  - [x] Port viewer to use new types and queries

**Comment by Wumpf** [comment]
internal slack thread on the topic https://rerunio.slack.com/archives/C033K5VS2KD/p1689179014868759

**Comment by emilk** [comment]
I guess it needs flag to inform if it is recursive or not
