### ISSUE TITLE
Improve Component documentation

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3042]
The "Loggable Data Types" section lists all archetypes' components but we don't have a documentation of their semantics (and underlying data type).

This should be improved as follows:
- each component should have a dedicated, linkable paragraph providing data-centric information (what they contain, what's their semantic)
- links in archetypes' docs

**Comment by emilk** [comment]
I think this can be fixed with the same docs-generation as @jprochazk is working on for https://github.com/rerun-io/rerun/issues/2775

**Comment by emilk** [comment]
There is good documentation for all components now at https://www.rerun.io/docs/reference/types/components
