### ISSUE TITLE
Make Welcome Screen UI reactive

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3043]
Make the three columns of the Welcome Screen are not reactive, e.g. they remain horizontally arranged even on narrow screens. They should become vertically arranged on narrow screens.

It should even work on Mobile.

**Comment by emilk** [comment]
What's left on this? Testing on Mobile?

**Comment by abey79** [comment]
> What's left on this? Testing on Mobile?

It should be fixed by #3219
