### ISSUE TITLE
bad onboarding experience - `cargo deny install` requires rust 1.70

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3049]
We're on Rust 1.69 right now but our build instructions say to run `cargo deny install` which won't work when you're in the repo because of the rust toolchain file. Meaning one needs to find out on their own which is the last working version

**Comment by emilk** [comment]
Did you mean to write `cargo install cargo-deny` (twice)?

**Comment by Wumpf** [comment]
some problems go away on their own ;). Plenty of updates later this isn't an issue anymore
