### ISSUE TITLE
Use correct "minus" unicode char for keyboard shortcut hints

### ISSUE THREAD

**Issue by martenbjork** [rerun-io/rerun#3053]
Similar to #2862. For shortcuts like `⌘ –`, we should use the [proper minus character](https://www.compart.com/en/unicode/U+2212), `−`. 

Before:

\+
\- (too small, misaligned)

After:

\+
− (wider, behaves more like a monospace font)

Bonus: Welcome to the fun world of dashes:

![Image](https://user-images.githubusercontent.com/875708/261964368-2a2a69f5-2871-4e1b-bb00-bdc3624165f2.png)

**Comment by emilk** [comment]
Will be closed by https://github.com/emilk/egui/pull/3271
