### ISSUE TITLE
Glitch in data view when multiple components are selected

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3071]
When more than one component is selected, all but the first have a glitch in their data `ScrollArea`:

https://github.com/rerun-io/rerun/assets/49431240/bc2fbfd0-c804-482e-8ff3-ab5c04be60b9

(Don't mind the flickering, this is my computer having issues.)

**Comment by emilk** [comment]
Looks like we could be missing a `ui.push_id`

**Comment by abey79** [comment]
No longer reproduces
