### ISSUE TITLE
Remove limit on line and point count

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3076]
Longstanding problem with our line & point renderers is that they each impose a maximum number of line strip segments, line strip counts and points. On top of that they also always allocate the same "buffer textures" (workaround for not actually having buffers)
This was done for easier implementation originally but sticked around for very long now.

-> Line & point strip builder/drawdata should have a dynamic size.
For what we need it is still okay to know the size in advance (we typically do!), but we the only bound we should put on the size is the maximum texture size.

This will
* allow users to have more lines and points
* reduce memory usage when using fewer
* allow to remove `shared_render_builders.rs`

**keep in mind that we still need to clamp when hitting the maximum (texture) size**

**Comment by emilk** [comment]
The current maximum point cloud size is 4Mi, limitied by the fixed-size 2048² texture, controlled by `DATA_TEXTURE_SIZE` in `crates/re_renderer/src/renderer/point_cloud.rs`
