### ISSUE TITLE
File -> Open does not load rrd successfully

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3080]
**Describe the bug**
The file menu -> open pathway for loading an RRD has no effect.  The viewer just stays as the "Ready -- listening on port" screen.

**To Reproduce**
1. Run the viewer
2. Try to open an RRD

**Expected behavior**
The RRD should open.

**Affected Versions**: 0.8.0, 0.8.1

**Affected OSes**
 - Definitely: Ubuntu
 - Maybe: Windows

**Comment by emilk** [comment]
It works on my Mac.

**Comment by jleibs** [comment]
This appears to be fixed on main already through the new welcome screen behavior.  The fundamental problem appears to be that the rrd is successfully opened (loaded into the store-hub) but never set to active.

**Comment by emilk** [comment]
That makes sense!

**Comment by emilk** [comment]
Let’s see if we can easily backport the fix for 0.8.2
