### ISSUE TITLE
Only show image in 3D space view if there's a pinhole camera

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3092]
Right now if you log an image and put it into a 3D space view, we'll draw a rectangle expanding into X and Y at the origin with pixels being unit size. This is almost never what you want it want and completely messes up heuristics as it enlarges the "extended bounding box".

This can easily happen by accident if you first log an image and then a pinhole camera!

**Comment by jleibs** [comment]
Resolved by: https://github.com/rerun-io/rerun/pull/3822
