### ISSUE TITLE
Reduce log-spam from analytics cert issues

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3104]
When changing our proxy we spent half an hour with all rerun instances outputting an error about certs
```
[2023-08-24T16:15:52Z ERROR rustls::conn] TLS alert received: AlertMessagePayload {
        level: Fatal,
        description: HandshakeFailure,
    }
 ```
 
Need to be careful about not just blanket silencing all TLS errors since a persistent error like this could be a real certificate problem we need to be aware of, or even something malicious like a MITM attack.

**Comment by emilk** [comment]
Let's silence spam from `rustls` in release builds, and also remove the extra `GET` call in `crates/re_analytics/src/sink_native.rs`
