### ISSUE TITLE
Closing the viewer takes several seconds

### ISSUE THREAD

**Issue by asuper0** [rerun-io/rerun#3106]
Depends on the size of cached data, closing viewer could take 5 or more than 10 seconds.
Why does it takes so long time? Could you just close it in a rude way?

**Comment by emilk** [comment]
I'm guessing it is because of save the app state or blueprint to disk.

You should be able to see what is slow [by starting the profiler](https://github.com/rerun-io/rerun/issues/3083).

* Maybe related to https://github.com/rerun-io/rerun/issues/3098

**Comment by asuper0** [comment]
It seems help by resetting the viewer.

The profiler don't show the reason. I tried some times.

![exit1](https://github.com/rerun-io/rerun/assets/41113804/f76d3542-8d30-4646-9c92-fe9f3f463794)

![exit2](https://github.com/rerun-io/rerun/assets/41113804/b2035ef5-a167-4de2-abdd-c24e9c8acc0c)

As the two figures show, the profiler only catch 200~300ms, but the closing time are 700ms for figure 1, and 3000ms for figure 2.

**Comment by emilk** [comment]
This will almost certainly be fixed in 0.9 thanks to:

* https://github.com/rerun-io/rerun/issues/3156
* https://github.com/rerun-io/rerun/issues/3098
