### ISSUE TITLE
Optimize out unnecessary joins across autogenerated instance keys

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3107]
The store will auto-generate monotically increasing instance keys when they are not passed in by the user. This allows `re_query`'s join logic to "just work" no matter what but it also means that in most cases we're computing a costly join across 2 components of the same size, both with autogenerated instance keys, even though we already know the answer to that join.

**Comment by teh-cmc** [comment]
My proposed solution here would be to completely drop the notion of autogenerated instance keys altogether (which would fix a bunch of other issues).

When we get two components to join and none of them have keys, then we know we can blindly pair them.

**Comment by teh-cmc** [comment]
The solution proposed above induces _way_ too many cascading changes resulting from having to make cluster keys optional (internally), since everything has been built on the assumption that they should always be present (and rightly so).

A less invasive solution would be to indicate in the query results whether or not the returned instance keys were autogenerated (which we know since all autogenerated keys of a given length point to the same arrow buffer).

**Comment by emilk** [comment]
I think this is high-priority for 0.10, since we have introduces potential performance regressions in 0.9 because of it (https://github.com/rerun-io/rerun/pull/3363)
