### ISSUE TITLE
Add fade-in, fade-out to Welcome screen and simplify Welcome Screen vs. Loading logic

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3125]
Things that this issue covers:
- implement a fade-in/fade-out behaviour for the welcome screen
- see if that (and #3124) enable relaxing some of the constraint on the loading vs. welcome screen workflow
- ~~in particular, address the web demo workflow break introduced in #3116, where the welcome screen is no longer displayed after the recording is closed~~ (not sure what that was about, it works now)

**Comment by nikolausWest** [comment]
Done?

**Comment by abey79** [comment]
I added the fade-in/out idea to [#3244](https://github.com/rerun-io/rerun/issues/3244), so we can close this one.
