### ISSUE TITLE
Doc page: clicking link to examples breaks going back

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3146]
**Describe the annoyance**
Following the link to https://www.rerun.io/examples in https://www.rerun.io/docs, breaks going back to the previous page. I guess linking directly to https://www.rerun.io/examples/real-data would fix this.

**To Reproduce**
1. Go to https://www.rerun.io/docs 
2. Click on "example gallery"
3. Try to go back in your browser

**Expected behavior**
Go back to https://www.rerun.io/docs

**Additional context**
- Tested with Chrome and Firefox

**Comment by emilk** [comment]
That is annoying
