### ISSUE TITLE
Docs for TranslationAndMat3 incorrect

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3147]
**Describe the bug**
Two issues:
- "3x3 translation matrix", I guess this is a typo and should be changed to just "3x3 matrix" ?
- "*row-major* 3x3 matrix", is it really required to be row-major as in memory layout?

**Comment by emilk** [comment]
This is the old code - the new codegen'ed transforms have better docs. Not sure why the old `rerun_py/rerun_sdk/rerun/components/transform3d.py` is still in our code base though 🤔

**Comment by emilk** [comment]
* Will be fixed by https://github.com/rerun-io/rerun/issues/3236
