### ISSUE TITLE
Expanding streams view doesn't play nicely with other parts of the UI

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3152]
See video

https://github.com/rerun-io/rerun/assets/2624717/d48ade66-53aa-44cf-ae2f-a3737769e6f6

How to reproduce:
```bash
pip install --pre -f https://build.rerun.io/commit/d7de7f9/wheels --upgrade rerun-sdk.  # Latest build as of Aug 30th 09.20 CET
python -m rerun_demo
```

**Comment by abey79** [comment]
Tagging with 0.9 in case this is a quick fix.

**Comment by emilk** [comment]
Let's add a max size to it that leaves at least 25% or 200 pixels level on the screen, or something like that.

**Comment by nikolausWest** [comment]
> Let's add a max size to it that leaves at least 25% or 200 pixels level on the screen, or something like that.

If we can avoid a max size that would be nice. It's actually really useful to show just the streams view to explain what's going on in the underlying data model

**Comment by abey79** [comment]
Looking into it, it introduce some complexity in quite a few widgets. My proposal:

1) Implement @emilk's suggestion of enforcing a limit at 200px or something.
2) Build (or use if it exists already) a "snapping" resizing system for panel: resizing close to max height should "snap" to using the full height (ie. in that case we dont even draw the viewport/side panels/etc.). Likewise, it would be nice that resizing the time panel all the way down would "snap" to its collapsed state (which would have the added benefit of freeing the top-right button to actually _hide_ the timeline, which can't be done currently).

I'll open a PR for (1) and an issue for (2).
