### ISSUE TITLE
The hover previews on events in the Streams View flicker and block

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3154]
See video

https://github.com/rerun-io/rerun/assets/2624717/50c276c9-d783-4478-a2f8-a1b78ac56e0f

As you hover events in the streams view, the preview data UI flickers in and out and covers way too much of the UI. THe effect is quite jarring

How to reproduce:
```bash
pip install --pre -f https://build.rerun.io/commit/d7de7f9/wheels --upgrade rerun-sdk.  # Latest build as of Aug 30th 09.20 CET
python -m rerun_demo
```

**Comment by emilk** [comment]
Let's make sure we use `UiVerbosity::Reduced` for these, and if we are, make sure `UiVerbosity::Reduced` is smaller for this example

**Comment by nikolausWest** [comment]
> It will not fix the flickering though, which is due to the mouse moving over a bunch of datapoints which are all separated by 2-3 pixels. I'm leaning towards "works as intended".

Once the oversized tooltips are fixed, it might alleviate the problem. If it doesn't, we could consider waiting a little before showing the tooltip. At the same time that will affect the feeling of snappiness. Feels like @martenbjork kind of territory. Either way, happy to hold off on solving that for now if #3171 has a big enough effect

**Comment by abey79** [comment]
Sounds good. I'm not sure about the actual psychological impact, but #3171 definitely has reduced tooltip size rather drastically.

**Comment by martenbjork** [comment]
Shouldn't the tooltip work harder to get out of the way? Right now, it often covers the cursor, even though there is more space above the cursor where it could go. Here's my reference implementation: https://7e94j1.csb.app/ What do you think about this behavior?

<img width="841" alt="Desktop - 1" src="https://github.com/rerun-io/rerun/assets/875708/bf65f098-78c3-4cd2-aa61-c683a395ddd4">

**Comment by abey79** [comment]
I opened #3187 to cover the tooltip behaviour.
