### ISSUE TITLE
Large app.ron causes significant slowdown during shutdown

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3156]
**Describe the bug**
Rerun takes 2-3 seconds to shutdown at quit.

**To Reproduce**
Not clear how I got into this state, but the attached app.ron definitely creates the issue for me. This app.ron is currently about 7.2M
[app.ron.zip](https://github.com/rerun-io/rerun/files/12475575/app.ron.zip)

Update: you can reproduce the behavior by opening any view and then repeatedly clicking the "repopulate viewport" button. Seems proportional to the number of space-views created.
 - For `structure_from_motion/main.py` (3 space views) the file only grows at 500 bytes / repopulate.
 - For `open_photogrammetry_format/main.py --no-frames` (118 space views) the file grows at 10k bytes / repopulate.

**Expected behavior**
app.ron should stay a reasonable size and rerun should shutdown quickly.

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/3312232/0b59fba3-149e-475f-96db-64551fb80d92)

**Backtrace**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10

**Rerun version**
`main`

**Comment by emilk** [comment]
I'll add some GC:ing to the next egui release

**Comment by teh-cmc** [comment]
Tangent question: where are these `3.8s` going? It shouldn't take anywhere near that to write 7M of data to page cache? Is it the RON serializer?

**Comment by emilk** [comment]
Will be fixed by:
* https://github.com/emilk/egui/pull/3299
