### ISSUE TITLE
OPF example: big perf regression between `0.8.1` and tip on AMD

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3157]
`main`:
![image](https://github.com/rerun-io/rerun/assets/2910679/d43fbeac-7f79-4f64-bcb7-db8e645e4587)

`0.8.1`:
![image](https://github.com/rerun-io/rerun/assets/2910679/f89637ac-f7ce-46bb-b710-f6e573c795ed)

**Comment by jleibs** [comment]
Two more datapoints:

### Intel + Wayland
![image](https://github.com/rerun-io/rerun/assets/3312232/0414d8f8-af0f-4ea4-8735-53945199dc5f)
Something different (but also not good) going on here.

### Nvidia + XWayland
![image](https://github.com/rerun-io/rerun/assets/3312232/5f03f140-7632-4a23-8b2d-2b2e6a4cb998)

**Comment by teh-cmc** [comment]
The regression was introduced in https://github.com/rerun-io/rerun/commit/effb72ba15e9faaafcab2c4874e2b287f1e01d5f.

Just bisected into it, haven't looked at the underlying reason yet.

**Comment by teh-cmc** [comment]
I cannot reproduce the issue on my laptop: both the embedded intel GPU and the discrete nvidia card give about 55ms per frame.

My laptop has the exact same OS/software setup as my desktop so... I guess this is an AMD thing :unamused:

**Comment by emilk** [comment]
The regression diff should only touch CPU code; the GPU should see the exact same data and calls o.O - some weird timing thing?

**Comment by emilk** [comment]
For reference, on my MacBook Pro the performance has **improved** by a factor of **3x** from 0.8.2 to 0.9: https://github.com/rerun-io/rerun/issues/1136#issuecomment-1748716579

**Comment by teh-cmc** [comment]
Mesa :man_shrugging:
