### ISSUE TITLE
Audit python APIs and force kwargs where appropriate

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3167]
For APIs with long argument lists forcing the specification of kwargs can both help with code-clarity and future backwards compatibility.

We can do this by adding introducing * to the function arguments.

e.g.
```
def serve(
    *,
    open_browser: bool = True,
    web_port: int | None = None,
    ws_port: int | None = None,
    recording: RecordingStream | None = None,
) -> None:
```

**Comment by emilk** [comment]
There aren't many functions left; should be quick work!
