### ISSUE TITLE
Improve the behaviour of tooltips when the cursor is close to the window's borders

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3187]
It is extremely annoying when a tooltip covers the area over which the mouse pointer currently hovers, and this tends to happen very often in the timeline panel when close to the border of the windows:

https://github.com/rerun-io/rerun/assets/49431240/ab91a192-fa9e-46f0-9eb4-8acc969140ba

<br/>

If the tooltip doesn't fit bottom left of the mouse, it should jump top-right instead. See @martenbjork's comment [here](https://github.com/rerun-io/rerun/issues/3154#issuecomment-1702625924).

**Comment by emilk** [comment]
This was fixed in egui 0.28
