### ISSUE TITLE
Provide feedback while downloading a RRD

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3192]
There is currently no user feedback when downloading a RRD, e.g from the web via the new Example page of the Welcome Screen until at least one batch is completely read/downloaded/streamed. This is unfortunate as this state may last for a significant time for some RRD. Some feedback should be provided.

**Comment by abey79** [comment]
Gigantic Slack discussion thread here: https://rerunio.slack.com/archives/C03G1SP5Y87/p1693919261107909

**Comment by emilk** [comment]
We should show all in-progress receivers in the recordings view. That is: for each receiver without a associated connection, show the receiver source.
