### ISSUE TITLE
`app.rerun.io` should default to a blank viewer with the Welcome Screen

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3196]
Currently, `demo.rerun.io` redirects to something like `https://demo.rerun.io/version/0.8.1/examples/structure_from_motion/`. However, we now have the Welcome Screen along with an Examples page, so we should disable the redirect and default to an "empty" viewer.

**Comment by nikolausWest** [comment]
Actually, I think we'll be sunsetting demo.rerun.io so it's more important that this happens for app.rerun.io
