### ISSUE TITLE
Data view scroll area doesn't cover the whole container

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3228]
I've seen this one again and again, it's really jarring:
![image](https://github.com/rerun-io/rerun/assets/2910679/e24bf607-633e-449a-a7aa-952eb36e5d0f)

**Comment by emilk** [comment]
The fix should be to call https://docs.rs/egui/latest/egui/containers/scroll_area/struct.ScrollArea.html#method.auto_shrink
