### ISSUE TITLE
Speed up codegen

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3267]
`cargo codegen` takes around 6s to run. Most of it is running `black`. We could probably speed it up by running `black` only once, for all the generated code, instead of once for each generated file.

Probably same for `cargo fmt`

You can profile the codegen with `cargo codegen --profile`

**Comment by teh-cmc** [comment]
Related: `ruff`'s formatter has reached alpha and beta should follow soon:
- https://github.com/astral-sh/ruff/milestone/4
- https://github.com/astral-sh/ruff/milestone/5

**Comment by emilk** [comment]
I tried out `ruff format` in alpha, and it still has some problems, so we'll wait for beta.

`cargo fmt` is now the bottleneck. Running it once for each file is about as fast as running it once for a whole folder, so the same optimization as in #3368 won't work there.

Until we get `ruff format`, there is very little we can do right now to speed up codegen, except for generating less code

**Comment by emilk** [comment]
We're using `ruff format` since a few months, and it's great, but now `cargo fmt` is the bottleneck (by far). Hard to speed that up, except for generating less code.

**Comment by Wumpf** [comment]
I think we can close this then. We wanted to reduce the amount of generated code for a while but that's orthogonal to what we wrote here
