### ISSUE TITLE
Strongly-typed analytics events

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#3269]
Right now we construct events ad-hoc in code, and properties are mostly undocumented. We should instead just have a proper struct/enum with a single `into_event` method for each event.

We need to be careful about keeping these types clear of any extra noise that a non-Rust user would not be interested in. For example, no `derive` on the types if we can help it, and any `impl` blocks should be in a separate file.

**Comment by emilk** [comment]
Let's keep it simple:

```rs
trait AnalyticsEvent {
    NAME: &'static str,

    fn into_event(self) -> Event
}

// All the fields map 1-to-1 to the final fields

pub struct CrashPanicEvent {
    /// …
    pub callstack: String,

    /// …
    pub message: String,

    /// …
    pub file_line: String,
}

…
```

**Comment by jprochazk** [comment]
Some notes:

We have a lot of "global" properties that are appended to every event. Currently those are done ad-hoc via `register` calls on `ViewerAnalytics`, placing the properties in an untyped `HashMap<String, Property>`.
We'll move these into a `Context` struct, which will live in `ViewerAnalytics`.

Every property that is _not_ registered globally will be part of a specific event struct. We don't have many of these.
