### ISSUE TITLE
Update general documentation for new api

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3273]
Update all our general (non-sdk specific) documentation pages to use the new api:

### Getting Started
- [x] Python Quick Start: https://github.com/rerun-io/rerun/pull/3620
- [x] Rust Quick Start #3630
- [x] Logging Data in Python: https://github.com/rerun-io/rerun/pull/3620
- [x] Logging Data in Rust #3630

### How-To Guides
- [x] Using Rerun in Notebooks: https://github.com/rerun-io/rerun/pull/3667
- [x] using Rerun with ROS 2

### Concepts
- [x] Entities and Components: https://github.com/rerun-io/rerun/pull/3627
- [x] The Entity Path Hierarchy: https://github.com/rerun-io/rerun/pull/3627
- [x] Spaces and Transforms: https://github.com/rerun-io/rerun/pull/3627
- [x] Events and Timelines: https://github.com/rerun-io/rerun/pull/3627
- [x] Annotation Context: https://github.com/rerun-io/rerun/pull/3627

**Comment by nikolausWest** [comment]
Running notes that we can fill in while porting all examples etc: https://www.notion.so/rerunio/0-9-migration-notes-2b3debe9947f47a38428267b2da4cc1b?pvs=4

We'll then use those notes to create the migration guide

**Comment by emilk** [comment]
Blocked by
* https://github.com/rerun-io/rerun/issues/3236

**Comment by Wumpf** [comment]
there's a bunch of follow-up comments on the concepts
