### ISSUE TITLE
Write a migration guide for 0.8 -> 0.9

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3277]

**Comment by nikolausWest** [comment]
Running notes that we can fill in while porting all examples etc: https://www.notion.so/rerunio/0-9-migration-notes-2b3debe9947f47a38428267b2da4cc1b?pvs=4

We'll then use those notes to create the migration guide

**Comment by emilk** [comment]
@jleibs you have done some work on this but forgot to link the PRs to it 😬
