### ISSUE TITLE
TranslationAndMat3x3 defaults to zero matrix instead of identity

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3297]
**To Reproduce**
Compare
```
import numpy as np
import rerun as rr
import rerun.experimental as rr2
from rerun.experimental import dt as rrd

rr.init("depth_camera", spawn=True)
rr2.log(
    "world/rgbd_camera",
    rrd.TranslationAndMat3x3(matrix=np.eye(3)),
)
rr.log_pinhole("world/rgbd_camera", height=480, width=640, focal_length_px=500.0)
```
with and without the matrix argument.

**Expected behavior**
Default should be the identity.

**Screenshots**
With argument:
![Screenshot world - 4](https://github.com/rerun-io/rerun/assets/9785832/d4956389-b861-4e3e-a52e-45aaa4fe2157)
Without argument:
![Screenshot world - 3](https://github.com/rerun-io/rerun/assets/9785832/50570108-a6db-4bd0-a412-5a0765b8962e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.0 (5680fa18f 2023-08-23), LLVM 16.0.5] x86_64-unknown-linux-gnu 7db7b54, built 2023-09-12T08:50:21Z
```

**Comment by emilk** [comment]
Good catch!

**Comment by teh-cmc** [comment]
The matrix is optional and should serialize as `null` when left unspecified... so the issue is probably query-side and affect all SDKs?

**Comment by emilk** [comment]
Good point, and the cause of the problem is likely then the auto-derive of `Default` for `Mat3x3`. Sounds like a very easy fix then, but we should also check if we do the same bad auto-derive for other types (e.g. quaternions)
