### ISSUE TITLE
Improve handling of archetype queries at timepoints before the archetype is logged

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3320]
Currently when we query an archetype at a time before the archetype has been logged, we end up getting a `PrimaryNotFound` error.  This means that every view-part-system does something like:
```
        match query_archetype_with_history::<A, N>(...) {
            Ok(_) | Err(QueryError::PrimaryNotFound(_)) => {}
            Err(err) => {
                re_log::error_once!("Unexpected error querying {ent_path:?}: {err}");
            }
        }
```

New systems sometimes forget to do this, leading to spurious warning pop-ups.

If the component *exists* but not at that time we should indicate this condition by returning an empty list rather than a None.

**Comment by teh-cmc** [comment]
Closed by mistake because a PR mentioned the word "resolve" and this issue number in the same sentence :joy:
