### ISSUE TITLE
Decide if we want a `Archetype::with_singular_component` in C++ and Rust

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3330]
Singular is inconsistent with how we roll in Rust and Python.
Passing several custom arguments could be done better with a variadic template, so we go from
```
.with_labels({"red", "green", "blue"})
```
to 
```
.with_labels("red", "green", "blue")
```

should still support passing in vectors though! This part is related to #3050

**Comment by emilk** [comment]
I think it is important that we still support passing in a `std::vector` of labels (or ideally any container compatible with `std::begin/std::end`), and I'm not sure variadic templates is compatible with this.

I don't think it is inherently bad to distinguish between singular and plural. `Points3D(…).with_color(0xff00ff)` reads pretty good to me in both C++ and Rust.

**Comment by Wumpf** [comment]
Settled by #3791: ComponentBatches can be created from single and multiple components and the way this is designed it now doesn't really make sense to have singualr versions
