### ISSUE TITLE
Memory leak on web build, leads to crash eventually

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3335]
browser tab left open for long enough
![image](https://github.com/rerun-io/rerun/assets/1220815/dccf6fe0-06f0-40fc-bcb6-f88120a0c1ed)

Memory leak may affect all platforms, but on the web run out of memory

**Comment by nikolausWest** [comment]
Still, I haven't been able to reproduce going to chrome://discards/ and discarding the tab

**Comment by Wumpf** [comment]
we don't have a good repro of this, closing until it shows up again
