### ISSUE TITLE
Rust Objectron example improperly logging some data as timeful

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3338]
timeless data is supposed to be independent of active timelines

![image](https://github.com/rerun-io/rerun/assets/1220815/b5f57b70-6c88-45fe-93fe-77c377ffb57b)
![image](https://github.com/rerun-io/rerun/assets/1220815/ce9230fb-c4be-4fd3-8532-a4ec868a03b9)

**Comment by teh-cmc** [comment]
That's just the Rust objectron example not logging the data as timeless.
