### ISSUE TITLE
`Asset3D` mesh migration to archetypes

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3354]
Turn into sub-issues as needed.

- [ ] Python support
  - [ ] Extensions
  - [ ] Unit test (constructors, serialization)
  - [ ] Doc example
- [ ] Rust support
  - [ ] Extensions
  - [ ] Unit test (constructors, rust-to-rust roundtrip)
  - [ ] Doc example
- [ ] C++ support
  - [ ] Extensions
  - [ ] Unit test (constructors, serialization)
  - [ ] Doc example
- [ ] Cross-language roundtrip test
- [ ] Remove old components
  - [ ] Clean up `re_components`
  - [ ] Port viewer to use new types and queries

**Comment by emilk** [comment]
This can use the same `MediaType` component that we use for `TextDocument`
