### ISSUE TITLE
Port all examples to new codegen API

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3382]
Required Fixes:
- Initial Mitigation for https://github.com/rerun-io/rerun/issues/3552:
  - [x] https://github.com/rerun-io/rerun/pull/3611
- [x] https://github.com/rerun-io/rerun/issues/3551
- [x] https://github.com/rerun-io/rerun/issues/3584
- [x] Apply changes corresponding to: https://github.com/rerun-io/rerun/pull/3560
  - [x] e.g. https://github.com/rerun-io/rerun/pull/3545/files#r1341454165
- [x] https://github.com/rerun-io/rerun/issues/3585
- [x] https://github.com/rerun-io/rerun/issues/3586
- [x] https://github.com/rerun-io/rerun/issues/3553
- [x] https://github.com/rerun-io/rerun/issues/3587
- [x] https://github.com/rerun-io/rerun/issues/3555

Python
- [x] arkit_scenes
- [x] blueprint
- [x] car
- [x] clock
- [x] depth_guided_stable_diffusion
- [x] detect_and_track_objects
- [x] dicom_mri
- [x] dna
- [x] face_tracking
- [x] human_pose_tracking
- [x] live_camera_edge_detection
- [x] live_depth_sensor
- [x] minimal
- [x] minimal_options
- [x] multiprocessing
- [x] multithreading
- [x] notebook
- [x] objectron
- [x] open_photogrammetry_format
- [x] plots
- [x] raw_mesh
- [x] rgbd
- [x] ros_node
- [x] segment_anything_model
- [x] signed_distance_fields
- [x] structure_from_motion
- [x] text_logging

Rust
- [x] clock
- [x] custom_space_view
- [x] dna
- [x] extend_viewer_ui
- [x] minimal
- [x] minimal_options
- [x] minimal_serve
- [x] objectron
- [x] raw_mesh

External
- [x] https://github.com/rerun-io/differentiable-blocksworld (https://github.com/rerun-io/differentiable-blocksworld/pull/2)
- [x] https://github.com/rerun-io/tapnet (https://github.com/rerun-io/tapnet/pull/2)
- [x] https://github.com/rerun-io/slahmr (https://github.com/rerun-io/slahmr/pull/2)
- [x] https://github.com/rerun-io/MCC (https://github.com/rerun-io/MCC/pull/2)
- [x] https://github.com/rerun-io/limap (https://github.com/rerun-io/limap/pull/2)
- [x] https://github.com/rerun-io/cross_attention_renderer (https://github.com/rerun-io/cross_attention_renderer/pull/3)
- [x] https://github.com/rerun-io/grounding-sam (https://github.com/rerun-io/grounding-sam/pull/8)
- [x] https://github.com/rerun-io/point-shap-e (https://github.com/rerun-io/point-shap-e/pull/2)
- [x] https://github.com/rerun-io/simplerecon (https://github.com/rerun-io/simplerecon/pull/2)

**Comment by nikolausWest** [comment]
Running notes that we can fill in while porting all examples etc: https://www.notion.so/rerunio/0-9-migration-notes-2b3debe9947f47a38428267b2da4cc1b?pvs=4

We'll then use those notes to create the migration guide
