### ISSUE TITLE
Hovering the barchart legend causes the chart to disappear

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3399]
**Describe the bug**
When moving the mouse over the legend, the chart disappears.

**To Reproduce**
Go to: https://demo.rerun.io/version/0.8.2/examples/plots/
Move mouse over the legend that dsays "bar chart"

**Expected behavior**
The chart shouldn't disappear. Maybe it should even become more visible rather than less visible.

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/3312232/4908028d-19fc-46c3-8946-cf996a764508)
![image](https://github.com/rerun-io/rerun/assets/3312232/56cee9aa-2eb7-44d6-89bb-4b19567e1ede)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 
**Rerun version**
0.8.2 and main.

**Comment by emilk** [comment]
Probably something to fix in `egui_plot`

**Comment by emilk** [comment]
Will be fixed when we update to egui with:
* https://github.com/emilk/egui/pull/3387
