### ISSUE TITLE
Force users to spell out the components in archetype constructors

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3402]
Currently this is valid code:

```py
rr.log("base", rr.Arrows3D([0, 1, 0]))
```

As a user I would find this profoundly confusing. What are these three numbers - are they the base of the arrow, or its tip? (answer: neither!).

This would be much better if the user was forced to write out `rr.log("base", rr.Arrows3D(vector=[0, 1, 0]))`.
(In this case, I would also vote for making `origin` mandatory).

Furthermore, I think in all our examples we should include the origin for our arrows.

The same would go for Rust and C++ - `Arrows3D::from_vector(…).with_origin(…)`.

**Comment by nikolausWest** [comment]
I think forcing named arguments here is fine but I don't think we should make origin mandatory.

**Comment by teh-cmc** [comment]
Agreed with @nikolausWest.

Making `origin` mandatory would also introduce the concept of archetypes with multiple required components which we're really not ready to deal with for 0.9.
