### ISSUE TITLE
Improve on `ArchetypeView::iter_raw_optional_component`

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3415]
See https://github.com/rerun-io/rerun/pull/3395#discussion_r1333929330:
> Asking for an iterator to all components, and then just taking the first seems like a bad idea to me. If there are multiple blobs the other ones will just silently be ignored.
> 
> Better to write helper functions `arch_view.required_mono_component::<Blob>()` and `arch_view.optional_mono_component::<MediaType>()` or similar. It will better state the intent here (more readable code), and will give us an opportunity to log a warning if there are more than one component.

**Comment by emilk** [comment]
In general it would be very useful to have a special `trait` for mono-components so that we can make our simplify code around it, and protect against misuse.

See also:
* [#3168](https://github.com/rerun-io/rerun/issues/3168)
