### ISSUE TITLE
World up-axis not respected under various conditions

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3420]
**Describe the bug**
It seems like after setting the up-axis using view coordinates the Rerun viewer has to be restarted or double clicked into empty space to reset the 3D view.

This seems to be the case when:
- rotating the camera around its principal axes (i.e., middle-mouse rotate)
- switching between recordings with different up-axis
- logging again, but with different up-axis

**To Reproduce**
```python
import numpy as np
import rerun as rr
import rerun.experimental as rr2

rr.init("Up-axis Test", spawn=True)
rr2.log("world", rr2.ViewCoordinates.RUB, timeless=True)
rr2.log(
    "world/points",
    rr2.Points3D(np.random.rand(100, 3))
)
```
Run this twice and replace RUB with RDF. The second recording will say up is -Y, but the view shows +Y as the up-axis still.

**Expected behavior**
3D view should always respect the set up-axis.

After camera rotation it's a bit less obvious what should happen. But still rotating around the up-axis seems better then whatever it rotates around right now (?). Generally, the rotation when no up-axis has been set feels unintuitive, but that's a separate issue.

**Desktop (please complete the following information):**
 - OS Ubuntu 20.04
 
**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

**Comment by roym899** [comment]
I think once I figured out that it's fixed by double clicking it's less of an issue.

**Comment by emilk** [comment]
Very related:
* https://github.com/rerun-io/rerun/issues/3539
