### ISSUE TITLE
No way to adjust Recordings / Blueprint size in left-hand panel

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3421]
**Describe the annoyance**
There's no way to adjust how much space Recordings and Blueprint take on the left hand side. I think when having a lot of entities, it might often be desirable to have the Blueprint section take more space than it currently does. 

I think one would expect to have a resize option popping up when hovering over the top of Blueprint as in this video

https://github.com/rerun-io/rerun/assets/9785832/8a5051c9-9f38-4da7-baf8-ca597309558b

```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

**Comment by emilk** [comment]
The video isn't working for me

**Comment by roym899** [comment]
Hm, I reencoded it with `yuv420p` pixel format. Not sure if that was the problem though.

**Comment by emilk** [comment]
That works now - thanks!

**Comment by emilk** [comment]
I think I need to add something like a `SplitPanel` to egui for this
