### ISSUE TITLE
`**kwargs` in constructors makes archetype creation more difficult

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3423]
**Describe the annoyance**
When constructors of archetypes take `**kwargs` it becomes harder to create an archetype. It becomes unclear what arguments are supported. For example, `class_ids`, `colors`, etc. are not visible for `Boxes2D`, and `Boxes3D`.

![kwargs](https://github.com/rerun-io/rerun/assets/9785832/1acda9f3-a0d7-4ffc-9d8b-d5c133315191)

**Expected behavior**
Show all arguments.

**Your goals**
Ideally understand how to use the archetype from just looking at the signature.

**Comment by nikolausWest** [comment]
Let's not use **kwargs in any of our init methods

**Comment by nikolausWest** [comment]
Related: 
- https://github.com/rerun-io/rerun/issues/3433
