### ISSUE TITLE
`SegmentationImage` gets immediately cleared by clearing at later time step

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3424]
**Describe the bug**
It looks like a previously logged `SegmentationImage` gets cleared by a `rr2.Clear` at a later time. Only observed for `SegmentationImage` so far. 

**To Reproduce**
```python
import rerun as rr
import numpy as np

rr.init("test clear", spawn=True)
rr.set_time_sequence("frame", 0)
rr.log_image("image", np.random.rand(100,100,3) * 0.2)
rr.log_segmentation_image("image/segmentation", np.random.randint(0,10, size=(100,100)))
rr.set_time_sequence("frame", 10)
rr.log_cleared("image/segmentation")
```
This works fine in 0.8.2, but not in the prerelease. Same with the new API.

**Expected behavior**
Segmentation image should disappear at frame 10, not at frame 0.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 2e9df4c, built 2023-09-23T09:59:35Z
```

**Comment by teh-cmc** [comment]
I'm actually reproducing the same issue on both `0.8.2` and `0.9-alpha` :thinking:
