### ISSUE TITLE
Add `Image.from_file(image_path)`

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3431]
For:
* [ ] Python: https://github.com/rerun-io/rerun/pull/3481
* [ ] ~~Rust~~ will punt on this until: https://github.com/rerun-io/rerun/issues/3494

**Comment by emilk** [comment]
Let's do whats fastest for us to write, probably using PIL

**Comment by jleibs** [comment]
Note: rust already has comparable helpers on `TensorData`. Unclear we need an alternative helper for rust until we introduce the proper archetype version.
