### ISSUE TITLE
Unify how we import datatypes, components, archetypes

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3435]
We currently have e.g. `from rerun.experimental import dt as rrd` in some examples/docs.

We should not do this, instead either do:

* `from rerun.datatypes import Utf8` or write out the full `rr.datatypes.Utf8` in the code
* `from rerun.components import Text` or write out the full `rr.components.Text` in the code
* `from rerun import Archetype` or write out the full `rr.Archetype` in the code

**Comment by jleibs** [comment]
Done as part of: https://github.com/rerun-io/rerun/pull/3470
