### ISSUE TITLE
Bad default layout for structure_from_motion example

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3455]
This is what the [webviewer](https://demo.rerun.io/pr/3451/examples/structure_from_motion/) looks like for me

![image](https://github.com/rerun-io/rerun/assets/1220815/e8a4710b-3963-49b5-aceb-7041456eec9a)

The newly added markdown doesn't place itself in the grid as expected

**Comment by emilk** [comment]
This is only for wide screens. It is in a grid, but egui_tiles suggests a 3x2 grid instead of a 2x2, because 2x2 would create extreme wide-screen views
