### ISSUE TITLE
Add a `--check` argument to `cargo codegen`

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3495]
This should do a dry-run and return an error code if any of the files would be modified.

This would be a bit clearer and less error prone in the CI check:
https://github.com/rerun-io/rerun/blob/50222c2349cfaec64f795636d2398d26e6bf4738/.github/workflows/reusable_checks.yml#L138-L140

And would also be something that could be added to a git `pre-push` hook to reduce frequency of submitting code that's going to fail the codegen check.

**Comment by emilk** [comment]
The various codegens should not write to the filesystem directly, but instead return a `BTreeMap<Path, String>` of filed it wants to write. This will then be trivial to implement. It will also make the codegen a lot nicer.
