### ISSUE TITLE
No helper enum for MediaType in Python

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3502]
When using the `rr.TextDocument` archetype to log markdown text in python, it would be useful with a helper enum (in the global namespace) to set the correct mediatype. Rust users have `MediaType::markdown()` but Python users currently need to know to use `mediatype="text/markdown"`. Even writing this issue I had to double check the doc example several times because I forgot what the string was exactly.

**Comment by teh-cmc** [comment]
They're there https://github.com/rerun-io/rerun/blob/main/rerun_py/rerun_sdk/rerun/components/media_type_ext.py#L10-L68 :thinking:

**Comment by nikolausWest** [comment]
> They're there https://github.com/rerun-io/rerun/blob/main/rerun_py/rerun_sdk/rerun/components/media_type_ext.py#L10-L68 🤔

It doesn't show up in global namespace:
![Screenshot 2023-09-28 at 10 21 25](https://github.com/rerun-io/rerun/assets/2624717/da35d9de-3143-428c-9c08-87f6e531b535)

**Comment by nikolausWest** [comment]
Related, I also can't do `rr.components.MediaType`. I think we need to import the `components` module into the global scope as well
