### ISSUE TITLE
Make sure archetype docs are thorough and correct

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3504]
After landing
- https://github.com/rerun-io/rerun/issues/2775
- https://github.com/rerun-io/rerun/issues/3437

Take another pass over all archetype pages and make sure:
- Text is correct and descriptive
- We use the correct "pluralness" (Arrow3D vs Arrows3D) everywhere (title, and in text) 
- We link to the correct Python docs (Arrows3D instead of log_arrow)
- Includes at least one code example
- Each code example has a screenshot

**Comment by Wumpf** [comment]
* Related to #3540

**Comment by emilk** [comment]
Make sure each `Ext` class links back to the original with doclinks, i.e:

```py
class Boxes3DExt:
    """Extension methods for [Boxes3D][rerun.archetypes.Boxes3D]."""
```

**Comment by emilk** [comment]
Clean up the CSS for images for the Python API docs
