### ISSUE TITLE
`rr.Clear.flat()` not showing in autocomplete

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3526]
**Describe the annoyance**
`rr.Clear.flat()` doesn't seem to be picked up by the language server. `rr.Clear.recursive()` does.

**Additional context**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 29ab0e3, built 2023-09-28T17:19:31Z
```

**Comment by Wumpf** [comment]
I get neither picked up, only the `recursive` *field* shows up. Maybe that's what you saw?

The problem is presumably that we add recursive & flat like so:
```
    @staticmethod
    def deferred_patch_class(cls: Any) -> None:
        def flat() -> cls:
            return cls(recursive=False)

        def recursive() -> cls:
            return cls(recursive=True)

        cls.flat = flat
        cls.recursive = recursive
```

**Comment by roym899** [comment]
Yeah, you're right, neither shows up as a function.
