### ISSUE TITLE
Viewer hangs upon rearranging tiles into view with tabs

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3527]
**Describe the bug**
The viewer hangs and does not recover when adding a tile at the bottom half of a view that currently has tabs (see video below).

**Video**

https://github.com/rerun-io/rerun/assets/9785832/5c1bc8fc-47b1-4f9e-82f9-f349807e055d

Crash happens when releasing the tile, since that might not be clear from the video.

**To Reproduce**
```python
import rerun as rr
import numpy as np

rr.init("Test", spawn=True)

rr.log("img1", rr.Image(np.random.rand(100,100,3)))
rr.log("img2", rr.Image(np.random.rand(100,100,3)))
rr.log("img3", rr.Image(np.random.rand(100,100,3)))
rr.log("img4", rr.Image(np.random.rand(100,100,3)))
```
Put two of these images as tabs into the same tile. Then move one of the other images into the same tile, splitting the tab view either horizontally or vertically. The side seems to matter, so if it doesn't crash immediately, maybe try on the other side of the tab view.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.9.0-alpha.4 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 29ab0e3, built 2023-09-28T17:19:31Z
```

**Comment by nikolausWest** [comment]
Do you get any useful logs if you start the viewer with `RUST_LOG=debug rerun` ?

**Comment by roym899** [comment]
Nope, no output at all when it hangs.

**Comment by nikolausWest** [comment]
Could you share the rrd file?

**Comment by emilk** [comment]
I can reproduce

**Comment by emilk** [comment]
Found it
