### ISSUE TITLE
Make sure Python docstrings indicate if something is an archetype, component, or datatype

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3540]
To mitigate the risk for confusion about what you're logging, we should make sure that the docstrings for both classes and their init methods indicate if they are archetypes, components, or datatypes. Components that implement automatic upcasting to add an indicator, that should be indicated as well.

**Comment by emilk** [comment]
I think this is good advice for all three languages, i.e. we should make sure the first line in the docstring in the `.fbs` mentions it, or is automatically prefixed with `Archetype: ` etc by the actual codegen
