### ISSUE TITLE
Hover previews can easily become too cluttered

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3573]
Hovering over data in a space view can easily become quite cluttered (see screenshot and video). 
<img width="579" alt="Screenshot 2023-10-01 at 21 45 48" src="https://github.com/rerun-io/rerun/assets/2624717/de152142-564f-4b98-9d2d-1a4349bd349b">

https://github.com/rerun-io/rerun/assets/2624717/33d06906-651a-4832-a9df-86d6c166fd3d

We should therefore 
- #3548 Hide indicator components as they aren't really the data you are interested in inspecting in a view.
- Not show PinholeProjection, Resolution, or AnnotationContext when hovering an image
    - Is there anything else?
- Make sure the hover preview doesn't cover the part of the view where you're currently hovering.
    - If fixing this isn't achievable quickly, that should be broken out to a separate issue and handled in a later cycle

**Comment by nikolausWest** [comment]
I also wonder about "hover position" for 3D points when hover in 2D. I think we should remove it but I may be wrong. I definitely don't understand it.

**Comment by Wumpf** [comment]
Afaik showing the position was a user request:
* #3226
Also not happy with what it looks like though in the ui. There's some more notes on the topic here
* #2843

**Comment by nikolausWest** [comment]
> Also not happy with what it looks like though in the ui. There's some more notes on the topic here

In my opinion the current implementation makes things worse more than better. It's not worth the added clutter when it's hard to understand
