### ISSUE TITLE
`DisconnectedSpace` requires a parameter

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3599]
There is currently a required boolean for disconnect space such that we have to log;
```
rr.DisconnectedSpace(True)
```

At a minimum we should provide a default value of True here but it's also unclear whether logging:
```
rr.DisconnectedSpace(False)
```
has the expected behavior.

**Comment by emilk** [comment]
I'll make it optional for 0.9.1, and then we can remove it in 0.10
