### ISSUE TITLE
UI handling for "user.components." prefix

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3606]
When deprecating `ext=` and introducing `rr.AnyValues` we started using the prefix "user.components.<name>"

This is a little bit on the verbose side. We should either pick a different prefix or special-case it in the UI.  Would be nice to do something like highlight it in a different color, etc.

**Comment by nikolausWest** [comment]
I think we should go with something much shorter, like for instance `any.`

**Comment by emilk** [comment]
It is currently `any.values.MyComponent`

**Comment by emilk** [comment]
`AnyBatchValue` docs still says:

> The component will be named "user.components.<NAME>".

**Comment by emilk** [comment]
Alternative naming suggestions for `AnyValues`:
* `Custom`
* `Dynamic`

**Comment by jleibs** [comment]
Decided to simply drop the prefix for now.

https://github.com/rerun-io/rerun/issues/3661 may force us to change the way this works in the future.
