### ISSUE TITLE
After release, replace Python reference links from `HEAD` to `latest`

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3624]
We currently must use links to the HEAD in order to avoid missing links:

`https://ref.rerun.io/docs/python/HEAD/common/spatial_primitives/#rerun.Points3D`

Once 0.9 is out, we should update the docs to link to `latest` instead.

**Comment by teh-cmc** [comment]
Done?

**Comment by emilk** [comment]
Yes, this is done
