### ISSUE TITLE
isort considers rerun first party in examples dir

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3636]
**Describe the annoyance**
When I run isort from the root dir, it will consider `rerun` first party (because the working dir is called rerun) and move the imports around.

What fixed it was to either
- rename the repo to sth other than rerun, or
- add an `examples/.isort.cfg` that contains  
```cfg
[settings]
profile=black
known_third_party=rerun
```

**Comment by abey79** [comment]
Does that apply to `ruff`'s implementation of `isort`?

**Comment by abey79** [comment]
Good question. I think the answer is no: https://github.com/rerun-io/rerun/pull/3765
