### ISSUE TITLE
Python API docs: Add a way to link to the `latest` release

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3647]
If you go to https://ref.rerun.io/docs/python/ you can select a version from a drop-down.

Currently at the top is `0.8.2`. At the bottom you'll find:

![Image](https://github.com/rerun-io/rerun/assets/1148717/c709bed4-4546-4243-8469-03c0f79111f7)

What is `test`?

What is `prerelease`? Is this the weekly alpha?

Is `HEAD` an idiomatic name in Python documentation? Can we call it `nightly` instead?

I would like it if we had `0.9.0-alpha.6` in that list. Maybe not _all_ alphas, just the _latest_ alpha, spelled out explicitly.

**Most importantly**: it lacks a `latest`, i.e. latest actual release. We need this in order to link to the latest docs of a specific item, e.g. <https://ref.rerun.io/docs/python/latest/package/rerun/archetypes/line_strips2d/>

**Comment by jprochazk** [comment]
Note that [`latest`](https://ref.rerun.io/docs/python/latest) exists, just that link doesn't work because `latest` points to `0.8.2` right now.

**Comment by abey79** [comment]
> Is HEAD an idiomatic name in Python documentation? Can we call it nightly instead?

Most python docs are hosted on readthedocs.io, and the idiomatic name there is `latest` = `main`, and the version selector usually defaults to the latest released version. There usually isn't a handle for the "latest release".

**Comment by jprochazk** [comment]
> What is test?

That's from when someone manually dispatched the docs release job, can safely be deleted

> What is prerelease? Is this the weekly alpha?

That's the latest alpha, like the one we just released. I'll change it to be called just `latest alpha`. I guess there's no need for that if we have the latest alpha version on that list.

**Comment by emilk** [comment]
Let's go with

* `nightly` - nightly, or every commit to main
* `stable` - actual "real" release
* `dev` - latest `alpha` or `rc`

**Comment by jprochazk** [comment]
This is done, just missing final cleanup of the old versions in the dropdown. We'll do that after the 0.9 release.
