### ISSUE TITLE
Bad heuristic results in adding inappropriate segmentation to 3D scenes

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3677]
Repro:
```
"""Log a pinhole and a random image."""
import numpy as np
import rerun as rr

rr.init("rerun_example_pinhole", spawn=True)
rng = np.random.default_rng(12345)

image = rng.uniform(0, 255, size=[3, 3, 3])
rr.log("world/camera/image", rr.Pinhole(focal_length=3, width=3, height=3))
rr.log("world/camera/image", rr.Image(image))

image = rng.uniform(0, 255, size=[3, 3, 1])
rr.log("seg", rr.SegmentationImage(image))
```

![image](https://github.com/rerun-io/rerun/assets/3312232/ff83f67a-dff4-4912-a2f4-1f592e2c33c3)

Note this *only* happens with `rr.SegmentationImage` but not with `rr.Image` so there's probably some place we need to do a more complete check.

**Comment by emilk** [comment]
so `seg` and `world/camera/image` are added to the same spaceview, despite them not having a common ancestor O.o that's really strange

**Comment by Wumpf** [comment]
that part isn't _that_ strange since as of 0.8 (or was it 0.7 already?) we sometimes spawn a single space view at the root
