### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3699]
Python 3.12.0 was recently released (Oct, 2nd) and we should support it.

This is currently blocked by `pyarrow` 3.12 wheel availability:
* https://github.com/apache/arrow/issues/37880

**Comment by emilk** [comment]
Still waiting for pyarrow 14 to show up on pypi

**Comment by abey79** [comment]
PyArrow 14 is up :tada:

But still soft-blocked on https://github.com/pytorch/pytorch/issues/110436 (we use it in our test suite).

**Comment by jleibs** [comment]
Our conda build will need to wait for:
 - https://github.com/conda-forge/arrow-cpp-feedstock/pull/1201

**Comment by h-vetinari** [comment]
FYI, in conda-forge, we support python 3.12 on pyarrow 13.x [since](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1181) more than a month already.
