### ISSUE TITLE
egui `Table` features required for Rerun viewer

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#370]
Just a meta issue to keep track of our needs `Table`-wise. Modify/add/comment at will.

Not intended to be a fully detailed spec for each and every thing that we need, just enough information to understand each feature unambiguously.

_Roughly in decreasing order of importance_.

---

- [x] Support for horizontal scrolling

`Table` should either be embeddable within an horizontal `ScrollArea` or (more likely) natively support horizontal scrolling (as it does for vertical scrolling).
While one can technically wrap a `Table` in a `ScrollArea` today, it leads to all kinds of serious clipping issues (text being clipped inappropriately, widgets disappearing...) and other layout bugs.

_Needed pretty much everywhere._

- [x] Automatic optimal sizing for columns

One should be able to specify an automatic column size when instantiating a `Table`, e.g.:
```rust
Table::new().column(Size::Optimal).column(...).show(...);
```

_Needed by text view, annotation contexts, and probably many more._

- [ ] Ability to show/hide columns from the UI

E.g. right clicking on the table pops up a ComboBox with checkboxes for each column.

- [x] Reset column size from UI

We should be able to reset a `Table`'s columns to their original size (which might be a fixed or an optimal size) from the UI (just a matter of clearing the internal resize state).

_Needed pretty much anywhere we have resizable tables._

- [x] Ability to scroll to a given row

One should be able to easily scroll to a given row number, and specify where the row should then be positioned (at the top? centered? at the bottom?).
Today it is only possible to scroll a specific amount of points, which is very cumbersome and very leaky.

```rust
enum ScrollTarget {
    Top,
    Center,
    Bottom,
}
Table::new().column(...).column(...).start_row(42, ScrollTarget::Top).show(...);
```

_Needed by text logs._

- [x] Ability to scroll past the end

Consider e.g.:
```rust
Table::new().column(...).column(...).start_row(LAST_ROW, ScrollTarget::Top).show(...);
```
which is something you want to do e.g. anytime you need to align the text logs to a given timestamp.

_Needed by text logs._

- [ ] Ability to swap columns from the UI

Being able to show/hide columns is often not enough / too constraining: need to be able to re-order columns by dragging them around.

- [ ] Ability to click on column to sort the table from the UI

Multiple clicks to toggle between ascending/descending order.

---

See also #341

**Comment by abey79** [comment]
More advanced features may include:
- tree table (aka first column is actually a hierarchical, collapsible list, like the streams view)
- hierarchical, multi-header-row:
```text
    ┌─────────────────┬──────────────────────────┬────────┐
    │    entity 1     │         entity 2         │entity 3│
    ├────────┬────────┼────────┬────────┬────────┼────────┤
    │ comp A │ comp B │ comp A │ comp B │ comp C │ comp C │
┌───┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 0 │        │        │        │        │        │        │
├───┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 1 │        │        │        │        │        │        │
├───┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 2 │        │        │        │        │        │        │
├───┼────────┼────────┼────────┼────────┼────────┼────────┤
│ 3 │        │        │        │        │        │        │
└───┴────────┴────────┴────────┴────────┴────────┴────────┘
```
- cell merging, e.g. to display splats

**Comment by emilk** [comment]
We've broken this up into smaller issues now
