### ISSUE TITLE
Drag & Drop of obj models doesn't work

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3703]
Try some obj file from here https://casual-effects.com/data/

Web:
![image](https://github.com/rerun-io/rerun/assets/1220815/ec65a621-8814-4334-8340-395f73f379a1)

Native (windows - notice also slash escaping issue #3697)
![image](https://github.com/rerun-io/rerun/assets/1220815/08320de2-8aec-4367-af60-bb5310256695)

**Comment by teh-cmc** [comment]
I imagine that's because this path is trying to guess from the data rather than the path, which isn't really possible with `.obj`... I'll have a quick look.
