### ISSUE TITLE
`log_line_strips_3d` with no `stroke_widths` argument shows no lines

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3711]
**To Reproduce**
```
import rerun as rr

rr.init("rerun_example_line_strip3d", spawn=True)

points = [
    [0, 0, 0],
    [0, 0, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1],
    [0, 1, 0],
    [0, 1, 1],
]

rr.log_line_strips_3d("strip", [points])
```

**Expected behavior**
Line strip shows up with the default width.

**Additional Info**
It looks two issues:
1. We end up logging an empty list for the radii (though not for any of the other components)
2. This empty list causes things to fail rather than being treated as "use the default radii"

**Comment by teh-cmc** [comment]
- Fixed in #3720
