### ISSUE TITLE
Image plane immediately shrinks to too small of a value for pinhole cameras.

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3728]
**Describe the bug**
When creating a scene with a pinhole, the image plane starts off large, which sets the accumulated bounds, and then immediately shrinks to a small value.

**To Reproduce**
```
python docs/code-examples/pinhole_simple.py
```

**Expected behavior**
Image plane should be set to a reasonable value.

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/3312232/9424c3f8-d8e8-41eb-890d-7958277ae7a8)

**Rerun version**
0.9

**Comment by emilk** [comment]
The scene bounding box should ignore the pinhole frustum imho

**Comment by jleibs** [comment]
> The scene bounding box should ignore the pinhole frustum imho

Good news: this seems to be the case.
Bad news: I have no idea what is causing the interaction.
