### ISSUE TITLE
Pre-push git hook that checks for typos and runs `lint.py`

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3738]
Motivation: save us from waiting until CI notices common problems
Requirements: Must run in at most 2-3 seconds

I think spell checking and most of `lint.py` makes sense. Maybe `lint.py` needs a `--fast`flag to skip some of its slower checks (if we know what those are).

**Comment by abey79** [comment]
`ruff` is a good candidate too for a pre-commit hook.

**Comment by emilk** [comment]
Let's add something like `just fast-lint` that the pre-push hook calls.

**Comment by abey79** [comment]
https://pre-commit.com or something else?

**Comment by emilk** [comment]
I don't think there's no need for any new dependencies. `scripts/setup_dev.sh` should just make sure there is a call to `just fast-lint` inside `.git/hooks/pre-push.sample`
