### ISSUE TITLE
Need a way to reset the accumualted bounding box without resetting the scene

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3750]
Many situations can cause the accumulated bounding box to be too large, in particular having the wrong entities in the scene. Once we remove these items, the accumulated bounding box should shrink correspondingly. 

I would propose simply resetting the accumulated bounding box any time we remove an entity from the scene.

**Comment by jleibs** [comment]
Related to giving users a better way to recover from problems such as: https://github.com/rerun-io/rerun/issues/3485

**Comment by teh-cmc** [comment]
Similarly -- reducing the size of the image plane doesn't seem to shrink the bounding box either.

**Comment by emilk** [comment]
> Similarly -- reducing the size of the image plane doesn't seem to shrink the bounding box either.

We should fix it so that the pinhole frustum image plane does not affect the bounding box at all (see other issues).

**Comment by emilk** [comment]
Double-clicking to reset the camera should also reset the bounding box
