### ISSUE TITLE
Add C++ example with logging data from Eigen/OpenCV

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3758]
this encompasses to explore what we need to make it
* easy
* zero-copy ('ish)

This is a moving target and we'll have to decide how far to go in the first iteration, but there should be _some_ sample demonstrating Eigen use.

**Comment by emilk** [comment]
Current work: https://github.com/rerun-io/cpp-example-opencv-eigen

**Comment by emilk** [comment]
Let's link to it from:
* C++ getting started guide
* `rerun_cpp/README.md`
* `rerun.hpp`

**Comment by emilk** [comment]
Also add an image to the main README.md of the repository
