### ISSUE TITLE
Fix release workflows

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#3776]
0.9 introduces a lot of small to medium issues that should be fixed before the next release

- [x] rerun-io redeploy failed (missing `actions/checkout`)
- [x] web publish fails due to no GCS auth
- [x] RRD file not published by web publish
- [x] make sure all web_viewer builds on CI are ordered debug -> release
- [x] fix post-release version bump, should also work for alpha
- [x] fix final release version not being updated
- [x] create PRs using gh CLI instead of `create-pull-request` action

**Comment by nikolausWest** [comment]
@jprochazk will you update this issue with the full list?
