### ISSUE TITLE
Automatic scaling of the data density graph can have distracting behavior

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#3783]
The data density graph behaves weirdly when scrolling up and down:

https://github.com/rerun-io/rerun/assets/49431240/6916403d-f1d2-436f-90e1-fc13069dd44b

Reproduced with the Rust-version of the `clock` example based on `main` 4d8fcad62c1ecb647575bfaa138db44b0b2f18aa

**Comment by emilk** [comment]
it's normalizing the height based on the maximum height of any of the graphs

**Comment by abey79** [comment]
Oh ok. So works as intended? @martenbjork any feelings about that?

**Comment by abey79** [comment]
Closing as wont fix (at least for now)
