### ISSUE TITLE
C++ universal "maybeowned" adapting container used everywhere instead of std::vector

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3794]
The ComponentBatch class introduced in #3791 is not actually specific to components at all. We should build it out to a "universal" container that we use in all codegen wherever we use std::vector right now.
It is also what all serialize methods should work with.

* [x] https://github.com/rerun-io/rerun/pull/4236
* [x] #4247

**Comment by Wumpf** [comment]
When looking into this we should keep in mind `TensorBuffer` which might be a bit harder to solve but should also use the maybe-owned concept!

**Comment by emilk** [comment]
Next step of this is also to support strides

**Comment by Wumpf** [comment]
Talking to a user, not only strides would be useful but also byte offsets. Example: Struct like this:

`struct PointAndColor {
float x,y,z;
uint32_t color;
}` 

We want it to be convenient to log arrays of this struct both as points and colors!

**Comment by Wumpf** [comment]
The original issue was solved. Split all the other things that came up into different issues and  list them in a tracking issue here
* #4260
