### ISSUE TITLE
Separate concepts of image file format / compression vs encoding

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#3804]
:warning: This is a fairly large issue that's going to require some thought and refactoring.

## Context

Our Images currently exist as a thin wrapper over TensorData.

As we started to add support for compressed images, we introduced a special-case for JPEG data inside the TensorData type. This should be cleaned up in:
 - https://github.com/rerun-io/rerun/issues/3803
 
 However, support for new image **encodings**, added in:
  - https://github.com/rerun-io/rerun/pull/3541
  
Because multi-plane / multi-resolution images are not well represented by dense tensors, we followed the pattern established for jpegs. We can continue to do this even through the cleanup of  https://github.com/rerun-io/rerun/issues/3803, but ultimately this is not really a semantically correct representation.

Semantically:
 - A multi-plane image (e.g. NV12) should still have a deterministic mapping of pixel-coordinates -> data values. While multi-plane images might involve looking up and combining multiple values, the offsets into the separate channels are still deterministic.
 - A compressed image requires a specific decoding step (likely with caching) to convert it into an image that can be used by the viewer.
  
## Proposal  
The data representation of images and tensors ultimately needs to be split into 3 separate things:
 - Tensors - dense multi-dimensional arrays
 - Images - N planes of dense two-dimensional arrays
 - ImageAssets - BinaryBlobs with a specified format.

Ideally we should be able to *view* an image as a tensor, but even then that view should feature a choice of decoder. For example, converting to 3 planes of RGB vs leaving as up-sampled YCrCb.

**Comment by SeaOtocinclus** [comment]
@jleibs We can't compress gray data, is it expected?
<img width="395" alt="image" src="https://github.com/rerun-io/rerun/assets/74376766/8a4c7cd1-77c7-4ee9-a155-3b6b10d288ed">

Just do the following with an `img` being a gray matrix
```
rr.Image(img).compress(jpeg_quality=75),
```

**Comment by jleibs** [comment]
@SeaOtocinclus thanks for reporting. That doesn't seem expected. I'll take a look.

**Comment by pmoulon** [comment]
@jleibs Found out that the compress options does not seems accessible from the C++ API, ideally it should if we want the different API to be on par
https://ref.rerun.io/docs/cpp/stable/image_8hpp_source.html
