### ISSUE TITLE
Welcome screen flickering / unstable scrollbar / unstable line breaks

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#3827]
**Describe the bug**
See video. Sort of similar to #3072.

https://github.com/rerun-io/rerun/assets/9785832/73c510d8-123a-4d6b-a746-aa145176abef

**To Reproduce**
Change size of viewer close so that the scrollbar barely appears and at the same time the line break in one of the paragraphs changes. This happened to me when opening the viewer after building the prerelease without resizing it.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
```
rerun_py 0.10.0-alpha.6+dev [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu
```

**Comment by emilk** [comment]
This is an unstable state that the egui scrollbars sometimes fall into: hiding the scrollbars leads to a re-layout that adds the need of scroll bars, which causes the available ui area to shrink (to give room to the scroll bars), which leads to a re-layout that now means the scroll bars aren't needed… and so on.

* Will be solved by https://github.com/emilk/egui/issues/3316
