### ISSUE TITLE
Excessive & uneven use of profile scopes results in misleading measurements

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#3850]
Consider e.g. this code:
```rust
let arch_views: Vec<_> = {
    let now = std::time::Instant::now();
    re_tracing::profile_scope!("store_walk");
    let x = range_archetype::<TimeSeriesScalar, { TimeSeriesScalar::NUM_COMPONENTS }>(
        store, &query, ent_path,
    )
    .collect();
    eprintln!("store_walk in {:?}", now.elapsed());
    x
};

{
    let now = std::time::Instant::now();
    re_tracing::profile_scope!("joins");
    for (time, arch_view) in arch_views {
        let Some(time) = time else {
            continue;
        }; // scalars cannot be timeless

        for (scalar, scattered, color, radius, label) in itertools::izip!(
            arch_view.iter_required_component::<Scalar>()?,
            arch_view.iter_optional_component::<ScalarScattering>()?,
            arch_view.iter_optional_component::<Color>()?,
            arch_view.iter_optional_component::<Radius>()?,
            arch_view.iter_optional_component::<Text>()?,
        ) {
           // [...]
        }
    }
    eprintln!("joins in {:?}", now.elapsed());
}

{
    let now = std::time::Instant::now();
    re_tracing::profile_scope!("sort");
    points.sort_by_key(|s| s.time);
    eprintln!("sort in {:?}", now.elapsed());
}
```

When I run this code with my local dataset, I get the following timings for an average frame:
```
store_walk in 24.440935ms
joins in 18.674951ms
sort in 98.991µs
```

Great: the `store_walk` is my biggest bottleneck and is where I should focus my optimization efforts for now...

Now let's take a closer a look using the profiler:
![image](https://github.com/rerun-io/rerun/assets/2910679/cd01d2f3-0b7f-44e9-b06c-2bdddfdb82d3)

Immediately you can see that, due to our excessive use of profile scopes across the codebase, the timings have grown substantially:
```
store_walk in 26.128721ms
joins in 77.89653ms
sort in 178.552µs
```
Now this would be fine in and of itself if the profiling overhead was even across the codebase, but naturally in practice that's never the case.

And since it's uneven, I'm now being misled to believe that not only `store_walk` isn't my main bottleneck, but `joins` is 3x worse than that.

Something to keep in mind I guess... I don't have a solution for this on the top of my head.

**Comment by emilk** [comment]
For more context: the profiling scopes are very cheap (1-2ns) when profiling is turned OFF (the default), but as soon as you start the profiler they start costing 100ns-200ns each.

You can find the most common profile scopes in the Puffin Viewer:

![puffin](https://github.com/rerun-io/rerun/assets/1148717/6d80b51b-e1bd-4f0d-bb55-727c7e6ee2be)

Anything that has more than a few thousand hits in one frame should probably be removed
