### ISSUE TITLE
Pinhole resolution defaults to 1:1

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3852]
The Pinhole archetype has resolution as optional, but defaults to the completely unusable value of 1:1. Given that it is optional most users would probably assume that resolution would be picked up from the image if they log that as well.

Update: while creating this issue I also realized that setting the pinhole incorrectly affects the 2D image view so that it only shows the image inside the pinhole resolution. It's a little unclear to me at time of writing whether that is a good behavior or not, but I think it turns this issue from an annoyance to a bug.

Repro: (remove width and height from pinhole docs example)
```python
import numpy as np
import rerun as rr

rr.init("rerun_example_pinhole", spawn=True)
rng = np.random.default_rng(12345)

image = rng.uniform(0, 255, size=[3, 3, 3])
rr.log("world/image", rr.Pinhole(focal_length=3))
rr.log("world/image", rr.Image(image))
```

![image](https://github.com/rerun-io/rerun/assets/2624717/e0758b16-dc93-4abc-9a03-3177db3fc9f3)

**Comment by emilk** [comment]
We should have no default resolution unless the user sets one
