### ISSUE TITLE
C++: Failure to serialize rotations (`code-examples/transform3d_simple`)

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3865]
Repro: `./docs/code-examples/roundtrips.py transform3d_simple`

This might be related to why `just cpp-test` fails

**Comment by emilk** [comment]
It is specifically rotations that fail to serialize - scales work.

It looks like the `TranslationRotationScale3D::rotation` field is empty during serialization.

```C++
    rec.log(
        "base/rotated",
        rerun::Transform3D(
            rrd::RotationAxisAngle({0.0f, 0.0f, 1.0f}, rrd::Angle::radians(TAU / 8.0f))
        )
    );
```

**Comment by Wumpf** [comment]
scales are _also_ enums though, no? 🤔

**Comment by emilk** [comment]
My printf-debugging yesterday showed me that the serialization code for the Rotation is being called, but the rotation doesn't show up when you `just print output.rrd`
