### ISSUE TITLE
Sanity-check that the C header version and `rerun_c` library version is the same

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#3868]
It is very annoying for users if they get mismatched headers and library files. It can lead to very hard-to-debug problems.

To protect against that we can hard-code the version into both `rerun.h` (`#define RERUN_VERSION …`) and into a library-defined function (`rr_version()`). The C++ library can then check that `RERUN_VERSION == rr_version` before it does anything else.

**Comment by Wumpf** [comment]
CMake needs to parse version from this header as well. Search for ticket number in cmake script to find where
