### ISSUE TITLE
Text document archetype documentation doesn't render correctly

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3904]
https://www.rerun.io/docs/reference/types/archetypes/text_document

It gets confused by the markdown within the code tags
![image](https://github.com/rerun-io/rerun/assets/1220815/6cf5ef05-58ec-4ee6-9fc0-748a1ce42e4b)

**Comment by emilk** [comment]
It will always be problematic to embed a markdown ```-codeblock within markdown, so I suggest we switch the default `text_document` example to one that only show a few basic markdown features.
