### ISSUE TITLE
Crash when supplying too large mesh

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3928]
Similar to too large textures previously, we have issues with too large buffers. Easiest way to get a too large buffer is to supply a too large mesh through any api.

Just as before we need more extensive vetting of user supplied data _and_ need to tell wgpu to allow the largest possible buffer.

**Comment by emilk** [comment]
I tested this:

```rs
    rec.log(
        "big",
        &rerun::Mesh3D::new(vec![[0.0, 0.0, 0.0]; 1_000_000_000]),
    )?;
```

and got no crash, at least not on the native viewer.

It seems like the limit is pretty large, and this issue is more theoretical than the texture size limit

**Comment by Wumpf** [comment]
@roym899 do you remember how you got this issue? I missed to write the down the exact circumstances

**Comment by Wumpf** [comment]
default max buffer size is speced at 256mb https://www.w3.org/TR/webgpu/#limits
so yeah it gotta be a _very_ large mesh, but it can happen :)

**Comment by Wumpf** [comment]
Looks like we can also hit this limit when supplying _a lot_ of plot data. The crash then happens when egui tries to resize its staging buffer for uploading the data
```
thread 'ThreadId(1)' panicked at 'Failed to create staging buffer for index data'
egui-wgpu/src/renderer.rs:834
```
