### ISSUE TITLE
From visual history to a general time query

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#3933]
We currently allow users to set visual history on any data in the blueprint:

https://github.com/rerun-io/rerun/assets/2624717/b5a0a6f3-86e8-48d9-912c-8b217083eb77

This is somewhat useful but could be made much more powerful if we expanded this to be a more general time query. You should be able to:

- Specify a full time range / window with beginning and end
    - For example: https://github.com/rerun-io/rerun/issues/2547
    - Relative to currently selected time point or
    - Relative to latest time on timeline or
    - Fixed in time
    - With windows that start and end both before and after the current time selection
- https://github.com/rerun-io/rerun/issues/1648
- More types should also support visual history
   - For instance 
       - https://github.com/rerun-io/rerun/issues/3510
   - Related
       - https://github.com/rerun-io/rerun/issues/723
   - If a (ViewPart) type doesn't support visual history, we shouldn't let the user set it

**Comment by abey79** [comment]
#4123 adds support for specifying more general time ranges.

For the rest, I've started a proper tracking issue:
* #4107
