### ISSUE TITLE
Explore possibility to bundle libarrow so users don't need to install it

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3976]
bundle / statically link libarrow - whatever is needed to not have it be a manual user install! See also static section on https://arrow.apache.org/blog/2020/07/29/cpp-build-simplification/

**Comment by emilk** [comment]
This is a huge usability win if we can manage it

**Comment by jleibs** [comment]
This was done in https://github.com/rerun-io/rerun/pull/4051
