### ISSUE TITLE
Grayscale image presented too dark

### ISSUE THREAD

**Issue by playreplayoliver** [rerun-io/rerun#3994]
**Describe the bug**
Gray scale images is presented much darker in 0.9.1 compared to <= 0.8.2

**To Reproduce**
Running the following code...
```
import numpy as np
import rerun

x, _ = np.meshgrid(np.arange(0, 640), np.arange(0, 400))
im = (255 * x / x.max()).astype(np.uint8)
im[:, 350:] = 0
rerun.init('gray')
rerun.spawn()
rerun.log_image('image', im)

```
... on versions
pip3 install rerun-sdk==0.8.2
![0.8.2](https://github.com/rerun-io/rerun/assets/103262483/b488cddb-11b8-4c23-bb9f-afa469ae1b31)

pip3 install rerun-sdk==0.9.1
![0.9.1](https://github.com/rerun-io/rerun/assets/103262483/1a15baef-fbbb-4da1-aec9-3a0cdd7b147b)
**Expected behavior**
The behavior of 0.8.2 is expected

**Desktop (please complete the following information):**
6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Rerun version**
rerun_py 0.9.1 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu 00fa796, built 2023-10-12T12:13:35Z

**Additional context**
See previous issue: https://github.com/rerun-io/rerun/issues/1990
And previous pr: https://github.com/rerun-io/rerun/pull/2014

**Comment by Wumpf** [comment]
Previously fixed in:
* #2014
Regressed in
* #3391
