### ISSUE TITLE
Warning about missing quotes in entity paths can be annoying

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#3995]
> WARN  re_log_types::path::parse_path] Found an entity path 'world/100_7100.JPG' that was not in the normalized form. Please write it as 'world/"100_7100.JPG"' instead.

**Comment by emilk** [comment]
Yeah, this was maybe a bit aggressive on my part. Perhaps we should rethink the "name" vs "Index::String" dichotomy. It is at the moment just adding complexity and confusion.

**Comment by emilk** [comment]
We should also consider adding helpers for constructing entity-paths int our public API:s, especially for C++.
See for instance https://github.com/rerun-io/cpp-example-vrs/pull/1/files/4cafa610dcd9c5b1653b7e474d5b954fa9bd9536#r1377867266
