### ISSUE TITLE
Check our markdown files for syntax errors

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4007]
See this PR https://github.com/rerun-io/rerun/pull/4006 for example which had this:

```
* [C++]cpp.md)
```

which is not valid markdown

**Comment by jprochazk** [comment]
another example of "broken" syntax is:

```md
<div>

<div></div>
</div>
```

which we ran into before:
- https://github.com/rerun-io/rerun/issues/5822#issuecomment-2041060580

**Comment by jprochazk** [comment]
This would be a significant undertaking because there are no tools that can do this kind of strict syntax checking. =
