### ISSUE TITLE
re_datastore: arrow table debug-view

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#404]
A birds-eye view of our inner table/query engine.

This is a nice panel for looking into the main table(s) and seeing their columns etc. Good for debugging, but also shows the user data in its most naked form.

This is in aid of #393

**Comment by emilk** [comment]
This can now be implemented as a separate space view class. However, it makes very little sense unless we also have the UI to select/switch between different space view classes.

**Comment by emilk** [comment]
Some inspiration:
* `examples/rust/custom_space_view`
* `examples/rust/extend_viewer_ui/src/main.rs`
* Together with `egui_extras::TableBuilder` (see usage in the current code)

**Comment by abey79** [comment]
A very short, immediately useful thing could be a `Dump datastore` command in the Command palette that would `eprintln!` the datastore.

I'm currently sticking this in `App::ui()`:
```rust
        if let Some(ctx) = store_context {
            if let Some(recording) = ctx.recording {
                eprintln!("{}", recording.entity_db.data_store);
            }
        }
```
