### ISSUE TITLE
Match python and cpp arrow versions

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4050]
Although in theory there *shouldn't* be a hard link between versions of arrow across our different languages, the arrow conda projects seem to make `libarrow` and `arrow-cpp` require the same version. This means if `rerun-cpp` needs a different version of arrow that `rerun-py` we can't use both in the same conda package.

Specifically this prevents us from having a pixi project which includes `arrow-cpp` and also `rerun-sdk` to streamline launching via `spawn`

**Comment by abey79** [comment]
Note that supporting Python 3.12 (#3699 ) will require PyArrow 14.

**Comment by Wumpf** [comment]
we match cpp & arrow by now!
