### ISSUE TITLE
Logging SDK speed regression

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4093]
The C++ logging SDK is adding _a lot_ of overhead, and we need to figure out why.

Reportedly 2ec5ce7 was much faster than 0.10.0, so something in https://github.com/rerun-io/rerun/compare/2ec5ce7...0.10.0 broke (TODO: verify).
Maybe https://github.com/rerun-io/rerun/commit/c0521eee4176992c487c9683ff4eb6709b5880cf causes a Debug build of arrow-cpp to be built or something?

```
$ time RERUN=on ./build/rerun_vrs_example sample.vrs
real    0m15.105s
user    0m16.409s
sys     0m2.981s

$ time RERUN=off ./build/rerun_vrs_example sample.vrs
real    0m1.060s
user    0m1.043s
sys     0m0.017s
```

More info: https://rerunio.slack.com/archives/C04UBTMMGJK/p1698696318766679

**Comment by jleibs** [comment]
Using `-DRERUN_DOWNLOAD_AND_BUILD_ARROW=off` definitely seems to alleviate the problem.

With: `-DRERUN_DOWNLOAD_AND_BUILD_ARROW=on`
```
$ time RERUN=on ./build/rerun_vrs_example sample.vrs
real    0m15.105s
user    0m16.409s
sys     0m2.981s
```

With: `-DRERUN_DOWNLOAD_AND_BUILD_ARROW=off`
```
$ time RERUN=on ./build/rerun_vrs_example sample.vrs
real    0m3.643s
user    0m4.754s
sys     0m1.643s
```
