### ISSUE TITLE
Symbol not found errors when using the rerun-built arrow-cpp

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4095]
### Error
A user reported the following error when trying to run one of the examples:
```
./example_minimal
dyld[24822]: Symbol not found: __ZN5arrow11dense_unionENSt3__16vectorINS0_10shared_ptrINS_5FieldEEENS0_9allocatorIS4_EEEENS1_IaNS5_IaEEEE
```

### Known workaround
It appears we can work around this issue by specifying
```
-DRERUN_ARROW_LINK_SHARED=off
```

### Speculation
User may have a system instrall of arrow-cpp that's getting picked up at runtime instead of the version we are building.
 - I've confirmed this can happen on Linux if you happen to have a system install of arrow-cpp that matches the version we are compiling.

**Comment by emilk** [comment]
This has now been mitigated. We now link with arrow statically by default:
* https://github.com/rerun-io/rerun/pull/4101
