### ISSUE TITLE
Direct links for examples on app.rerun.io

### ISSUE THREAD

**Issue by karimo87** [rerun-io/rerun#4122]
I often want to include a link to a specific example on app.rerun.io on social media or in user conversations. Since that is not possible right now I am linking to app.rerun.io and then have to add an explanation on how to find the right example. This feels cumbersome and is likely costing us traffic.

**Comment by jprochazk** [comment]
https://github.com/rerun-io/rerun/pull/4165 will add a command to copy a direct link to the fully qualified URL of an example, so you will:

1. Open `app.rerun.io`
2. Navigate to the example you want to point people to
3. Open the command palette (CTRL+P / CMD+P)
4. Run the "Copy direct link" command
