### ISSUE TITLE
UI workflow for adding DataQuery with query expression

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4157]
- https://github.com/rerun-io/rerun/issues/4128

Adds support for a new DataQuery implementation that stores a query expression. Need a UI workflow for adding such a query to a space view.

- Needs to track the query expressions that have been added:
  - Path  (world)
  - Path + Recursive (world/)
  - Recursive ony (world/*)
- Should show preview of the query results

**Comment by Wumpf** [comment]
we have this!
