### ISSUE TITLE
Use the `ListItem` style for the component list (in the Selection Panel when an entity is selected)

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4161]
This is a list with "synchronised" hover highlight just like the Blueprint and Streams UI. It should be styled the same way.

Design (ignore the fact that components are hierarchical here):
<img width="302" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/3620ea5d-6259-4ca7-986e-0df976b67147">
<br/><br/>

blocked by:
- https://github.com/rerun-io/rerun/issues/6245

**Comment by abey79** [comment]
List Item 2.0 is close to ready for this, but I'm encountering a number of issues:
- `DataUi` implementations makes widespread use of `ui.label(...)` even for `UiVerbosity::Small`, which is bad because it doesn't truncate by default. Instead, we should use `ui.add(egui::Label::new(...).truncate(true))`. Easy but annoying to fix.
- `DataUi` ui very often "captures" hover (e.g. when hovering over the egui label), which "unhovers" the list item itself, for a very distracting effect. `ListItem` deals with this by checking if the content is itself hover, and if so uses a dimmer background for a much better experience. However, `DataUi` doesn't return an `egui::Response`, so the hover information is lots. A possible fix for that would be for list item to check cursor position instead of content response.
- Some `DataUi` implementation of `UiVerbosity::Small` is really busted (e.g. `Rotation3D` in axis/angle mode. Not yet sure how widespread this is.

**Comment by emilk** [comment]
> * `DataUi` implementations makes widespread use of `ui.label(...)` even for `UiVerbosity::Small`, which is bad because it doesn't truncate by default. Instead, we should use `ui.add(egui::Label::new(...).truncate(true))`. Easy but annoying to fix.

We should make this a global setting, `ui.style_mut().labels.truncate = Some(true);` or whatever

**Comment by abey79** [comment]
Yes, the global truncate setting would be really nice!

**Comment by abey79** [comment]
> We could make this a global setting, `ui.style_mut().labels.truncate = Some(true);` or whatever. We could also add a `ui.label_truncated(…)` helper.

https://github.com/emilk/egui/issues/4473
