### ISSUE TITLE
Logging API for "temporal batches"

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4184]
When translating existing time-series plots to Rerun our logging APIs have very poor ergonomics.

A user must iterate through every sample, calling set_time with the time value, and then logging the individual scalars.

The proposal from:
 - https://github.com/rerun-io/rerun/issues/3841
 
 Would let us optimize this a bit by passing the time values into the log-calls, but will still be order-N which can be quite painful for large time-series.
 
 A direct temporal batch logging API would instead let us collapse this into a single call. For example:
 ```
 rr.log_temporal_batch(timestamps=[...], ScalarBatch(...))
 ```

This would let us dramatically optimize the ingestion by letting us create a pre-batched uniform buffer of scalars that looks like what the eventual output of the batcher is going to be anyways.

**Comment by emilk** [comment]
Blocked by https://github.com/rerun-io/rerun/issues/5967

**Comment by jleibs** [comment]
- https://github.com/rerun-io/rerun/pull/6587 introduces an initial python API.

Missing things to complete this workstream:
 - https://github.com/rerun-io/rerun/issues/6592
 - Egonomic Rust and C++ APIs

**Comment by jleibs** [comment]
We should do a session on naming and usabillity of this prior to release 0.18
