### ISSUE TITLE
Add support to skip the "latest_at" semantics with range queries

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4192]
For $REASONS, "empty" range queries exhibit the "latest at" semantics.

In some case, this is questionable:

<img width="1605" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/7ad0b73c-94a4-4d41-bffb-64d07007dcc1">

In other case, this is outright problematic:

https://github.com/rerun-io/rerun/assets/49431240/206be5af-d117-4879-a550-5d91b5472d5a

Range queres _without_ the "latest at" semantics should possible, and used at least in `TimeSeriesSystem::load_scalars()`.

**Comment by teh-cmc** [comment]
Should not be too hard to add a switch for this in `RangeQuery`:
```diff
 pub struct RangeQuery {
     pub timeline: Timeline,
     pub range: TimeRange,
+
+    /// Should the result include the latest compacted state at `range.min`?
+    pub include_latest: bool,
 }
```

**Comment by teh-cmc** [comment]
Range queries don't have this weird behavior anymore (they are now multi-tenant proof).
