### ISSUE TITLE
Support per-space-view-class property defaults

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4194]
#4179 highlighted the need for specific default for, in this instance, visible history properties in timeseries space view. This might be a recurring pattern, so a proper mechanism for this should be devised for this (e.g. `SpaceViewClass` should have chance to set default values).

**Comment by Wumpf** [comment]
There could be the concept of a default provider that given component name tries to give you a default value or none.
This default provider would be implemented by either `Visualizer` or `SpaceView`. `EditUi` can take in a generic default provider then to determine defaults when needed.

Related to:
* #6071

**Comment by Wumpf** [comment]
* Fixed in #6465
