### ISSUE TITLE
Provide CMake install target setup

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4207]
Ever since we released the C++ SDK, having no cmake INSTALL is a common limitation people hit. Usecase examples:

* Use with a different build system (see https://github.com/kyle-figure/bazel-minimal-rerun/blob/main/third_party/rerun/patches/cmake.patch)
* Not having to build Rerun again from scratch for several rerun using applications on the same machine
* Using it with your own library that uses `install` (https://discord.com/channels/1062300748202921994/1173517222010966047/1173517222010966047)
*  #4130

**Comment by rishabh-slamcore** [comment]
Tried cloning and running `scripts/setup_dev.sh`
It fails in `scripts/setup.sh` line `rustup install 1.72.1`
The script assumes `rustup` is available on my vanilla ubuntu 20.04, which is not the case.

**Comment by Wumpf** [comment]
@rishabh-slamcore This issue here is specifically about the C++ SDK distribution, not about building Rerun from the repository. For getting started with the repository check https://github.com/rerun-io/rerun/blob/main/BUILD.md#getting-started-with-the-repository - you first have to install rustup. The setup shell scripts aren't in a good shape generally, we gonna soon replace it with a full pixi setup, see 

* #4170 

But worth noting you only need all of this when you want to build Rerun from the repository which is typically only when you want to modify something for a fork (with the goal of either experimenting, making personal enhancements or contributing) 🙂
