### ISSUE TITLE
`DataResult` should track the inheritance source along with the resolved properties

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4245]
Whenever we display some inherited properties (e.g. in the Visible History changes from #4222), it would be useful to provide the user with context on _what_ those value where inherited from (e.g. maybe to add a button to jump there in the selection panel). This means we must track the source alongside resolving properties.

**Comment by Wumpf** [comment]
We sidestepped this by limiting inheritance for the moment to Default (view!) and override (individual!)
The only odd one out is 'visible'.

We will however have this issue again once we introduce path filter driven overrides. But the problem statement is a bit different, so closing this!
