### ISSUE TITLE
Export TimeSeriesScalars as CSV

### ISSUE THREAD

**Issue by nonl4331** [rerun-io/rerun#4252]
**Is your feature request related to a problem? Please describe.**
I'm using rerun to log Odometry data in real-time. A lot of the time looking at the data on rerun isn't enough and I'd like to do further processing on it. Currently to my knowledge there is no way to export the data outside of rerun in a format usable by other programs.

**Describe the solution you'd like**
One possible solution to this would be to add a export to CSV to the rerun client when selecting a time series.

**Describe alternatives you've considered**
It's possible to parse into a CSV from the rrd format but I believe that it would be too much of a hassle for most people.

**Additional context**
Adding a way to only export data within a selection would also be useful.

**Comment by nikolausWest** [comment]
Thanks for opening this issue @nonl4331! I can totally see why this is needed and we've heard similar requests from other users. We're working on a series of infrastructure pieces that need to land before we can do this _in the right way™️_, but we'll have a think about if there is reasonable workaround in the meantime.

If you're willing to write some Rust code to do it you could always do something like write a rust cli tool that uses Rerun crates to deserialize an rrd file and then write it out in whatever format you like. That way you can first export the section of the recording you want from the viewer, and the run your CLI tool on it to export to your desired format. If you want to go this route, let us know. We're happy to provide help and pointers.
