### ISSUE TITLE
Allow following of time series data with a limited time window

### ISSUE THREAD

**Issue by nonl4331** [rerun-io/rerun#4253]
**Is your feature request related to a problem? Please describe.**
I'm using rerun to log Odometry data in real-time. This is problematic given that the default view shows all the data at once which means the data is continuously getting squished together in a way that often renders it unreadable. More often than not I might want to view the last x seconds.

**Describe the solution you'd like**
Have a view setting or option in the rerun client to track the last x units of time for time series data.

**Describe alternatives you've considered**
A right click selection works for viewing a certain timeframe but it does not follow new data.

**Comment by nikolausWest** [comment]
This is actually done and coming in the next release!
