### ISSUE TITLE
Automatic deletion or thinning of timeseries data

### ISSUE THREAD

**Issue by nonl4331** [rerun-io/rerun#4254]
**Is your feature request related to a problem? Please describe.**
Logging a large amount of time series data can cause rerun to lag and use significant amounts of memory especially for longer recordings.

**Describe the solution you'd like**
A configurable deletion or thinning of old time series data would reduce the overall amount of data while still allowing a high data density for more recent data.

**Describe alternatives you've considered**
- Lower logging rate from the application. This can cause high frequency information to be missed.
- Multiple rerun recordings. This is inconvenient.
- Nothing. This isn't a great option since this issue can cause the client to crash.

**Additional context**
This is a separate but tangentially related question but there a mechanism where data be differed/batched for higher bandwidth logging? (this would also allow thinning operations and similar to be performed more easily)

**Comment by nikolausWest** [comment]
Hi @nonl4331! Thanks again for opening an issue! We have some very significant performance improvement to time series plots on the way which should make some pretty large strides here. There is a generic garbage collection mechanism that drops old data built into Rerun (see https://www.rerun.io/docs/howto/limit-ram). My hope is that those two together should actually solve your issue completely.

Regarding thinning old data I don't foresee us dong that anytime soon.
