### ISSUE TITLE
wgpu 0.18 warning spam when resizing window

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4297]
Repo is simple: `git checkout andreas/wgpu-0.18`, `cargo rerun`, open dicom, and resize the window:

I fail to repro on `main`

![wgpu-warnings](https://github.com/rerun-io/rerun/assets/1148717/476efcbf-53f4-4bdd-83e7-693e49c6f165)

```
[2023-11-21T16:43:22Z ERROR re_renderer::error_tracker] WGPU error tick_nr=6426 description=Validation Error
    
    Caused by:
        In a RenderPass
          note: encoder = `encoder`
        In a set_viewport command
        Viewport has invalid rect Rect { x: 1660.2888, y: 208.80003, w: 711.71136, h: 294.69302 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target Extent3d { width: 2372, height: 1604, depth_or_array_layers: 1 }
    
[2023-11-21T16:43:22Z ERROR wgpu_core::present] No work has been submitted for this frame
```

We should
A) catch this error before wgpu does
B) prevent this error from happening

**Comment by Wumpf** [comment]
this must be a set_viewport call in egui since from the looks of it we never set fractional sizes/positions for viewports
