### ISSUE TITLE
Link to external C++ examples on examples page

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#4315]
There are no links to the [VRS](https://github.com/rerun-io/cpp-example-vrs) and [OpenCV / Eigen](https://github.com/rerun-io/cpp-example-opencv-eigen) example on the examples page right now.

**Comment by emilk** [comment]
I wonder under what heading this belongs:

<img width="655" alt="image" src="https://github.com/rerun-io/rerun/assets/1148717/d14634f8-0315-4c04-8601-cc7b3ad079ef">

A new heading?

**Comment by roym899** [comment]
Hm, I think the headings are a bit odd in general right now. But the way it is right now, I'd put VRS to Real Data, and the other one to articifial data.
