### ISSUE TITLE
Update Space View/Container/Visualizer icons to represent both type and sub-type

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4321]
Icons should generally encode two piece of information:
- Type:
   - space view
   - container
   - visualiser
   - other (this is yet ill-defined, generally include data-related things like entities/component/group/query/etc.)
- For space views and containers: sub-type: 3D vs. 2d vs. timeseries vs. text etc.
- For visualisers, we decided to stick to a single icon for all, for the time being.

One should immediately recognise a thing as being a space view even if that particular space view type was never seen before.

This issue is about (roughly in this priority order):

- [ ] devising a "top-level" icon style for each of Space View, Container, Visualizer categories (stretch goal: the loosely defined Data category, which would include entities, component, instances, etc.)
- [ ] updating/creating all Space View icons to the new style
- [ ] creating all Container icons
- [ ] creating the (unique) Visualiser icon

Current list of space view types:

<img width="178" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/c58fad7c-4028-4c7f-81cb-cf0c31809352">

Current list of container types:

<img width="94" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/1f4045a2-472e-433a-a060-88ac8ac616e4">

**Comment by nikolausWest** [comment]
Note on where these icons will be used:

1. In the blueprint tree
2. In the "contents" section in the selection view when a container is selected
3. In the "add space view or container" modal. Note: these icons may be significantly bigger so it may be preferable to use larger illustrations instead for these.

**Comment by abey79** [comment]
### Space View types

Here is the list of existing space views, followed by a few screenshot to illustrate the less obvious ones.

<img width="178" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/c58fad7c-4028-4c7f-81cb-cf0c31809352">

Bar chart:

<img width="461" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/12717fd8-0712-427e-aa96-7d36350afcc9">

Text document (can be either markdown or raw text):

<img width="457" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/984c2bae-8c0c-4b40-9a4b-506ed15811c5">

Tensor:

<img width="910" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/62626eca-c716-43c6-aab1-27191714c580">

Text Log:

<img width="450" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/cc2d5157-a987-47fa-b016-d269a06bdd3d">

Dataframe (big table of all the data):

<img width="874" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/f98f0974-e195-400e-b869-03698e3537b2">


### Visualiser types

Short-term decision: let's have one icon for all visualiser types.

For context, the visualiser more or less match the list of archetypes, which can be found here: https://www.rerun.io/docs/reference/types/archetypes

### Other icons

Things that are in used today:

<img width="430" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/164c1be5-8a44-4a47-846b-27dfa43b4a3d">

Issues:
- bullet vs. diamond is very hard to tell apart at default scale
- the notion of "group" is likely to disappear
- the notion of "entity-in-a-space-view" (vs. "entity-in-streams") is going to evolve

To sketch it briefly, the blueprint hierarchy will go Container -> Space View -> Queries -> Visualiser -> Data, where Visualiser will display "Data" that results from "Queries". This data will typically be entities from the store, but could also be other things (like inline data). This means that we will shortly need these icons:

Things in the data store:
- entities
- component

Things in the blueprint tree:
- query
- visualizer
- "data" (this is yet ill-defined, there might be subtypes like "data-from-entity", or "static data", etc.)

**Comment by abey79** [comment]
Great progresses made today. TBC early Jan 2024. Battle plan here: https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?type=design&node-id=1253-9760&mode=design&t=UqJM8rlATmsnLzze-0

**Comment by abey79** [comment]
This is mostly done. Remaining effort to be tracked here: https://github.com/rerun-io/rerun/issues/4827
