### ISSUE TITLE
`About` menu should display the rendering backend being currently used

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4337]
It's currently impossible to get that information in many cases AFAICT.

This should ideally tell you the complete story, e.g. "OpenGL ES via wgpu on X11".

**Comment by teh-cmc** [comment]
It should also log the actual device being used, especially for linux laptops where it takes a few PhDs to find out what GPU is actually being used by an app.

**Comment by Wumpf** [comment]
Loosely related to:

* #4898

**Comment by emilk** [comment]
We have this now, though the full details only show on hover:

![image](https://github.com/rerun-io/rerun/assets/1148717/3bc70e40-612a-4ee6-8123-8918547d81aa)

And the full details are logged (twice, in fact!):

```
[2024-01-30T11:53:05Z DEBUG egui_wgpu] Picked the only available wgpu adapter: backend: Metal, device_type: IntegratedGpu, name: "Apple M3 Max"
[2024-01-30T11:53:05Z DEBUG re_renderer::context] wgpu adapter backend: Metal, device_type: IntegratedGpu, name: "Apple M3 Max"
```
