### ISSUE TITLE
Timeless counter underflow warning when opening plots example with old blueprint

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4355]
Got this warning:
```
[2023-11-27T18:13:31Z WARN  re_data_store::time_histogram_per_timeline] Timeless counter underflowed, store events are bugged!
```
when opening the plots demo with an outdated blueprint.

Note that we changed this to be a debug warning on the 0.11.0 release branch

**Comment by emilk** [comment]
Let's verify this is a debug-only warning.

Can we repro it?
Can we improve the error message to help figure out what goes wrong?

**Comment by teh-cmc** [comment]
> Let's verify this is a debug-only warning.

Ha no, I remember now (by which I mean Andreas pointed that out just above :man_facepalming:): we only changed it on the release branch for 0.11.

Yeah this should really always be a `debug` log, especially now that we enable debug logs by default in debug builds: there's nothing that an end-user can do with that information beside being scared.

**Comment by Wumpf** [comment]
so the only action point is to make this a debug log? Okay!

**Comment by emilk** [comment]
We haven't seen this in a while 🤷
