### ISSUE TITLE
Adding new datatypes causes CI failures for cpp doc links in linkinator

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4382]
See: https://github.com/rerun-io/rerun/pull/4311

Failure here: https://github.com/rerun-io/rerun/actions/runs/7025830274/job/19117413595?pr=4311

Not sure why this isn't a problem with the python or rust doc-links.

**Comment by Wumpf** [comment]
ah that's because linkinator fails to check broken ankors -the page itself is already there https://ref.rerun.io/docs/python/stable/common/datatypes#rerun.datatypes.Uuid
