### ISSUE TITLE
Logging lots of out-of-order data using the same timepoint on a timeline leads to extreme slowdown in datastore

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4415]
A user shared a puffin profile of _very_ slow data ingestion

[slow_ingestion.puffin.zip](https://github.com/rerun-io/rerun/files/13523843/slow_ingestion.puffin.zip)

![image](https://github.com/rerun-io/rerun/assets/1148717/5951ecdf-850c-42d9-a25a-3dcf7d74f698)

![image](https://github.com/rerun-io/rerun/assets/1148717/d80de7f1-de2c-44a8-ad72-71e81af8ba86)

What I see is this: the data ingestion (which is currently happening in the main rendering loop, see https://github.com/rerun-io/rerun/issues/4298) gets a message containing ~3800 rows of data. Processing that takes ~2 seconds, because each insertion takes a whopping ~9ms. The bulk of the insertion cost is re-sorting, which makes me suspect that the reason for this new slowdown is out-of-order insertions.

There are several layers of bad here:
* As mentioned, we shouldn't be doing insertions on the main render loop (https://github.com/rerun-io/rerun/issues/4298)
* If we do, we should make sure to not use more than a certain time budget
* Each insertion should not be this slow, even with out-of-order insertion

### Workarounds
* Run the logging with `RERUN_FLUSH_NUM_ROWS=1`: this will create smaller chunks of work for the viewer, which should get back the viewer frame-rate, but still with slow ingestion

* Stop logging data out-of-order. This could happen if you are using custom timelines that are not monotonically increasing. Rerun _should_ support out-of-order logging, but it seems like we're hitting a bad corner case here.

### Other notes
It would be great if we could tell from a puffin profile whether or not the code that was running was a debug or release build.
If this was from a debug build, then this whole issue is a mistake.

* **EDIT**: https://github.com/EmbarkStudios/puffin/issues/171

**Comment by teh-cmc** [comment]
> It would be great if we could tell from a puffin profile whether or not the code that was running was a debug or release build.
If this was from a debug build, then this whole issue is a mistake.

+1 -- even the whole rerun versioning string ideally

**Comment by emilk** [comment]
#4417 only pushed the problem to later:

<img width="1220" alt="Screenshot 2023-12-04 at 17 13 27" src="https://github.com/rerun-io/rerun/assets/1148717/4b48bae8-2d34-46b7-9c02-93cc207b8b36">

The user was using `rec. set_time_sequence` temporarily for logging a few things, then never called `disable_timeline`. The user then went on to log 800k+ of other things, all ending up on the same timepoint in this "temporary" timeline.

**Comment by emilk** [comment]
For future adventurers:

The problem with splitting the buckets further even when they share the same timepoint, is the definition of `IndexTable::buckets`:

```
pub buckets: BTreeMap<TimeInt, IndexedBucket>
```

Since `BTreeMap` doesn't allow duplicate keys, we would need to change the key there, or add "sub-buckets" inside `IndexedBucket` split on `RowId`. In either case, it is an annoying change.
