### ISSUE TITLE
Class labels in 3D view should be hidable

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#4451]
**Is your feature request related to a problem? Please describe.**
After adding an annotation context class labels show up in the 3D view. These labels in 3D space can take too much space and hide other data in some cases. 

Example from nuScenes example:
![Screenshot from 2023-12-07 10-25-50](https://github.com/rerun-io/rerun/assets/9785832/15ce7e63-cf52-4623-b782-b3dbb708f5aa)

**Describe the solution you'd like**
Add a toggle to show / hide class labels.

**Describe alternatives you've considered**
Not logging class labels is of course a workaround, but it would be nice to keep the class label information on hover.

**Comment by Wumpf** [comment]
This works now with `ShowLables`!
