### ISSUE TITLE
DisconnectSpace and TimeSeriesScalar

### ISSUE THREAD

**Issue by rangsjo** [rerun-io/rerun#4465]
**Describe the bug**

rerun_example_disconnect_space does not work if TimeSeriesScalar is logged in python.

**To Reproduce**
1. Run:

            # Slightly modified example code for disconnect space
            rr.init("rerun_example_disconnect_space", spawn=True)

            # These two points can be projected into the same space..
            rr.log("world/room1/point", rr.TimeSeriesScalar(0))
            rr.log("world/room2/point", rr.TimeSeriesScalar(1))

            # ..but this one lives in a completely separate space!
            rr.log("world/wormhole", rr.DisconnectedSpace())
            rr.log("world/wormhole/point", rr.TimeSeriesScalar(3))
3. Look in the viewer for disconnected spaces.

**Expected behavior**

Two different spaces should be shown, but as stated, all signals are shown in one single space.

**Screenshots**

![image](https://github.com/rerun-io/rerun/assets/9679621/594046be-8f4f-4c31-b8f3-b1bdc18456c9)

**Desktop:**
 - OS: ubuntu 22.04 

**Rerun version**

rerun_py 0.10.1 [rustc 1.72.1 (d5c2e9c34 2023-09-13), LLVM 16.0.5] x86_64-unknown-linux-gnu release-0.10.1 e596e4e, built 2023-11-02T16:05:55Z

**Comment by Wumpf** [comment]
Thanks for filing the issue! This is indeed a bug the way `DisconnectedSpace` is defined. That said, itself is a workaround for not being able to specify what goes into which space view from code which is luckily about to change! (we've been saying that for a while now, but we're finally almost there 😅 )
We're also meanwhile want to make the way space view heuristic spawning works a bit more scalable and predictable. As part of that we concluded that `DisconnectedSpace` will likely be renamed to `UndefinedTransform` and only be applicable to 2D & 3D space views. I.e. it is regarded as a special spatial transform.

.. but as things are this is a bug as described.

**Comment by Wumpf** [comment]
Related to:

* #4388

**Comment by emilk** [comment]
The plan is that setting up spaceviews should be done via the new blueprint API when this issue is done:
* https://github.com/rerun-io/rerun/issues/4167
