### ISSUE TITLE
Implement an entity path filter

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4486]
A set of include/exclude rules, with the most specific rule winning:

```diff
+ world/**           # add everything…
- world/roads/**     # …but remove all roads…
+ world/roads/main   # …but show main road
```

`**` matches anything, including `/` _and parent_ (`/world/**` matches `/world`).
As a start, we only allow `**` as a suffix, and we don't match on single `*`.

We will use this filter when describing what entities to include in a space view.

See https://www.notion.so/rerunio/Query-DSL-b9ebd276ff3f44bc91dc62f8b8857ea1?pvs=4  for more

**Comment by abey79** [comment]
cc @martenbjork

**Comment by Guptajakala** [comment]
@emilk this is very useful, thank you!
Is there any plan to support wild cards at middle? E.g. `- world/roads/**/white`?
