### ISSUE TITLE
Picking, point rendering and outlines spuriously don't work on some Chrome + OS version combinations

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4500]
Tracking for this issue
https://bugs.chromium.org/p/chromium/issues/detail?id=1510915
for all we know this affects any version where ANGLE directly translates to GL (usually against better judgement ;))
So far no success in isolating it to a simpler scene.

Workaround for Mac
===========================
If you hit this on Chrome/Chromium/Brave/Vivaldi/Arc/[other chromium deriviatives] on Mac you can work around it:
* go to chrome://flags/
* search for `angle`
* set `Choose ANGLE graphics backend` to `Metal` 
* restart the browser

**Comment by emilk** [comment]
According to @Wumpf wgpu is unaffected.

Sadly we cannot compile a single Wasm for both WebGL and WebGPU: https://github.com/gfx-rs/wgpu/issues/2804

**Comment by Wumpf** [comment]
> According to @Wumpf wgpu is unaffected.

figuring this is a typo and supposed to mean `WebGPU`. Well, we don't have that good of a test coverage for WebGPU. For starters there's no WebGPU support on Chrome @ Linux to begin with. On Mac and Windows I have indeed not yet observed issues, but I didn't test with all the various Chromium derivatives that we're having trouble with here. Also, I recently only ran re_renderer demos and those worked well on WebGL as well, so not worth much

**Comment by emilk** [comment]
I can confirm that WebGPU works in my MacOS Brave browser (running chromium 120.0.6099.71), but WebGL does not.

WebGL:
![image](https://github.com/rerun-io/rerun/assets/1148717/ec268611-1208-4475-9d29-be8532d59559)

WebGPU:
![image](https://github.com/rerun-io/rerun/assets/1148717/0ed06394-551d-4561-89bb-4138959a8340)

**Comment by Wumpf** [comment]
This got fixed in Chrome 120.0.6099.199
It affected all Chrome Angle renderers.
