### ISSUE TITLE
Default plot bounds are broken

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4503]
run `./examples/python/plots/main.py` or visit https://app.rerun.io/commit/ab2b047/?url=https://app.rerun.io/commit/ab2b047/examples/plots.rrd and you'll see

![image](https://github.com/rerun-io/rerun/assets/1148717/fdf297bd-5b47-4ca3-9cc1-8f8b1658b2e4)

**Comment by emilk** [comment]
* Caused by https://github.com/emilk/egui/issues/3712

**Comment by abey79** [comment]
Will be fixed by https://github.com/emilk/egui/pull/3722
