### ISSUE TITLE
Highlight linked entity when hovering over text link

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#4538]
**Describe the annoyance**
Typically when hovering over an entity the same entity is highlighted in other views as well. This is currently not the case for text links, yet, when clicking the text link the entity is selected and will be highlighted.

https://github.com/rerun-io/rerun/assets/9785832/b7923790-f09d-4eb7-8988-a922afb4cc98

It would be nice to add the grey highlighting for linked entities.

**Comment by emilk** [comment]
This need some way to ask egui "What link, if any, is being hovered?"
