### ISSUE TITLE
Un-skip `github.com` and `static.rerun.io` links in linkinator

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#4556]
https://github.com/rerun-io/rerun/pull/4553 introduced changes to frontmatter that linkinator is not happy about. It includes the end quote of the `thumbnail` and `source` URLs as part of the link for some reason, which means the links don't go anywhere. For now those links are just skipped, but we should figure out what the actual issue is, fix it, and then remove the exclusion.

**Comment by Wumpf** [comment]
* Fixed in #5969
