### ISSUE TITLE
CocoaPods support?

### ISSUE THREAD

**Issue by CatalinVoss** [rerun-io/rerun#4568]
Would be super nice to have the C++ lib hosted on CocoaPods or otherwise facilitate easy integration with iOS.

**Comment by Wumpf** [comment]
We currently don't have C++ support for iOS to begin with, so any support for package management that is targeting that is further out still. Also, isn't CocoaPods a package manager for Objective-C and Swift?

Various package manager requests for C++ keep popping up, closing in favor of:
* #4579
