### ISSUE TITLE
Support multi-selection in blueprint view to show/hide selection

### ISSUE THREAD

**Issue by juliencbmeta** [rerun-io/rerun#4588]
**Is your feature request related to a problem? Please describe.**
When using multiple views, I would like to be able to multi-select a list of objects in the blueprint view, and show/hide the entire selection. It seems that right now we can only hide or show one item at a time. The selection is being ignored.

**Describe the solution you'd like**
Show/hide the entire selection from the blueprint view.

**Describe alternatives you've considered**
Alternative is to show/hide one element at a time. Which is not great when you have many items in the list.

**Additional context**
<img width="201" alt="rerun (1)" src="https://github.com/rerun-io/rerun/assets/136061340/ba954e23-d561-4ecd-82df-09b06e3e2839">

**Comment by abey79** [comment]
This is now addressed by context menu:
- https://github.com/rerun-io/rerun/pull/5205
