### ISSUE TITLE
Rerun streams proxy

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4615]
For some of our users it's very important to have multiple viewers viewing the same stream of logs. 

You can currently achieve this by proxying through a web server (`rerun --web-server`) but this is both awkward (pops up a browser tab) and hard to discover.

I propose we introduce a dedicated proxy mode for the cli to make it easier route log streams between SDKs and viewers.

The simplest thing would be to implement taking only TCP, stdin, and files as input and outputting to stdout, file or websocket. If it can be done with a reasonable amount of effort, outputting to TCP would also be nice.

**Comment by emilk** [comment]
https://github.com/rerun-io/rerun/pull/4834 adds a `rerun --serve` option, easily found with `rerun --help`.

Running just `rerun --serve` will set up a Rerun Server that allows both logging SDK:s and Rerun Viewers (native and web) to connect to it.
