### ISSUE TITLE
Don't use "Store ID" in the UI

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4647]
When hovering a recording, in the recordings list, the on hover UI summary says "Store ID", which is an internal concept that should not be leaked to users. In this case it should instead be called "Recording ID", which matches the parameter `recording_id` in the SDKs.

![Screenshot 2024-01-03 at 10 44 55](https://github.com/rerun-io/rerun/assets/2624717/fbd3c2d7-fc29-4ff7-a548-0cb4b8e53fa4)

**Comment by RohanMishra315** [comment]
Hey @nikolausWest Can I take a look at it ? can you tell where Ui files are ?

**Comment by emilk** [comment]
It's in `crates/re_viewer/src/ui/recordings_panel.rs`:

```
❯ rg "Store ID"
crates/re_viewer/src/ui/recordings_panel.rs
249:            re_ui.grid_left_hand_label(ui, "Store ID");
```

**Comment by emilk** [comment]
I'm fixing this as part of https://github.com/rerun-io/rerun/issues/4649
