### ISSUE TITLE
Heuristics should avoid adding redundant groups

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4651]
The heuristics often add a redundant group that has the same name as the space view. We should avoid introducing groups that don't help navigating the scene.

For example if you open up the "ARkit Scenes" example, you get the following:
![image](https://github.com/rerun-io/rerun/assets/2624717/0a42c14b-cb13-4992-9118-b964d9b2dcec)

The group named "world" here is redundant and should ideally not be added.

**Comment by jleibs** [comment]
This was already fixed as part of: https://github.com/rerun-io/rerun/pull/4618
