### ISSUE TITLE
Formalize specification/documentation of how transforms interact with heuristics and queries

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4655]
There are several open questions at the moment regarding where transforms fit into the heuristic system.
 - Do they only impact "Spatial" views or can they be used to split content in different kinds of views.
 - Is there a mechanism to "query" entities up to the next transform?
 - Is there actually a difference between a "DisconnectedSpace" and a Null "SpatialTransform?"
 - Can a pinhole transform be converted to a rigid transform or does it create a permanent topological disconnect between 2d and 3d spaces.
 - Can 3D content be added to a 2D space without a transform?
 
This would improve clarity for users in issues like:
 - https://github.com/rerun-io/rerun/issues/4465

**Comment by Wumpf** [comment]
We got answers for all of these by now and most of them even coded up:

* Do they only impact "Spatial" views or can they be used to split content in different kinds of views.
   * only impact spatial views. `SpaceInfo` should go away
* Is there a mechanism to "query" entities up to the next transform?
   * transforms propagation is part of general property propagation
* Is there actually a difference between a "DisconnectedSpace" and a Null "SpatialTransform?"
   * Yes. A disconnected space changes the spacial topology. A null spatial transform is handled as identity
* Can a pinhole transform be converted to a rigid transform or does it create a permanent topological disconnect between 2d and 3d spaces.
   * no. It's a permanent topological disconnect 
* Can 3D content be added to a 2D space without a transform?
   * no 

@jleibs plz check over these and close if we're on the same page. If not then this ticket is clearly not done 😄

**Comment by jleibs** [comment]
Agree we're on the same page. Would be great to capture this somewhere durable. Almost like we need a spatial-transform architecture markdown doc.  (Which is where we would also add future notes on semantics for things like time-varying transforms https://github.com/rerun-io/rerun/issues/1522)
