### ISSUE TITLE
Per-log timepoint control / asynchronous “backfilling” of timestamped data in Rust

### ISSUE THREAD

**Issue by kpreid** [rerun-io/rerun#4665]
**Is your feature request related to a problem? Please describe.**
In Rust, I'd like to be able to log data _as if_ it had been logged at a previous time. I have an asynchronous/pipelined task (running a GPU computation that produces data to be logged) which gives me data available later than the end of processing the previous simulation step/frame.

**Describe the solution you'd like**
Add an operation which is analogous to `RecordingStream::log()` except that it accepts an explicit `TimePoint` which could have been previously fetched from `RecordingStream::now()`.

I think the cleanest way to do this without introducing any combinatorial explosion would be to replace the `timeless: bool` accepted by [`log_with_timeless()`](https://docs.rs/re_sdk/0.11.0/re_sdk/struct.RecordingStream.html#method.log_with_timeless) and [`log_component_batches()`](https://docs.rs/re_sdk/0.11.0/re_sdk/struct.RecordingStream.html#method.log_component_batches) — which is itself already a sort of TimePoint override — with an `Option<TimePoint>`. Simple use cases for timelessness can continue using `log_timeless()`, and complex ones can pass `Some(TimePoint::timeless())`.

One complication is how this should interact with the real-time `log_time` and `log_tick`. Probably they should still be written as from the time of actual recording, since they stay more meaningful that way and the application can provide its own timestamps for the virtual ordering.

**Describe alternatives you've considered**
In principle, this is possible in the current API by making appropriate `RecordingStream::set_timepoint()` calls to save and restore time information — however, that requires controlling **exclusive access** to the `RecordingStream` (no other threads/tasks may log anything, at risk of getting the wrong timepoint) which means I have to build a strict wrapper around `RecordingStream` with a mutex. I hope the above solution is much simpler, because anything asynchronous can stick to using explicit timepoints and anything synchronous with the simulation loop doesn't have to care.

An alternative feature would be to add an operation which "clones" a `RecordingStream` but causes it to have separate timepoint state while still writing to the same destination.

**Comment by teh-cmc** [comment]
Thanks for the detailed issue.

This is actually already planned:
- https://github.com/rerun-io/rerun/issues/3841

I've added the `user-request` label over there.
