### ISSUE TITLE
Marking of edited for the blueprint is error prone

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4687]
There are several places where viewport edit-tracking is done manually.

This carries a significant risk that a logic error can result in a never-ending sequence of blueprint re-saving. This can happen if
(1) the edit marking happens without a user interaction
(2) the saved state as a result of the edit does not result in a new state where the edit is no longer marked.

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/2142
