### ISSUE TITLE
egui_tiles GC log warning log spam

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4692]
Steps:

* `cargo rerun ./examples/assets`
* make sure the "hello" recording is selected
* click the reset button
* interact with viewer

causes lots of `[2024-01-05T09:02:31Z WARN  egui_tiles::tiles] GC collecting tiles: [#15151604064148837086]` spam

**Comment by emilk** [comment]
Oh yeah, egui_tiles should only print those warnings in debug builds.

But also, this indicates that we're doing something wrong, e.g. removing a tile from a container without deleting the tile from the `Tiles`
