### ISSUE TITLE
Viewer screenshots include the "image copied to clipboard" toast message

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4694]
On `0.12.0a4` I can no longer get a clean screenshot of the viewer because the screenshot ends up including the message that a screenshot was taken.

![image_copied_to_clipboard](https://github.com/rerun-io/rerun/assets/2624717/5725439e-46e2-482b-9826-48f7626f0edd)

It might be related to that a single screenshot produces three identical toast messages and three identical logs.

<img width="530" alt="Screenshot 2024-01-05 at 10 12 45" src="https://github.com/rerun-io/rerun/assets/2624717/69a67ae7-a44a-4d22-b7c6-5663f3d5dd4c">

![Screenshot 2024-01-05 at 10 16 54](https://github.com/rerun-io/rerun/assets/2624717/ca25789c-a624-43a2-9603-01057ddde837)

**Comment by emilk** [comment]
How are you taking the screenshot? Seems like the command is triplicated

**Comment by Wumpf** [comment]
it is. have a fix!
