### ISSUE TITLE
Show size of RRD in the example page

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4724]
As some of the examples potentially become larger, it's helpful to give users a hint about how much data they are about to download. We should be able to compute the rrd sizes and include that information in the manifest file and show it somewhere in the example summary.

**Comment by jprochazk** [comment]
Right now the example manifest is built separately from the `rrd` files, and this would mean we'd have to always build both together. A solution that wouldn't require any changes to builds/CI would be to use a `HEAD` request to retrieve the size of each `rrd` file and listing that in the UI.

**Comment by emilk** [comment]
doing a `HEAD` to ask for the size sounds like the best solution to me
