### ISSUE TITLE
CMake 'EXISTS' only produces defined behaver for full paths

### ISSUE THREAD

**Issue by KevinGliewe** [rerun-io/rerun#4769]
**Describe the bug**

In [this CMakeLists.txt file](https://github.com/rerun-io/rerun/blob/65b50778ff11a3bf4b1acb7bef49dc8f78292fac/rerun_cpp/CMakeLists.txt#L189)
The CMake `EXISTS` only produces a defined behavior when provided with a full path.

From the [CMake Documentation](https://cmake.org/cmake/help/latest/command/if.html#exists):
> True if file1 is newer than file2 or if one of the two files doesn't exist. **Behavior is well-defined only for full paths**. If the file time stamps are exactly the same, an IS_NEWER_THAN comparison returns true, so that any dependent build operations will occur in the event of a tie. This includes the case of passing the same file name for both file1 and file2.

In my case, CMake picks up some other 'tests' directory inside the build folder and tries to include the subdirectory.
Since I use the rerun_sdk from the zip distribution, the produces an error.

A solution would be to use `${CMAKE_CURRENT_SOURCE_DIR}` to reference the `tests` directory:

```cmake
# -----------------------------------------------------------------------------
# Add tests if they exist (they are not part of the distribution zip).
# Has direct dependency to arrow, so needs to happen last.
if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/tests)
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/tests)
endif()
```

**Rerun version**
0.12.0

**Comment by Wumpf** [comment]
Good catch, didn't know! I see you already linked this in a commit, so looking forward to the PR :)
