### ISSUE TITLE
Fork `arrow2` and get rid of `polars`

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4789]
While we want to migrate from the `arrow2` crate to `arrow` (https://github.com/rerun-io/rerun/issues/3741), it is a big task that we would rather punt on right now. It is technical debt, but the debt is not going to grow significantly. The gains don't justify the potential rabbit hole of paint it could turn into.

One of the major reasons to migrate away from `arrow2` is because `DataType` has a huge overhead, especially when cloned.

We have a PR to fix it (https://github.com/jorgecarleitao/arrow2/pull/1469) but it is unmerged, because `arrow2` in unmaintained.

So: we fork `arrow2` as `re_arrow2`, merge our PR, and solve our immediate memory issue.

Since `polars`  require `arrow2`, we need to stop using it. We only have it for a few tests.

---

We should revisit the migrating away from arrow2 when we start exposing arrow things to the users (e.g. support data queries in the SDK) and/or when we want to interface with a some data frame crate.

**Comment by emilk** [comment]
One question is: what do we do with the tests and examples we have that depend on polars?

**Comment by kylebarron** [comment]
fwiw, Polars also forked arrow2 into polars-arrow, and I don't think it has a dependency on arrow2 anymore

**Comment by emilk** [comment]
We want to get rid of `polars` anyhow because of its huge dependency tree

**Comment by emilk** [comment]
Blocked on landing caching to avoid conflicts

**Comment by emilk** [comment]
Forking of arrow2 happening in https://github.com/rerun-io/arrow2/pull/2

I suggest we use it as `arrow2 = { package = "re_arrow2", version = "0.18" }`. That way we can keep using `arrow2` in the code for a smaller diff.
