### ISSUE TITLE
Asset rerun_cpp_sdk-0.12.0-multiplatform.zip is missing libraries for macOS and windows

### ISSUE THREAD

**Issue by rgolovanov** [rerun-io/rerun#4805]
**Describe the bug**
In assests of 0.12.0 or latest build the archive which suppose to contain multiplatform libraries misses libs for macOS and windows
see https://github.com/rerun-io/rerun/releases/tag/0.12.0

**To Reproduce**
1. Check asset [rerun_cpp_sdk-0.12.0-multiplatform.zip](https://github.com/rerun-io/rerun/releases/download/0.12.0/rerun_cpp_sdk-0.12.0-multiplatform.zip)

**Expected behavior**
All libraries in place

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/14174584/fc0e072b-fc67-4c53-a1b8-57e888d1641c)
but all is in place for earlier releases:
![image](https://github.com/rerun-io/rerun/assets/14174584/b51d2fc3-c8de-44ff-8c0b-197db401596c)

**Rerun version**
0.12.0+

**Comment by Wumpf** [comment]
thanks for reporting this! when testing the RC builds prior to the release the artifact was still correct, something must have broken in our CI. Will have a look asap!

Meanwhile you can use https://build.rerun.io/commit/4fc0c00/rerun_cpp_sdk.zip (which is from 0.12.0-rc6 which is fully compatible with 0.12.0)

**Comment by Wumpf** [comment]
@rgolovanov I uploaded the correct artifacts now to the release 

https://github.com/rerun-io/rerun/releases/download/0.12.0/rerun_cpp_sdk.zip

Keeping this ticket open until we figured out why this happened and how to fix our release scripts
