### ISSUE TITLE
Missing documentation for ImageEncoded and NV12 support

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4820]
The main documentation site is missing entries for `rr.ImageEncoded`. In the Python docs, there is an entry for [rr.ImageEncoded](https://ref.rerun.io/docs/python/0.12.0/common/image_helpers/), but the [rr.FileFormat](https://ref.rerun.io/docs/python/0.12.0/common/enums/#rerun.ImageFormat) doesn't list any formats so it's impossible to find what encoding formats we support, including NV12

None of the documentation of TensorBuffer seems to mention that you can set `kind = "nv12"` either.

**Comment by jleibs** [comment]
Related: https://github.com/rerun-io/rerun/issues/3804
