### ISSUE TITLE
Add contextual menu to blueprint tree for common actions

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#4823]
To make it easier to add blueprint content in the UI, we should introduce context menu on right click in the blueprint with options:

#### Single selection 
- Add View
- Add Container
- Put in new container
- Hide
- Remove

#### Multiple selections
- Put in new container
- Hide
- Remove

#### Single selection 
- Add Entity
- Put in new a container
- Hide
- Remove

#### Multiple selections
- Put in new a container
- Hide
- Remove

### Views and containers selected
(same if all entities of a selected view are selected)
- Put in new container
- Hide
- Remove

### Entity is selected
(Same for single or multiple entities)
- Add to new view
- Hide
- Remove

### Entities and views and/or containers selected
- Hide
- Remove

**Comment by abey79** [comment]
Closing this one in favour of finer grained issues with the remaining items.
