### ISSUE TITLE
Improve X-axis ticks spacing in timeseries space views

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4828]
<img width="340" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/8fb13a29-2d28-45be-a68d-2ef193c440b3">

that X axis ☝🏻 is way too messy

**Comment by emilk** [comment]
This might be good to tackle early, since it may require tweaks to `egui_plot`

**Comment by emilk** [comment]
* https://github.com/emilk/egui/pull/3896 makes this fixable in the next egui update

**Comment by seongs1024** [comment]
![image](https://github.com/rerun-io/rerun/assets/56729421/4709de4e-3a4e-4176-a3f0-38094c85de20)

Hope that it is applicable to y-axis too!

**Comment by emilk** [comment]
@seongs1024 thanks for pointing out that problem - it will be fixed in
* https://github.com/emilk/egui/pull/3921
