### ISSUE TITLE
Fix release CI failures

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#4861]
* https://github.com/rerun-io/rerun/pull/4837

The 0.12.1 release build has two failures:

* the latest branch failed to update (https://github.com/rerun-io/rerun/actions/runs/7558960349/job/20582843079)
* the post-release version bump failed https://github.com/rerun-io/rerun/actions/runs/7558960349/job/20582842767

This resulted in:

* Having to manually create a 0.12.1 tag
* Having to manually update the `latest` branch
* No instructions posted in the GitHub PR about next steps (e.g. how to do a GitHub release)
* https://github.com/rerun-io/rerun/releases/download/0.12.1/rerun_cpp_sdk.zip was never uploaded
* No assets uploaded to https://github.com/rerun-io/rerun/releases/tag/0.12.1

**Comment by jleibs** [comment]
Related: https://github.com/rerun-io/rerun/issues/4763
