### ISSUE TITLE
`setup_dev.sh` issue with `cargo install typos-cli`

### ISSUE THREAD

**Issue by ricardonunosr** [rerun-io/rerun#4907]
**Describe the bug**
Running the command `./scripts/setup_dev.sh` causes error while installing `typos-cli`.

`typos-cli` need `rust 1.75.0` since version `1.17.0` of `typos-cli`
<img width="942" alt="image" src="https://github.com/rerun-io/rerun/assets/47164756/136f9f4d-b62c-432a-9e3d-8c0fa4c09d1f">

Some ideas:
 - the `setup_dev.sh` use the pixi tool. Use `pixi shell` to have all of rerun environment ready
 - lock the version in `Cargo.toml` use `--locked` in the script

**To Reproduce**
1. Run `./scripts/setup_dev.sh` on a machine without `typos-cli`
2. Error occurs while compiling crate

**Expected behavior**
Expect script to install dependencies without errors

**Screenshots**
![image](https://github.com/rerun-io/rerun/assets/47164756/d97c629f-393f-4eaa-ba51-d4f5e3a54bdc)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3.1

**Comment by Wumpf** [comment]
Typos is already part of the pixi.toml, so this should be removed from the script as we're phasing them out, see

* #4170
