### ISSUE TITLE
Fix C++ contributor ci

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4922]
For some technical reasons we have a separate external-contributor ci setup which doesn't allow as-easy access to secrets etc. that we use for publishing. Currently the C++ part of this ci doesn't work at all which is a problem now that we're getting more and more contributions.

**Comment by Wumpf** [comment]
Related:
* #1994

**Comment by emilk** [comment]
We should test if `rerun-bot: full-check` works for contributor PRs

**Comment by Wumpf** [comment]
Piggybacked ci fixes in https://github.com/rerun-io/rerun/pull/6053
`rerun-bot: full-check` isn't tested yet

**Comment by Wumpf** [comment]
calling this still done, rerun-bot handling is something else
