### ISSUE TITLE
Loading data with more than 1 space view deadlocks if `RAYON_NUM_THREADS=2`

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4939]
This is true for both our latest release (`0.12.1`) and our latest `main`: `RAYON_NUM_THREADS=2 rerun plots.rrd` successfully starts a viewer and loads the data, but then deadlocks.

I think this might possibly hide another deadlock in the query cache, but we need to fix this one first to know for sure.

Putting on high priority as this might hide something very very wrong.

https://github.com/rerun-io/rerun/assets/2910679/e492d407-8657-45b7-b25e-ab7fb3ee5f30

**Comment by Wumpf** [comment]
Tried with both caching enabled and disabled, both from startup or changed at runtime and it doesn't repro for me so far

**Comment by teh-cmc** [comment]
This is caused by external loaders, removing them all from my PATH fixes the issue -- something is blocking and/or waiting for another task on the compute threadpool?

No idea why the number of space views seemed to affect my earlier repro? We'll see what happens when I fix this.
