### ISSUE TITLE
Tracking issue: future time-series and plotting features

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#4945]
- support for data aggregation (mean/std, min/max, percentiles, etc.) (future)
  - [x] define aggregation time window
  - [ ] styles: error bars, error bands,  one line per percentile, etc. 

#### Layout/synchronisation

These stories are about making it easy to layout and synchronise multiple plot space views. Things that we want:
- synchronise y axes bounds between plots
- synchronise visible time range between plots
- synchronise zoom/scroll location between plots

Possible avenues to address that:
- Propagate properties from the top of the container hierarchy (instead of "only" from the space view). That would naturally allow shared properties (e.g. visible time range)
- Container aware synchronisation (vertical -> sync VH / horizontal -> sync Y bounds / grid -> both).
- Make it possible to have multiple plots in a single space view (aka. `plt.subplot()`), where all plots would have their axis implicitly synchronised.

**Comment by Wumpf** [comment]
We have aggregation by now

There's other tickets tracking various style aspects:

axis synchronization is handled by
* https://github.com/rerun-io/rerun/issues/2240
* https://github.com/rerun-io/rerun/issues/294
