### ISSUE TITLE
Deadlock with primary caching is on

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4947]
I can consistently reproduce a dead-lock on main (as of 4371783) that happens only with primary caching on.

Repro step:
- reset the blueprint:
![image](https://github.com/rerun-io/rerun/assets/49431240/04a25cff-5c2e-41e4-89cb-9bea2fe7b5cc)

- left space view over middle one:
![image](https://github.com/rerun-io/rerun/assets/49431240/12eeec99-5dfb-4970-adbd-ea3bf1d05254)

Deadlock occurs then.

Alternative repro:
- start with primary caching off
- enable primary caching

=> deadlock immediately occurs

Stack trace:

<img width="1160" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/28a11e6d-c7a7-478f-bcf3-e95bee653f7a">

Repro RRD (800+MB, on private slack):
https://rerunio.slack.com/archives/C041NHU952S/p1706543181xxxx99?thread_ts=1706204242.101919&cid=C041NHU952S

**Comment by abey79** [comment]
Another suspicious thread:
<img width="1173" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/8cda02a4-22ec-4aaf-8d0d-1859e5a8d8bd">

**Comment by abey79** [comment]
And that error seems to popup shortly after the deadlock: 
<img width="525" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/189d14ce-ebd6-4953-9292-8327f688fff8">

**Comment by abey79** [comment]
With `RAYON_NUM_THREADS=1` or `RAYON_NUM_THREADS=2`, the deadlock doesn't happen. With `RAYON_NUM_THREADS=3` it happens.

**Comment by teh-cmc** [comment]
Reproduced together by duplicating a view a bunch of times
