### ISSUE TITLE
Add/remove entity and query editor improvement

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#4962]
This issue is about the minimal set of UI tweaks to bring the UI around Space View content (Add/remove entity, query dialog box, etc.) to a releasable state.

Always:
- move the "Clone SV" button to a different line, after the query editor if visible

When the query DSL feature flag is OFF:
- back to "Add/remove entities" button label + adjust hover text accordingly

When the query DSL feature flag is ON:
- move "?" hover help to to field title hover text?

**Comment by abey79** [comment]
@nikolausWest here is a proposal with mock-ups

https://www.figma.com/file/F02bljLYwuUy1ymlIn3Du0/Selection-panel-%2F-query-editor-%2F-release-0.13-fixup?type=whiteboard&node-id=0%3A1&t=KAckCAniXIOBhpl7-1

**Comment by nikolausWest** [comment]
I added some comments (mainly copy) in the mockup but looks good!
