### ISSUE TITLE
Cloning a space view doesn't clone all of its configuration state

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4977]
- Have e.g. a 3D point cloud view
- Set visible time range to `-inf:+inf`
- Clone the view -> the cloned view is back to default settings (`LatestAt(cur_frame)`)

**Comment by jleibs** [comment]
Note that this same problem applies to child entity-properties, component overrides, etc.

**Comment by abey79** [comment]
#4978 partially addresses this by properly cloning the entity properties.

**Comment by jleibs** [comment]
Adding to 0.13 because the new legend / axis config depend on it.
