### ISSUE TITLE
scalar's default visible range prints incorrect range

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#4986]
Looking at the sin/cos lines in the plots example.
The space view says:
![image](https://github.com/rerun-io/rerun/assets/1220815/aa7fc22b-2946-4421-8dfe-22f77452db5c)

But clicking on one of the lines it claims there's thing visible:
![image](https://github.com/rerun-io/rerun/assets/1220815/91feb2dd-6c65-4058-bcd3-9e4e8c2173ce)
Also the greyed text is incorrect? This applies only to this one now

**Comment by abey79** [comment]
I believe this is not a UI bug. The accumulated entity properties seem to be erroneous for those entities.

cc @jleibs

**Comment by abey79** [comment]
> Also the greyed text is incorrect? This applies only to this one now

Is that true? I didn't think so.
