### ISSUE TITLE
Drag-n-drop issues with space view

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#4996]
Some issues I've encoutered while drag-n-dropping stuff around.

Much easier to screencast than to describe with words: see below.

#### Issue 1

https://github.com/rerun-io/rerun/assets/2910679/26e0e13d-562d-4520-82a5-2b6f7459aa76

#### Issue 2

https://github.com/rerun-io/rerun/assets/2910679/58591738-90c1-4ab7-92b5-581365d4e91b

**Comment by emilk** [comment]
This is the text that pops up:

> [2024-02-05T14:08:04Z ERROR re_viewport::viewport] Visualizers for space view Placeholder("reconstruction") haven't been executed prior to display. This should never happen, please report a bug.

**Comment by Wumpf** [comment]
The issue with (1) is likely that egui_tiles doens't report a view that we then unexpectedly draw: we first ask egui_tiles what views are going to be there, execute all visualizers for all spaces views in parallel, and _then_ draw egui_tiles. While doing so we rely on the results from the previously execueted visualizers. If that didn't happen that error shows up
