### ISSUE TITLE
Store non-deterministically returns ComponentNotFound for new MarkerShape

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5005]
This specifically impacts https://github.com/rerun-io/rerun/pull/5004

Can repro using the branch (`jleibs/point_markers`) and the code:
```
import math

import rerun as rr

rr.init("rerun_example_scalar", spawn=True)

for step in range(0, 64):
    rr.set_time_sequence("step", step)
    rr.log("scalar/cos", rr.archetypes.Scalar(math.cos(step / 10.0)))
    rr.log("scalar/sin", rr.archetypes.Scalar(math.sin(step / 10.0)))
```

Sometimes everything works as expected:
![image](https://github.com/rerun-io/rerun/assets/3312232/6ca4a5fb-28f0-4e6e-8bcb-227d9ce40fac)

But sometimes we get an error:
```
[2024-02-01T21:28:25Z ERROR re_viewport::system_execution] Error executing visualizer "SeriesPoint": Could not find component: rerun.components.MarkerShape
```
and the visualizer refuses to show the PointSeries:
![image](https://github.com/rerun-io/rerun/assets/3312232/c51b526d-f44e-41a3-b900-120e66b9b889)

Appears unrelated to the python logging since you can save an RRD file and reload it. Sometimes it will load properly, sometimes MarkerShape won't work.

**Comment by jleibs** [comment]
This appears this is caching related as disabling primary_caching appears to avoid the issue.

**Comment by teh-cmc** [comment]
I wouldn't be surprised if that's another bug I introduced in the reentrancy patch... :unamused:  looking.
