### ISSUE TITLE
Endless ui refresh

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5018]
Reported by @abey79 

Something is calling `request_repaint` way too often.

Needs a repro.

* Could be https://github.com/emilk/egui/pull/3930
* This would help diagnose it: https://github.com/emilk/egui/issues/3931

**Comment by abey79** [comment]
repro on main:
- `just py-build`
- `python examples/python/face_tracking/main.py`
- let the script run for a few seconds then kill it
- reset viewport

=> no endless UI refresh

mess just a little bit with the space view:
- move the 3D space view tile around (tab / un-tab it)
- zoom/scroll  the 3D space view a little bit

After a few of those ops, the infinite UI refresh triggers.

**Comment by abey79** [comment]
Still using the face tracking example, when setting the blueprint as follows and restarting, I can trigger the infinite refresh by just rotating/zooming the 3d view—no tile dragging needed.

<img width="2109" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/86269df0-78fa-4ad2-9138-32cf4dff01d0">

**Comment by jleibs** [comment]
This issue is still affecting head of main.  It doesn't impact all scenes, but for example in `arkit_scnes` the scene constant repaints.

**Comment by emilk** [comment]
@jleibs you just need to uncheck this checkbox:

![image](https://github.com/rerun-io/rerun/assets/1148717/6e9052bc-dd4c-4a03-9ae7-da92337c00fc)

It is off by default, but you ran an earlier version on `main` where it was on by default, and that is now saved. Or just reset your Rerun.

In other words: this won't be a problem for our users.

**Comment by emilk** [comment]
nope, wrong again
