### ISSUE TITLE
Pinhole image plane distance defaults to 0

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#5060]
**Describe the bug**
The pinhole frustum is by default not visible since the distance is set to 0.

**To Reproduce**
```python
import rerun as rr
import numpy as np

rr.init("test", spawn=True)
rr.log("world/points", rr.Points3D(np.random.rand(500,3)))
rr.log("world/image", rr.Pinhole(focal_length=3, width=3, height=3))
rr.log("world/image", rr.Image(np.random.rand(3, 3, 3)))
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Rerun version**
> rerun_py 0.13.0-alpha.4 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.13.0-alpha.4 e7325d4, built 2024-02-06T10:51:01Z

**Comment by jleibs** [comment]
Bisected to: https://github.com/rerun-io/rerun/commit/c73f9f6a4135718de5c21e72ed6fb03ff2eca638
