### ISSUE TITLE
Can't resize space views

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#5061]
Open https://app.rerun.io/commit/b9cd458/index.html and go to any example.

https://github.com/rerun-io/rerun/assets/2624717/95fdf3f2-1caf-414d-b3e5-e44f0ecda4b8

**Comment by roym899** [comment]
Still seems broken for me in the prerelease and when building from main.

**Comment by emilk** [comment]
Works for me. Are you sure @roym899 ? Maybe try `rerun reset` and see if it helps?

**Comment by roym899** [comment]
I think I installed the release candidate on pypi instead. Pointing it explicility to the wheel does the trick. 

Not sure what I did wrong before when building from source.
