### ISSUE TITLE
Strange blueprint reordering after drag and drop

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#5081]
What: After dragging and dropping a space view in the blueprint, it seems to reorder the other items. 

How to reproduce:
`just rs-plot-dashboard --num-plots 12 --num-series-per-plot 5 --num-points-per-series 5000 --freq 1000 --connect`

https://github.com/rerun-io/rerun/assets/2624717/c07b9750-ee48-456f-9018-37a43a453f64

**Comment by abey79** [comment]
Yet another manifestation of us using egui_tiles as an application layer data structure. I'll check if there is a quick fix.
