### ISSUE TITLE
Selecting data blindly queries and deserializes it (uncached)

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#5084]
Looking at a big line cloud with caching enabled, everything is fine:
![image](https://github.com/rerun-io/rerun/assets/2910679/6a89abdf-104d-4e41-99f8-4c558cdcdd2f)

But then as soon as you select something:
![image](https://github.com/rerun-io/rerun/assets/2910679/e1ff9543-48b9-4032-996a-01523286985f)

**Comment by teh-cmc** [comment]
Things get even far far worse if you select the strips themselves.
![image](https://github.com/rerun-io/rerun/assets/2910679/a68ce4ef-419e-42e0-99fe-3e36b4708309)

**Comment by emilk** [comment]
Ultimately we should architecture the viewer in a way that it is impossible to use the store without going through the cache

**Comment by teh-cmc** [comment]
This is done -- there is no uncached APIs anymore.
