### ISSUE TITLE
Grey out groups without visualizers and don't default-expand them

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#5085]
We now also show you entities that can't be shown in a space view (or aren't shown by default because we didn't pick a visualizer for you). This is nice, but to make it look nicer we should also grey out groups that only have such entities and don't expand them.

here's an example of a 2D image view with an image entity and two entities with tensors:

![image](https://github.com/rerun-io/rerun/assets/1220815/9e7a86d1-0189-4264-8c5d-68271f4e5143)

**Comment by jleibs** [comment]
Group concepts going away in: https://github.com/rerun-io/rerun/issues/4899 closing this.
