### ISSUE TITLE
Compile times

### ISSUE THREAD

**Issue by v-morlock** [rerun-io/rerun#5095]
**Describe the annoyance**
Compile times for rerun are rather long right now. Even when disabling most of its features, its compile-time really adds up and i'm wondering whether things like egui really need to be compiled when we're only using the sdk to log data..

We have a medium-size rust application and in the compile-timings, the crates with the longest compile-times all seem to be rerun-related.

This is how we add rerun in our cargo.toml
rerun = { version = "0.12.1", default-features = false, features = ["sdk"] }

**To Reproduce**
Install rerun, compile with `cargo build --timings`

**Screenshots**
<img width="1636" alt="image" src="https://github.com/rerun-io/rerun/assets/18666999/d47da3fc-98b8-4ecb-83ac-9d376201e2ad">

**Comment by emilk** [comment]
I agree completely. However, I think this existing issue covers it
* https://github.com/rerun-io/rerun/issues/4788

I'll add some more notes on that one shortly.

**Comment by Wumpf** [comment]
@emilk something strange is going on there though. Why are we building with egui when not including the viewer itself

**Comment by Wumpf** [comment]
ah you already noted that on the other issue now 👍

**Comment by emilk** [comment]
…and solved it: https://github.com/rerun-io/rerun/pull/5099
