### ISSUE TITLE
Bad SpaceView heuristics

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5125]
structure_from_motion/colmap has a heuristic issue.
Resetting fixes it, but then closing and reopening the .rrd again brings us back to the bad state again:

![image](https://github.com/rerun-io/rerun/assets/1148717/d6a1c4b0-6103-4cd0-8c9e-b7e31479e990)

**Comment by emilk** [comment]
The resetting -> closing and reopening might be a separate issue:
* https://github.com/rerun-io/rerun/issues/5131

**Comment by Wumpf** [comment]
@emilk please check if this is fixed by
*  #5164

**Comment by Wumpf** [comment]
we haven't seen this during testing of the final 0.13 version anymore
