### ISSUE TITLE
"Reset blueprint" doesn't save a new blueprint

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5131]
This is confusing. If you load an .rrd with a bad blueprint file, and you hit "Reset blueprint", then close the .rrd and open it again, the bad old blueprint is back. The "Reset" doesn't take.

**Comment by emilk** [comment]
I'm not sure what happened. I can't reproduce this easily now, so it is some weird corner case.

**Comment by Wumpf** [comment]
closing it until we get hold of it again
