### ISSUE TITLE
rerun_viewer wont launch again if exited while still in Fullscreen

### ISSUE THREAD

**Issue by Omotoye** [rerun-io/rerun#514]
👍

**Describe the bug**

If I close the rerun viewer while still in fullscreen by using Alt+Tab to navigate  to the terminal, I get the error message in the image below the next time I try to open the rerun viewer and it doesn't work again until I delete the folder in this path `~/.local/share/rerunviewer/`

**To Reproduce**
1.  Put rerun viewer on fullscreen
2.  Close rerun viewer from the terminal while it's still in fullscreen

**Screenshots**

![rerun error](https://user-images.githubusercontent.com/67521465/206793648-4254a62a-359e-467b-a140-6eadcc797e66.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - WSLg (Ubuntu 22.04)
 - Screen Resolution: 2256 x 1504

**Comment by emilk** [comment]
@Omotoye I'm gonna close this and hope that recent changes to `eframe` (including a `winit` update) has solved the issue.

If you are still having a problem on `rerun main`, please re-open this issue!

**Comment by Omotoye** [comment]
I just checked it and the problem is **solved**. I installed it with the pip installation package and tried the cube example. After putting it on fullscreen and stopping it, on the relaunch, it didn't have the weird behavior it used to have.

**Comment by Wumpf** [comment]
awesome, thanks for checking on this @Omotoye
