### ISSUE TITLE
Logging images to different child-of-root entity paths should result in separate SpaceViews

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5145]
This is a pretty important heuristic. Logging to `/img_left` and `/img_right`, we should get two space-views, not one.

Currently our VRS example looks like this by default on 0.13:

![image](https://github.com/rerun-io/rerun/assets/1148717/62185770-adc4-492b-b525-48c5acab768b)

**Comment by nikolausWest** [comment]
I still don't think it should be related to the root at all. The heuristic we want:

- Heuristics never overlap RGB images on RGB images
- Heuristics never overlap Depth images on Depth images
- Heuristics never overlap Segmentation images on Segmentation images

For the special case where users do want multiple same-typed images overlapped, they can set it up manually
