### ISSUE TITLE
Selecting vertical/horizontal/grid containers within a vertical/horizontal/grid container should draw a box when selected

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#5174]
<img width="1748" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/9a040053-8031-4d5f-91ad-7b482bceab2d">

In the above scenario I'd expect a blue box around both space views in the vertical container since it was selected (and a grey one on hover, in accordance with out highlighting colors).

<img width="1734" alt="Screenshot 2024-02-12 at 14 19 52" src="https://github.com/rerun-io/rerun/assets/1220815/210a230e-cbca-4ea7-97bc-15f2d82c7bff">
(this screenshot is lacking selection here, this should ofc only show when still selected)

This would help localizing where's what in the viewport.

**Comment by emilk** [comment]
First step:
* https://github.com/rerun-io/rerun/pull/6596
