### ISSUE TITLE
Timeseries: setting [0,0] as Y axis range panics

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5239]
Typing zero here leads to a crash:

<img width="780" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/cfe948e9-09da-4304-8b53-339ffa821eb9">

That is easy to come by if the intension is to type e.g. 0.5

<img width="700" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/0c370d96-a4d7-41b3-8d16-07de0c4bdccd">

**Comment by Wumpf** [comment]
egui didn't get released but we got that fix over by now
