### ISSUE TITLE
`Rerun ERROR: Shape must be rank 2.` when logging depth image with shape (H, W, 1) from C++

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#5254]
**Describe the annoyance**
Minor annoyance: when logging a DepthImage with a tensor shape of length 3 (such as {height, width, 1}) Rerun reports

> Rerun ERROR: Shape must be rank 2.

on every log call; however, the depth image shows up nonetheless.

This is a little annoying, because the same code to log an Image will not work when logging a depth image, i.e., you need some separate logic to get the tensor shape for a depth image compared to a normal image.

In Python there is no equivalent warning when logging a DepthImage with shape (H, W, 1).

**Workaround**
```C++
rerun::DepthImage({img.rows, img.cols}, rerun::TensorBuffer::u16(img))
```
instead of 
```C++
rerun::DepthImage({img.rows, img.cols, img.channels()}, rerun::TensorBuffer::u16(img))
```

**Expected behavior**
Accepts tensor shapes of rank 3 as long as the last dimension has size 1.

**Comment by emilk** [comment]
I agree that "rank" is a confusing term. I suggest we replace "rank N" with "N-dimensional" in our language. In this case, the error message should be something like "The tensor must be 2-dimensional, but got shape 800x600x1"
