### ISSUE TITLE
New options for setting blueprint: "force", "load if unset", "set default"

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5298]
Builds on top of:
 - https://github.com/rerun-io/rerun/issues/5297

Now that a blueprint can be set at any time, we want some minimal control for the SDK for how this behaves.

Force and load-if-unset are mostly trivial and could likely be added to the "ActivateBlueprint" message proposed in (https://github.com/rerun-io/rerun/issues/5297)

"Set default" includes some extensions to the StoreHub.
 - The basic idea is that the store-hub will store **two** blueprints per app-id.  One is the currently active blueprint, where all user edits are applied. The other is our first implementation of a "snapshot" as the MVP of a single "default" snapshot per blueprint.

A blueprint sent from the SDK will have the option to only replace the "default" snapshot, and a new variant of the "Reset blueprint" action will be to reset to the blueprint to the (SDK-provided) default as opposed to the (Heuristic provided) default.

### Consideration
If putting this data in the "ActivateBlueprint" message, we should be careful about whether that message is baked into the stream or not when saving a blueprint. If a user is opening a blueprint from file it might be weird for the file being opened to make the determination as to if the behavior is force / load if unset/ or set default.

**Comment by emilk** [comment]
Very related to
* #5629

**Comment by jleibs** [comment]
Proposal for 0.15: Always use "load if unset + set default"

It's 1 click for a user to reset.

**Comment by jleibs** [comment]
Considering this done as of: https://github.com/rerun-io/rerun/pull/5678
