### ISSUE TITLE
Context menu: hide/don't show tooltips while a context menu is visible

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5310]
Don't show (or hide if already shown) hover tooltip when displaying a context menu. This is currently very annoying.

To be solved in egui?

![image](https://github.com/rerun-io/rerun/assets/49431240/bcd56a5c-fce6-4075-be74-f45e75495e43)

**Comment by abey79** [comment]
egui fix in https://github.com/emilk/egui/pull/4138

**Comment by emilk** [comment]
nice one
