### ISSUE TITLE
Context menu: reword "Add to new container" action

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5311]
For a single item: "Wrap in new container"
For multiple items: "Move items to new container"

**Comment by abey79** [comment]
Both of the copy above tend to be on the verbose side. In #5392, the copy changed to "Move to new container" (for both single and multi-selection). @nikolausWest ok for you? I can do "Wrap to new container" for a single selection, but I think it'd be kind of weird to have a very different term used for mostly the same thing. 

![Image](https://github.com/rerun-io/rerun/assets/49431240/ffe615e5-d516-45dc-9ec1-3229e20b20f4)

**Comment by nikolausWest** [comment]
Fine by me (at least until we come up with something better 😛)
