### ISSUE TITLE
Hard to navigate Visible History feature

### ISSUE THREAD

**Issue by karimo87** [rerun-io/rerun#5315]
**Describe the annoyance**

I want to use the visible history feature. When I try to set up my override I am first struggling with the overlaid information blocking out the fields I am interested in. Once I can see the "current time with offset" it takes time for me to figure out that the set value is behind the cutoff on the right-hand site. 

This might be my setup, but I have replicated this on the web with both Chrome and Safari.

**To Reproduce**
1. Hover Visible History drop-down to see how overlay is blocking background info
2. Select override and see where the offset value field ends up

**Expected behavior**
I'd expect to see the field for setting the offset value when choosing that option.

I'm not sure what would be better behaviour for the overlay.

**Screenshots**

https://github.com/rerun-io/rerun/assets/6584154/b4a09ac0-62e1-4e2e-a41f-efa9314c9a3d

**Comment by emilk** [comment]
increasing the default tooltip delay seems like a good start
