### ISSUE TITLE
Tracking issue: Add web-viewer to examples and docs

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5316]

**Comment by jprochazk** [comment]
Some potential steps:
- Add `blueprint_url` query param to web
- Deprecate `url` query param, replace with `recording_url` or similar
- Fix the styling issue where the viewer tries to take over the whole screen with `position: absolute`
- Save all recording and blueprint files from all of our examples (including code-examples` snippets)

**Comment by jprochazk** [comment]
We decided not to have the viewer inline for now, but link to it instead. The `data-inline-viewer` is repurposed as a means to transform a screenshot to an `app.rerun.io` example link.

Remaining work:
- https://github.com/rerun-io/rerun/pull/5618
