### ISSUE TITLE
New clients do not receive data in Web-Viewer mode after dropping old messages

### ISSUE THREAD

**Issue by Charlie-AuZone** [rerun-io/rerun#5344]
**Describe the bug**

https://github.com/rerun-io/rerun/assets/139271810/1b016b74-ef55-45d4-889e-c44192cf08d0

After a while, new clients fail to recieve data in server mode. This happens once the memory limit is reached and some data is dropped.

**To Reproduce**
```python
import rerun as rr
import numpy as np
import time
rr.init("rerun_example_my_data", spawn=False)
rr.serve(open_browser=True, server_memory_limit="1GB")

imarray = np.random.rand(540,960,3) * 255

while True:
    rr.log("test", rr.Image(imarray))
    time.sleep(0.01)
```
1. Run the above code
2. Observe the Rerun screen in the browser running correctly of an image with random noise.
3. After the terminal says `Memory limit (954 MiB) exceeded. Dropping old log messages from the server. Clients connecting after this will not see the full history`, open a new tab to the same URL: [http://localhost:9090?url=ws://localhost:9877](http://localhost:9090?url=ws://localhost:9877)
4. Observe that in the new tab, no data is seen, but in the original tab, data is still being streamed in.

**Expected behavior**

On the new tab, older logs are lost but new data is streamed in.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Rerun version**
`rerun_py 0.14.0 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-pc-windows-msvc release-0.14.0 0c723a8, built 2024-02-28T14:53:55Z`

**Additional context**
Also occurs in the Rust program, but a Python replication of the bug was included here for a minimal reproducible sample.

**Comment by edwardstevenw** [comment]
I also experience this behavior. I am running `rerun --serve --server-memory-limit 100MB --memory-limit 100MB` and I open the url to view the logged data. Whenever messages have been dropped, I cannot reconnect to the server again. 

Also if I may say another thing I experienced which is related to the memory limit, is that --memory-limit does not take effect for web viewer client. It defaults to 2.3GB, not 100MB which I expected. I will create an issue for this separately if I have to, thank you!
