### ISSUE TITLE
Visual glitch in blueprint tree UI (hidden items) and in rerun menu

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5352]
Bad background for icons when the item is hidden:

<img width="213" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/b0eb0951-a9eb-43f1-96bb-22ec226455c7">

Introduced in:
- https://github.com/rerun-io/rerun/pull/5219

**Comment by emilk** [comment]
I fail to reproduce. If I hover an item it looks fine:

![image](https://github.com/rerun-io/rerun/assets/1148717/417f542c-53ba-4a3d-9f42-c62a12766797)

**Comment by abey79** [comment]
@emilk my bad, I forgot to specify that this happens only when the item is hidden

**Comment by abey79** [comment]
Likely for the same reason, the rerun menu has the same glitches:
<img width="257" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/902b2c8e-551c-44fc-81b4-21f14c6248a3">

**Comment by Wumpf** [comment]
the later is 
* #5368

**Comment by emilk** [comment]
Duplicate of [#5368](https://github.com/rerun-io/rerun/issues/5368)
