### ISSUE TITLE
Blueprint tree: provide feedback when a data result not visualisable

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5410]
Currently, if a data result is not visualisable, it is displayed as it it was hidden (see the tensor with 3d points in screenshot).

We should clearly indicate that that this data result is not visualisable in the context of this space view:
- don't display the eye icon on hover (it is not relevant)
- different styling?
- tooltip? 
- note in the label?

<img width="1406" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/604cebd7-bb55-4fda-9ea0-548309efc5ec">

**Comment by emilk** [comment]
Requires some design
