### ISSUE TITLE
Timeline cursor goes off limit

### ISSUE THREAD

**Issue by 02alexander** [rerun-io/rerun#5418]
**Describe the bug**
If I drag the timeline cursor to the left I loose the grip around the cursor and it's gets stuck outside the interval. I can also drag it outside to the right but then it automatically jumps backs when I release so that's not as bad.

![rerun-issue](https://github.com/rerun-io/rerun/assets/28707703/214c691f-6ccc-469f-b331-252725a9210b)

**To Reproduce**
1. Open viewer
2. Go into a recording (in the video, the helix example)
3. Move timeline cursor far to the left or right

**Desktop (please complete the following information):**
 - NixOS with KDE desktop using X11 display server 

**Rerun version**
I tested on two versions and the problem occur in both.
`rerun-cli 0.15.0-alpha.2 [rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball), LLVM 17.0.6] x86_64-unknown-linux-gnu`
`rerun-cli 0.14.1 [rustc 1.76.0-nightly (3a85a5cfe 2023-11-20), LLVM 17.0.5] x86_64-unknown-linux-gnu`

**Comment by teh-cmc** [comment]
Well, this is a far as I can tell fixed on `main`, somehow.

Whoever is responsible, we thank you for your service.



![Image](https://github.com/rerun-io/rerun/assets/2910679/7dc59f0e-dee9-4874-a3d7-7004a23ee2e9)
