### ISSUE TITLE
Shorten and unify in-example description markdowns

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#5440]
The in-app markdown description can be a great way to share some context about what you're looking at for someone that opened an example without a deep understanding of what that is. It isn't a good place for a tutorial / deeper description since the in-app markdown documents provide a much worse reading experience than our website. 

Example:
![Screenshot 2024-03-08 at 11 28 30](https://github.com/rerun-io/rerun/assets/2624717/65f8d53b-75d1-4184-9726-e29c69ea2bfc)

We should unify these in app markdown descriptions to:

- [ ] Be much shorter and just give enough information to orient someone who opened an example on app.reru.io without much context.
  - [ ] They need to know that this is an example recording of X, built using Rerun.
  - [ ] It should link to some key pieces of data in the recording
  - [ ] Link to documentation and the source code
- [ ] Each example we include on app.rerun.io should have a markdown description

**Comment by emilk** [comment]
My work-list:

* [x] arkit_scenes
* [x] detect_and_track_objects
* [x] dicom_mri
* [x] dna
* [x] human_pose_tracking
* [ ] nuscenes
* [ ] open_photogrammetry_format
* [ ] plots
* [ ] raw_mesh
* [ ] rgbd
* [ ] rrt-star
* [ ] segment_anything_model
* [ ] structure_from_motion
