### ISSUE TITLE
Crashes when trying to use rerun from python and c++ at the same time.

### ISSUE THREAD

**Issue by 02alexander** [rerun-io/rerun#5442]
**Describe the bug**

I'm trying to use c++ from python and use rerun logging in both languages at the same time. I am currently doing this using pybind11 but when I import the c++ module before importing rerun I get the following output
```sh
./main.py
free(): invalid pointer
[1]    130434 IOT instruction (core dumped)  ./main.py
```

main.py:
```py
import cpp_logging
import rerun as rr
```

The c++  code:
```cpp
#include <rerun.hpp>
#include <rerun/demo_utils.hpp>
#include <iostream>
#include <pybind11/pybind11.h>

using namespace rerun::demo;

void log_from_cpp() {
    rerun::RecordingStream& rec = rerun::RecordingStream::current();
    std::vector<rerun::Position3D> points = grid3d<rerun::Position3D, float>(-10.f, 10.f, 10);
    std::vector<rerun::Color> colors = grid3d<rerun::Color, uint8_t>(0, 255, 10);

    rec.log("my_points", rerun::Points3D(points).with_colors(colors).with_radii({0.5f}));
    std::cout << rec.is_enabled() << std::endl;
}

PYBIND11_MODULE(cpp_logging, m) {
    m.def("log_from_cpp", &log_from_cpp);
}
```

What's especially weird is that if I change the order of the imports to 
```py
import rerun as rr
import cpp_logging
```
it doesn't immediately crash anymore. But if I try to run the c++ code
```py
import rerun as rr
import cpp_logging
cpp_logging.log_from_cpp()
```
I get 
```sh
[1]    132230 segmentation fault (core dumped)  ./main.py
```

**Expected behavior**
Ideally I should be able to initialize rerun from the python side and use `rerun::RecordingStream::current()` from c++ to get the recording I initialized in python. But no matter what It shouldn't chrash with segmentation fault or IOT instruction.

**Backtrace**

**Desktop (please complete the following information):**
 - OS: NixOS on the unstable channel 

**Rerun version**
rerun_py 0.14.1 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.14.1 74f1c23, built 2024-02-29T11:00:55Z

**Additional context**

**Comment by Wumpf** [comment]
@02alexander does this still repro for you? If so, can you please attach a debugger and provide a callstack?

**Comment by Wumpf** [comment]
Let's consider it fixed until proven otherwise then!
