### ISSUE TITLE
Card based example gallery in the application welcome screen

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#5452]
New design here: https://www.figma.com/file/U85f12k8Tw2ArD4N61cdtQ/Marketing-material?node-id=2272%3A42422

**Comment by martenbjork** [comment]
The latest design is available here: https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?type=design&node-id=4490-34338&mode=design&t=yFhSDzPn3GlN9XOA-0

It's similar to the one one the website, but this uses the app's fonts and colors and the width of the page matches what's currently used in the app.

Let me know if you have questions!
