### ISSUE TITLE
New categorization system for examples

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#5454]
We want to categorize tags instead of examples. The examples should all live on the same page, with some kind of filtering mechanism based on the tags.

Because we no longer need categorization of examples, category descriptions, etc., we can remove the [examples/manifest.toml](https://github.com/rerun-io/rerun/blob/main/examples/manifest.toml) altogether, and any tag categorization can live on landing.

**Comment by nikolausWest** [comment]
The current plan I think is more something like:

## In the gallery on rerun.io/examples:

- Show each example as a card, whether runnable or not
- If runnable, include a quick action button that opens up the viewer and loads it directly
- Clicking on a card opens up a preview / modal of the example details page
- The preview / modal can be expanded to be full page 
- The example detail page has a component that shows 
  - a preview screenshot of the example
  - a link to the source code
  - a description of what it is
  - the Rerun types used
  - (optionally) a mini tutorial with the code snippets with rerun calls used to create it
  - instructions of how to run it
- If the example is runnable (has an available rrd file) there is a button that replaces the preview image with an inline web-viewer
- There is a categorization system that helps users filter and navigate all the examples
  - Current design is based on tags, which are themselves broken into 3 categories
  - We could also go with something simpler, like putting all examples on the same page divided into categories

# In the in-app welcome page

- Shows all runnable examples as cards
- Clicking on a card streams the rrd into the viewer (web or native)
- To begin with there is no filtering or higher level categorization of the examples

**Comment by nikolausWest** [comment]
Replaced by:
- https://github.com/rerun-io/rerun/issues/5665
