### ISSUE TITLE
Create blueprints for common examples

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5468]
Creating blueprints for the main examples we include on app.rerun.io has a two-fold benefit.

(1) It allows us to validate the blueprint APIs work for the use-cases covered by these examples
(2) Should improve the clarity of the examples themselves once these blueprints are also served as a part of the examples.

Blueprint examples:
 - https://github.com/rerun-io/rerun/pull/5510
 - https://github.com/rerun-io/rerun/pull/5518
 - https://github.com/rerun-io/rerun/pull/5572
 - https://github.com/rerun-io/rerun/pull/5582

## Progress / assignee

↪️ == intentionally skipped

| Example            | Assignee / PR |
|--------------------|----------|
|arkit_scenes |  	✅ https://github.com/rerun-io/rerun/pull/5510 |
|blueprint |  	n/a |
|car |  	removed #5576 |
|clock |  	↪️ (@Wumpf ) |
|controlnet | ✅ #5634 |
|depth_guided_stable_diffusion |  	✅ #5582 |
|detect_and_track_objects |  	↪️ (@Wumpf ) |
|dicom_mri |  	↪️
|dna |  	↪️ (@Wumpf ) |
|external_data_loader |  	↪️ (@Wumpf ) |
|face_tracking |  	✅ #5616 |
|gesture_detection |  	✅ #5619 |
|human_pose_tracking |  	✅ https://github.com/rerun-io/rerun/pull/5612 |
|incremental_logging |  	↪️ (@abey79) |
|lidar |  	↪️ (@abey79) |
|live_camera_edge_detection |  	✅ https://github.com/rerun-io/rerun/pull/5613 |
|live_depth_sensor |  	↪️ (@Wumpf, wouldn't hurt here but I couldn't run it without the hardware and it looks kinda simple; could a blueprint than rgbd though) |
|llm_embedding_ner |  	✅ https://github.com/rerun-io/rerun/pull/5614 |
|log_file |  	↪️ (@Wumpf ) |
|minimal |  	↪️ (@Wumpf ) |
|minimal_options |  	↪️ (@Wumpf ) |
|multiprocessing |  	↪️ (@abey79) |
|multithreading |  	↪️ (@abey79) |
|nuscenes |  	✅ https://github.com/rerun-io/rerun/pull/5556 |
|nv12 |  	↪️ (@abey79) |
|objectron |  	✅ #5617 |
|open_photogrammetry_format |  	↪️ (@abey79) |
|plots |  	✅ #5517 |
|raw_mesh |  	↪️
|rgbd | ✅ 	#5623 |
|ros_node |  	 |
|rrt-star | 	↪️ (@Wumpf) |
|segment_anything_model |  	↪️ (@Wumpf) |
|shared_recording |  	↪️ (@Wumpf) |
|signed_distance_fields |  	✅ #5635 |
|stdio |  	↪️ (@Wumpf) |
|structure_from_motion |  	✅ https://github.com/rerun-io/rerun/pull/5572 |
|template |  	↪️ (@Wumpf) |

**Comment by jprochazk** [comment]
We should also have blueprints for every snippet, at minimum to disable the timeline and blueprint views.

**Comment by abey79** [comment]
Related:
- #5477

**Comment by emilk** [comment]
On the flipside; if an example works well without a blueprint (e.g. Dicom) then I think it makes sense to leave it as is, to also show users that they don't _need_ to set a blueprint
