### ISSUE TITLE
Log and visualize tables / dataframes

### ISSUE THREAD

**Issue by gokcergun** [rerun-io/rerun#5585]
Hi, 

I'd like to log a table. I checked the available options but couldn't see any alternative except using Text. 
Is there a way to do? If not, is it a feature that you plan to implement? 

Thank you.

**Comment by teh-cmc** [comment]
> I'd like to log a table. I checked the available options but couldn't see any alternative except using Text.

Your best bet today is to use a [`TextDocument`](https://www.rerun.io/docs/reference/types/archetypes/text_document) with a markdown [`MediaType`](https://www.rerun.io/docs/reference/types/components/media_type):
![image](https://github.com/rerun-io/rerun/assets/2910679/8a5fd5e7-9c5a-417d-9fc4-4871fd45df06)

> Is there a way to do? If not, is it a feature that you plan to implement?

We plan to make it possible for users to visualize _anything_ that sits in the database by combining a custom query with a generic dataframe view, but we're not quite there yet.

Here's a screenshot from recent experiments:
![image](https://github.com/rerun-io/rerun/assets/2910679/79360357-57bf-44dd-a279-d6537b3c72a4)

You can follow the progress on that in the tracking issue:
- https://github.com/rerun-io/rerun/issues/4466
