### ISSUE TITLE
Styling in markdown tables is broken

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#5588]
Here's an unstyled table, it's fine:
![image](https://github.com/rerun-io/rerun/assets/2910679/b1489ed0-8087-4189-9eaa-52d6b84ea3c9)

And then adding a bit of bold and italics...:
![image](https://github.com/rerun-io/rerun/assets/2910679/385e2aa7-8442-419c-9a25-c71c88f99a2f)

**Comment by Wumpf** [comment]
great find, I'm mirroring this over to https://github.com/lampsitter/egui_commonmark/issues

**Comment by Wumpf** [comment]
fixed in egui_commonmark 0.14 (to be released)
