### ISSUE TITLE
Locally edited blueprint overridden when loading an example

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5629]
https://github.com/rerun-io/rerun/assets/49431240/e3bf1dea-d107-4aa6-a1e5-7a0843e1d67a

**Comment by emilk** [comment]
`App::save` is called on shutdown on my Mac, so at this does not look like an `eframe` bug

**Comment by emilk** [comment]
The blueprint is in fact saved fine, it is just that when you load an example, the blueprint in the example .rrd gets activated and overrides you local blueprint.

**Comment by jleibs** [comment]
Considering this fixed as of: https://github.com/rerun-io/rerun/pull/5678

In the default behavior we don't touch the active blueprint, but the reset button will now return the blueprint to the one that came from the last recording you loaded.
