### ISSUE TITLE
Viewer not starting with: thread 'ThreadId(1)' panicked at 'Failed to get focus'

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#5642]
**Describe the bug**

I'm getting the following when starting the viewer on recent prereleases and when building from main

> thread 'ThreadId(1)' panicked at 'Failed to get focus'
egui/src/memory.rs:803
stack backtrace:
... (see below)

For reference, prerelease from c8d6edf59bd496b523a5dbf9506d11c6951743a6 works fine.

**To Reproduce**
Just run `rerun` in the command line.

**Expected behavior**
Start the viewer.

**Backtrace**

```
thread 'ThreadId(1)' panicked at 'Failed to get focus'
egui/src/memory.rs:803
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   7: core::panicking::panic_display
             at core/src/panicking.rs:168:5
      core::panicking::panic_str
             at core/src/panicking.rs:152:5
      core::option::expect_failed
             at core/src/option.rs:1988:5
   8: egui::context::Context::wants_keyboard_input
   9: egui_winit::State::on_window_event
  10: eframe::native::epi_integration::EpiIntegration::on_window_event
  11: <eframe::native::wgpu_integration::WgpuWinitApp as eframe::native::winit_integration::WinitApp>::on_event
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
  13: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
  14: winit::platform_impl::platform::EventLoop<T>::run_on_demand
  15: eframe::run_native
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Rerun version**
> rerun_py 0.15.0-alpha.3 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu

**Comment by emilk** [comment]
On it
