### ISSUE TITLE
Opening a blueprint appears to do nothing if you have no rrd files

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5694]
We are dependent upon the existance of Recordings to manage whether an app shows up in the recordings.

However, if I open a blueprint, I expect to see the app show up, regardless of whether I have any recordings.

**Comment by emilk** [comment]
In other words, you want to see all app ids in the blueprint panel, regarless if they have any recordings or not?
What if you open a recording and close it again, do we still show the app id? Or do we throw out the blueprint once we close the last recording using it?

**Comment by jleibs** [comment]
If we make app an explicit, selectable concept rather than an implicit grouping of recordings I think it warrants its own close button somewhere.

**Comment by emilk** [comment]
Suggestion:
* Switch to the app id when opening a blueprint (even if it has no recording)
* Show all known App Ids in the Blueprint panel that has at least one blueprint OR recording
* Close all blueprints of an App Id when closing the last recording of that app ID
