### ISSUE TITLE
Docs preview links are broken due to faulty redirection

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#5702]
When I click on this link <https://rerun.io/preview/a523fa2fe35458d442d7ce82a3db52c06d320a4a/docs>, I get redirected to <https://www.rerun.io/preview/[commit]/docs/getting-started/what-is-rerun> instead of <https://www.rerun.io/preview/a523fa2fe35458d442d7ce82a3db52c06d320a4a/docs/getting-started/what-is-rerun>.

**Comment by jprochazk** [comment]
The `/preview` stuff is gone in favor of per-PR builds
