### ISSUE TITLE
API for reading logs in python

### ISSUE THREAD

**Issue by darren-harton** [rerun-io/rerun#5749]
Saving logs with rerun is convenient and easy, but I wish I had the ability to programmatically parse my logs after they have been saved. If this were possible then I could recommend rerun as an alternative to ROS' logging for many use cases.

Thanks for the excellent free software :)

**Comment by teh-cmc** [comment]
Querying the Rerun database from the SDK (..not limited to Python!) is definitely on our roadmap, though I don't have an ETA.
