### ISSUE TITLE
Problem accessing example manifest results in bad welcome page

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5752]
I tested out `0.15.0-rc.1` before the manifest had fully published and was welcomed to this screen:

![image](https://github.com/rerun-io/rerun/assets/3312232/c79586ff-1856-4838-8e91-baf1b0a9807a)

Even if we can't reach/process the manifest we should probably have a fallback welcome screen that is more user-friendly.

**Comment by emilk** [comment]
This should be a fairly easy fix: just log the error instead of showing it, and then only show this portion to the user:

<img width="581" alt="Screenshot 2024-04-03 at 05 47 45" src="https://github.com/rerun-io/rerun/assets/1148717/95d11a84-0917-4f13-819e-b64eae56466f">

**Comment by emilk** [comment]
The first part of the welcome page should also show up right away. Right now it is waiting for the example manifest to download, which is unnecessary.
