### ISSUE TITLE
tensor selection preview tries to show an image and fails

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#576]
**To Reproduce**
open Dicom example, select tensor

**Expected behavior**
show nothing instead

**Screenshots**
<img width="204" alt="image" src="https://user-images.githubusercontent.com/1220815/207937145-296deba2-b169-4a0a-8ad2-a204beae8614.png">

**Comment by teh-cmc** [comment]
Fixed

![image](https://user-images.githubusercontent.com/2910679/221872799-a795cdfa-d6f4-47bf-8785-5841c94e55a8.png)
![image](https://user-images.githubusercontent.com/2910679/221873191-70c56a08-d0b5-424b-ac9a-597b59be39e2.png)
