### ISSUE TITLE
Properly format tags in the welcome screen's example card

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5783]
In app vs web, notice the difference in tag formatting:

<img width="356" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/79f302c6-f787-439b-9717-782e73ce939d">
<img width="269" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/8a44abc8-f933-4c76-8701-beb4eedd30fa">

We need to capitalise and remove `-`

**Comment by emilk** [comment]
Blocked by https://github.com/rerun-io/rerun/pull/5779 (will lead to too much merge conflicts)

**Comment by abey79** [comment]
My idea was to do that in the UI code rather than actually changing all tags. That's apparently how it's done for the landing page.

**Comment by abey79** [comment]
Not convinced this is 0.15 blocking, though—just added to the milestone for visibility.

**Comment by emilk** [comment]
We decided on https://rerunio.slack.com/archives/C04UBTMMGJK/p1712250738168869 to not do any conversions, and instead use `Human case` directly in the frontmatter.
