### ISSUE TITLE
Reference all performance bottlenecks highlighted by "air traffic" example

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#5799]
The [recently added air traffic example](https://github.com/rerun-io/rerun/pull/5449) highlights _a lot_ of performance bottlenecks in every single corner of the app (and probably SDK too now that I think of it...).

All these bottlenecks should have a dedicated issue explaining what's going on so we can investigate them at some point.

The first thing to try out is the cleaned up dataset, which demonstrates a lot of performance issues with normal looking data:
```
python examples/python/air_traffic_data/main.py --dataset 2h
```

and then move on to the raw dataset, which adds another layer of issues specific to ill-formed data (which ironically is more likely to be what's in the wild):
```
python examples/python/air_traffic_data/main.py --dataset 2h --raw
```

**Comment by abey79** [comment]
related: https://github.com/rerun-io/rerun/issues/5812

**Comment by teh-cmc** [comment]
Let's see how that behaves once `0.18` is ready to go.

**Comment by emilk** [comment]
Likely:
* https://github.com/rerun-io/rerun/issues/7115

**Comment by emilk** [comment]
Around a third of the frame-time is just asking entities wether or not they have a specific component or data on some timeline. If that was cached, it would be a huge win

![image](https://github.com/user-attachments/assets/6617d861-7845-4a0c-a230-fa58c6231529)

**Comment by abey79** [comment]
0.18 significantly increase frame time on my computer (3d view latest at and one plot with all data)

top 0.17, bottom main as of today.
![image](https://github.com/user-attachments/assets/217f8338-4bda-4bd2-9b2d-421233a9af87)

**Comment by Wumpf** [comment]
We have a decent understanding of this by now
* https://github.com/rerun-io/rerun/issues/8233
