### ISSUE TITLE
Consider a mode where the UI is "off" during ingestion, in order to limit the UI-specific overhead

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#5812]
This could improve loading time for big dataset such as the air traffic example #5449.

Avenues to consider would be:
- `rerun big_file.rrd --batch-load` which would display the UI only after fully loading the rrd
- have the UI display a progress bar with a "Show now" button  for loading recording

**Comment by teh-cmc** [comment]
Related:
- #4298

**Comment by emilk** [comment]
This should be less important now that we have much faster chunk-based ingestion

**Comment by emilk** [comment]
The ingestion overhead is now way down, and I rather work on making it faster (or run it in a background thread) than add a special mode to pause the UI until the data is loaded
