### ISSUE TITLE
Add tooltip to the timeline selection

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#5836]
Adding a onHover message for the timeline selection that says what a timeline is and that you can change it would be very helpful for onboarding.

![Screenshot 2024-04-08 at 10 19 58](https://github.com/rerun-io/rerun/assets/2624717/b9fcae78-e51b-48cf-8742-ba9643e4ddd1)

**Comment by emilk** [comment]
I tried adding it, but then the tooltip block the actual drop-down menu.

* https://github.com/rerun-io/rerun/issues/5841
* https://github.com/emilk/egui/issues/4338

**Comment by jleibs** [comment]
We could still add a mention of the timeline in the "?" hover for the timeline panel.
