### ISSUE TITLE
1xN tensors are not visualizable

### ISSUE THREAD

**Issue by egorchakov** [rerun-io/rerun#5839]
**Describe the bug**
Logged 1xN tensors don't seem to be visualizable (potentially related to https://github.com/rerun-io/rerun/issues/3709?)

```python
import torch
import rerun as rr

rr.init('tensor-viz', spawn=True, strict=True)
rr.log('1x10', rr.Tensor(torch.zeros(1, 10))
```

**Screenshots**

![image](https://github.com/rerun-io/rerun/assets/1927909/59113558-c087-4175-9755-cd366696d2eb)

**Rerun version**

```
rerun_py 0.15.0-rc.1 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.15.0-rc.1 3c298fd, built 2024-04-02T21:34:01Z
```

**Additional context**

A workaround I stumbled upon is first logging a 2xN tensor to the same entity path and then overwriting it with the original 1xN tensor, which makes the 1xN tensor show up in the viewer:

```python
rr.log('1x10', rr.Tensor(torch.zeros(2, 10)) # dummy 2xN
rr.log('1x10', rr.Tensor(torch.zeros(1, 10)) # original
```

**Comment by abey79** [comment]
Thanks for the report. I could reproduced both the issue and the workaround on `main`.
