### ISSUE TITLE
Blueprint modifications are not saved when closing a recording

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#5854]
Repro steps:

* Run an example that defines a blueprint (e.g. `pixi run python ./examples/python/rgbd/main.py`)
* do some blueprint modification in the ui
* close the recording (not the viewer!)
* run the example again
    * observe that your blueprint modifications are not there!

As video:
https://drive.google.com/file/d/1Y18hwNfDofu533SthTQT7_CF8sRHP1iv/view?usp=sharing

**Comment by emilk** [comment]
Closed by  #5868
