### ISSUE TITLE
Timed out waiting for https://rerun.io/viewer/commit/bc8bcd0 to load.

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#5878]
When executing `rr.show_notebook()`, we always get a cell showing:
```
Timed out waiting for https://rerun.io/viewer/commit/bc8bcd0 to load.
```

For locally run notebooks, the workaround:
```
rr.start_web_viewer_server()
```
will make things for.

For colab notebooks we need a proper fix (https://github.com/rerun-io/rerun/pull/5877)

**Comment by teh-cmc** [comment]
That's already been fixed and merged into the 0.15.1 branch.
