### ISSUE TITLE
Replace non-example `requirements.txt` files with pixi

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5895]
For instance:
* `pip install -r ./scripts/ci/requirements.txt` takes 2 minutes on CI
* `pip install -r rerun_py/requirements-lint.txt` takes 1 minute

We should replace this with something faster and cached.

I think the natural choice is to add these dev-deps to `pixi.toml`.

This would cover all requirements under `rerun_py` and under `scripts`

NOTE: **NOT** the example requirements, JUST the requirements for our dev tools (linting, formatting, …)

**Comment by Wumpf** [comment]
there's also `scripts/requirements-dev.txt` - a bit unclear for what this one is. Should also be included in this cleanup job!

**Comment by emilk** [comment]
> there's also `scripts/requirements-dev.txt`

Yes, as I said:

> This would cover all requirements under `rerun_py` and under `scripts`

To be clear: recursively under those folders, all `**requirements*.txt`
