### ISSUE TITLE
Better link checker on CI (`linkinator` and `lychee` misses important things)

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5925]
* https://github.com/rerun-io/rerun/pull/5923

Another example:
https://docs.rs/rerun/latest/rerun/trait.AsComponents.html links to https://github.com/rerun-io/rerun/blob/latest/examples/rust/custom_data/src/main.rs which is 404 - I've intentionally not fixed this link yet so we can check that the fixed link checker catches it

This makes me worried that we have a lot of broken links.

We need to either fix `linkinator`, or switch to a better tool.

**Comment by emilk** [comment]
We can try https://github.com/lycheeverse/lychee

**Comment by Wumpf** [comment]
Fixed in https://github.com/rerun-io/rerun/pull/5969

**Comment by emilk** [comment]
The new link checker didn't catch the broken link to  https://github.com/rerun-io/rerun/blob/latest/examples/rust/custom_data/src/main.rs which was part of the litmus test of this issue
