### ISSUE TITLE
Fix nightly build

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#5945]
I seem to have broken it in
* https://github.com/rerun-io/rerun/pull/5937

A bunch of job are marked "cancled": https://github.com/rerun-io/rerun/actions/runs/8661261357

You can trigger a new `nightly` build off `main` by going to https://github.com/rerun-io/rerun/actions/workflows/nightly.yml

**Comment by jprochazk** [comment]
Nightly jobs are not being cancelled anymore, but are still failing: https://github.com/rerun-io/rerun/actions/runs/8685071602/job/23814220193

**Comment by Wumpf** [comment]
there we go again! https://github.com/rerun-io/rerun/actions/runs/8721798047
