### ISSUE TITLE
Outdated notebook tutorial

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#5971]
The [tutorial for using Rerun in notebooks](https://www.rerun.io/docs/howto/notebook) (as of 0.15.1) isn't up to date with the[ latest notebook example](https://github.com/rerun-io/rerun/blob/main/examples/python/notebook/cube.ipynb).

For example, from tutorial:
![Screenshot 2024-04-15 at 12 37 56](https://github.com/rerun-io/rerun/assets/2624717/e00ebc84-a864-4805-8013-d2fa057525d8)

But in the notebook, we don't use that api:
![Screenshot 2024-04-15 at 12 38 45](https://github.com/rerun-io/rerun/assets/2624717/c6b1a20f-1461-4524-9459-feeff3826d18)

**Comment by Wumpf** [comment]
* Fixed in https://github.com/rerun-io/rerun/pull/6025
