### ISSUE TITLE
Reset Blueprint buttons in tooltip

### ISSUE THREAD

**Issue by karimo87** [rerun-io/rerun#5984]
**Describe the bug**

When hovering Application ID in Blueprint panel I get two buttons in the tooltip.

**To Reproduce**
See video

**Expected behavior**

No buttons, or a drop down that lets me click the buttons.

**Screenshots**

https://github.com/rerun-io/rerun/assets/6584154/6c664785-0948-4f06-8025-e83bbe300b88

**Backtrace**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6 

**Rerun version**

15.1

**Comment by emilk** [comment]
One way to solve this is to remove all buttons from tooltips.

Another way is to actually add support for clicking buttons in tooltips, by keeping tooltips around when you hover them.

**Comment by emilk** [comment]
These buttons are gone.
Also, since egui 0.28 we now support actually clicking buttons in tooltips.
