### ISSUE TITLE
Extend C++ API to allow to pass rbl file for spawning Visualizier

### ISSUE THREAD

**Issue by rgolovanov** [rerun-io/rerun#6016]
0.15.0 Viewer supports rbl files but it requires to manually load rbl to Visualizer when it is opened.

Would be better to extend API to allow pass RBL file in spawn at logger side (`rr_spawn_options`)

**Comment by teh-cmc** [comment]
This can be done in all languages by first spawning a viewer and then logging the blueprint as a file.

E.g. (pseudo-code):
```python
rr.spawn()
rr.log_file_from_path("my_blueprint.rrd)
```
