### ISSUE TITLE
Build error `error: couldn't read crates/re_web_viewer_server/src/../web_viewer/re_viewer.js: No such file or directory (os error 2)`

### ISSUE THREAD

**Issue by galou** [rerun-io/rerun#6028]
**Describe the bug**
'cargo build` throws `error: couldn't read crates/re_web_viewer_server/src/../web_viewer/re_viewer.js: No such file or directory (os error 2)`

**To Reproduce**
1. `cargo build`

**Expected behavior**
Should build.

**Desktop (please complete the following information):**
 - Ubuntu 22.04.

**Rerun version**
commit 093fc88c370eba4c6

**Comment by Wumpf** [comment]
Unfortunately our in-repo build setup is slightly more complex. Running `cargo build` will build a lot of extra things that have additional requirements. Have a look at our [build instructions](https://github.com/rerun-io/rerun/blob/main/BUILD.md) on how to get started with the repository

Instead, we're relying on the [pixi package manager](https://pixi.sh). Once installed you can simply run `pixi run rerun` to build & start a debug version of the rerun viewer.
