### ISSUE TITLE
Weird reloading on rerun.io/examples

### ISSUE THREAD

**Issue by haixuanTao** [rerun-io/rerun#6033]
Just want to point out that there is a bit of reloading issue on firefox on the rerun website:

Whenever I click on an example, I'm taken back to the example home page despite not clicking on going back.

## Screencast

[Screencast from 2024-04-18 14-13-02.webm](https://github.com/rerun-io/rerun/assets/22787340/0bf79645-a83c-43c4-9c4c-be269348d912)

**Comment by emilk** [comment]
I fail to reproduce using Firefox 124.0.2 on Mac.

Is there any clues in the developer console?

**Comment by jprochazk** [comment]
Issue is related to how we handle redirect from categories that no longer exist
