### ISSUE TITLE
Add script to upload .rrd for easy sharing

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6052]
Something like:

```
> pixi run upload-rrd --version 0.15.1 my_rrd.rrd
Uploaded to https://some-gcs-bucket/my_rrd.rrd
View it with https://app.rerun.io/version/0.15.1?url=https://some-gcs-bucket/my_rrd.rrd
```

This will be very useful when sharing examples.

Being able to read the version string from the .rrd would be nice, e.g. using `rerun print`

**Comment by teh-cmc** [comment]
Actually I just checked and `rerun print recording.rrd` prints everything we know about the recording... except the Rerun version 🤦

**Comment by emilk** [comment]
There is a draft in https://github.com/rerun-io/rerun/pull/6111 but needs some GCS magic in order to set up a HTTP endpoint for the new GCS bucket

**Comment by emilk** [comment]
Next problem is CORS:

> Access to fetch at 'https://static.rerun.io/rrd/0.15.1/rgbd_3f2ebd882270ce75cec25022152f468194c8c4ef.rrd' from origin 'https://www.rerun.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
