### ISSUE TITLE
`search-index` could not be run in the `py-docs` environment

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#6060]
I removed the `py-docs` environment and reverted to a `requirements.txt` file in this PR:
- https://github.com/rerun-io/rerun/pull/6038#discussion_r1572220964

The underlying problem isn't clear, but it may be related to [prefix-dev/pixi#1233](https://www.github.com/prefix-dev/pixi/issues/1233)

**Comment by abey79** [comment]
I'm really surprised that the issue happened there when it clearly doesn't with all the `pixi run -e wheel-test` stuff.
