### ISSUE TITLE
Full Design for Container/SpaceView/Entity default+override rules 

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6071]
The original plan for entity overrides only covered overriding of components for visualizers.

We would like to expand this design to also include defaults and/or overrides not just of visualizers, but also of space-view properties, possible sourced from containers.

For example: set the default view coordinates for all space-views to Z-up.

This issue should include:
 - Clearly articulated description of the different mechanims of override and how they interact
 - Python API concept for all mechanisms of override
 - Figma UI concept for all mechanisms of override

This issue does not cover implementation .

**Comment by Wumpf** [comment]
I think we figured all these things out quite well by now and even implemented a fair chunk. It's a bit scattered accross figma documents and issues, but it's there.
The only thing we haven't fully formulated is doing overrides/defaults on contains, but that doesn't seem super challenging from where we are (but also we deprioritized this part)
