### ISSUE TITLE
Allow specifying camera image plane distance as part of Pinhole archetype

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6084]
This is more of a styling property (and docs need to make this very clear) but since we decided to not make much difference between styling and data (both can be specified in the blueprint store soon) we should just add it to the Pinhole archetype.

Today, this is only heuristically driven and it's a source of great frustration to set this by hand in the ui once there's multiple cameras.

This implies moving this out of the legacy `EntityProperties`, see
* #4442

Also related to:
* https://github.com/rerun-io/rerun/issues/3810

**Comment by nnop** [comment]
looking forward to this feature. it's tedious to always manually set the image plane distance.
