### ISSUE TITLE
`static` components doesn't roundtrip when saved to `.rrd` file

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6094]
Repo: load "detect and track objects example", and looks at the streams view:

<img width="221" alt="Screenshot 2024-04-24 at 11 42 25" src="https://github.com/rerun-io/rerun/assets/1148717/6736c390-e9d2-470d-bada-0d722e73b73f">

Save it to disk, close rerun, and load the saved .rrd. Look again:

<img width="178" alt="Screenshot 2024-04-24 at 11 43 11" src="https://github.com/rerun-io/rerun/assets/1148717/4f26b230-8365-40b1-968e-582d7b1a7d79">

**Comment by teh-cmc** [comment]
Oh I don't think we even have a roundtrip test for the save path on the viewer-side :facepalm: (as opposed to the save path on the SDK side).

**Comment by teh-cmc** [comment]
> Oh I don't think we even have a roundtrip test for the save path on the viewer-side 🤦 (as opposed to the save path on the SDK side).

Nevermind, we have a pretty extensive test suite for this in fact... what's going on here :thinking:

**Comment by teh-cmc** [comment]
I actually cannot repro this. I tried:
- Saving entire timeline, `0.15.1`
- Saving time selection, `0.15.1`
- Saving entire timeline, `main`
- Saving time selection, `main`

**Comment by emilk** [comment]
Then let's close this
