### ISSUE TITLE
Clicking a SpaceView bar immediately triggers drag-n-drop

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#6124]
When you click on a spaceview bar, it triggers a drap-n-drop motion to a random place -- it's particularly annoying when you misclick the bar while you meant to click the name to access the properties.

https://github.com/rerun-io/rerun/assets/2910679/e849a584-4afd-4484-9ae4-42896c6bf050

**Comment by emilk** [comment]
We should fix this in egui_tiles. A drag shouldn't start until the mouse moves a bit

**Comment by abey79** [comment]
egui_tile issue: https://github.com/rerun-io/egui_tiles/issues/79
