### ISSUE TITLE
`segment_anything_model` & `detect_and_track_objects` examples are broken

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6128]
Almost certainly due to some dependency shenanigans, but the error output is very poor, very hard to understand why things fail.

This is preventing the `nightly` build from succeeding.

**Comment by jleibs** [comment]
Should be fixed by: https://github.com/rerun-io/rerun/pull/6137

pending next nightly to close

**Comment by jleibs** [comment]
this part is passing nightly
