### ISSUE TITLE
Looping affects first person view

### ISSUE THREAD

**Issue by roym899** [rerun-io/rerun#6141]
**Describe the bug**
Under some circumstances the first person view will not stay the same when looping. My guess is this happens when an image is logged before its pinhole.

**To Reproduce**
TODO

**Expected behavior**
View should stay the same.

**Rerun version**
> rerun_py 0.15.0 [rustc 1.74.0 (79e9716c9 2023-11-13), LLVM 17.0.4] x86_64-unknown-linux-gnu release-0.15.0 bc8bcd0, built 2024-04-09T14:34:04Z

**Comment by Wumpf** [comment]
any chance you can dig up a repro case on this?

**Comment by roym899** [comment]
I once tried to reproduce this and couldn't. So I think it's not an issue anymore.
