### ISSUE TITLE
Update `wgpu`/`winit`/`egui` as soon as `0.16` is out

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#6170]
As @Wumpf said: 
> We decided on post-standup not to update wgpu/winit/egui before the release in order to not drag it out and accumulate more risky changes.

We should be ready to merge all of that ASAP once `0.16` is out though, this needs as much soak time as we can get.

TODO:
- [x] `wgpu` PR ready
- [ ] `winit` PR ready
- [x] `egui` PR ready

**Comment by Wumpf** [comment]
looks like we'll take winit in the release after
