### ISSUE TITLE
Line widths grow as 2D view shrinks

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6215]
![image](https://github.com/rerun-io/rerun/assets/1148717/6bef6763-43ba-43e7-8a2c-f663cf8656ac)

If I specify the line widths in scene units it works, but specifying them in ui points causes them to be way too large.

**Comment by emilk** [comment]
TODO: check if this is a regression or old bug

**Comment by emilk** [comment]
I suspect `RectTransform`, without proof. Do we have a test for this @Wumpf ?

**Comment by Wumpf** [comment]
issue doesn't repro for me. Lines stay constantly at 8pixel for 2ui points at 200% screen scaling which is what I would have expected
![image](https://github.com/rerun-io/rerun/assets/1220815/26bf1fbc-f72a-48b4-abbf-12315f9639c6)

**Comment by Wumpf** [comment]
missunderstanding on my side: changing the size of the viewport causes the issue as described!
