### ISSUE TITLE
Confusing parts of VisibleTimeRange API

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6276]
### The TimeBoundary requires passing in a TimeInt.
- In our `set_time_seconds` APIs, we allow floating point seconds values.
- At the moment if you mistakenly pass a float in seconds, it's converted to an int implicitly (and incorrectly)
- Proposal: make this require a rwarg: seq, seconds, or nanos

### API doesn't make it clear you can't specify a time range more than one
- Because the input takes the form of a list, it's not clear that you can't do:
```
    time_ranges=[
        rrb.VisibleTimeRange(
            "time",
            start=rrb.TimeRangeBoundary.absolute(0),
            end=rrb.TimeRangeBoundary.absolute(10),
        ),
        rrb.VisibleTimeRange(
            "time",
            start=rrb.TimeRangeBoundary.absolute(20),
            end=rrb.TimeRangeBoundary.absolute(30),
        ),
    ]
```
as a user I might expect this to give me the union of the two ranges. Instead I believe it's simply first-value-wins for the timeline key.
- At a minimum we should probably warn on duplicate values here.

**Comment by Wumpf** [comment]
nothing to add to the first point and I think it's quite important to improve this as suggested.

> API doesn't make it clear you can't specify a time range more than one

it is documented that it's a first value wins situation `/// If a timeline is listed twice, the first entry will be used.`.
We could look into making this also take a dictionary but that gets tricky to map out to the existing data structures. I'm not convinced yet this is that much of a problem to justify a lot more time spent on it.

**Comment by jleibs** [comment]
> it is documented that it's a first value wins situation

Not in the doc visible in the editor:
![Image](https://github.com/rerun-io/rerun/assets/3312232/7aa7e028-da45-48cc-94bd-7369a5d70cba)

This other thing I was thinking we could do would just be scan them and print a warning.
