### ISSUE TITLE
egui ID clash in Selection panel

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6300]
```
git checkout 3dc64f9ebb5f04a7e696a4def64b6a66fe7a977d
pixi run rerun
```

* Open any example
* Select the recording (press escape)
* Scroll horizontally in the selection view

![image](https://github.com/rerun-io/rerun/assets/1148717/b207f67e-5778-4550-8af5-c7caed15bfa6)

**Comment by abey79** [comment]
I can't reproduce this, even on this exact commit 🤔
