### ISSUE TITLE
f64 depth images aren't displayed in the UI

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#635]
After #608 f64 depth images don't get shown in the viewer. Instead we get the following on logs in the terminal:

```bash
2022-12-23T12:22:46.423032Z  WARN re_viewer::misc::caches::tensor_image_cache: Bad image "tensor [270, 480]": Don't know how to turn a tensor of shape=[270, 480] and dtype=F64 into an image
```

**Comment by jleibs** [comment]
This doesn't just apply to depth images but to any f64 monochrome image.

**Comment by teh-cmc** [comment]
This applies to any image shaped tensors, whether it's depth or albedo.

`ClassicTensor::as_dynamic_image` doesn't handle `f64`s at all.

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/1686
