### ISSUE TITLE
Replace DataCell::from_* and to_* functions with their try_* counterparts.

### ISSUE THREAD

**Issue by Artxiom** [rerun-io/rerun#6399]
As discussed in PR #6380:
The functions `DataCell::from_arrow`, `from_arrow_empty`, `to_native`, etc. are just thin wrappers around their `try_*` counterparts. They only call `unwrap()` -  and thus panic in case of an error.
It would be better to remove the wrappers and properly handle the error-case everywhere but this requires a refactoring of every call of these functions.

Related to #3408 and #6330.

**Comment by Wumpf** [comment]
DataCell got removed by now making this obsolete
