### ISSUE TITLE
Manual settings for Y axis scale of time series plot doesn't work in 0.16.0

### ISSUE THREAD

**Issue by rgolovanov** [rerun-io/rerun#6429]
**Describe the bug**
Manual settings of Y axis limits don't work. It seems like it always stay in auto mode with  initially set limits.

**To Reproduce**
1. Log scalar values to rerun
2. In viewer try to adjust Y axis limits in manual mode
3. See values can't be applied

Reproducible with example: https://app.rerun.io/version/0.16.0/?url=https://app.rerun.io/version/0.16.0/examples/plots.rrd
![image](https://github.com/rerun-io/rerun/assets/14174584/91c67a1f-e774-4fdd-93a2-4799b2e1cde6)

**Expected behavior**
Manually set limits working as expected

See 0.15.1 https://app.rerun.io/version/0.15.1/?url=https://app.rerun.io/version/0.15.1/examples/plots.rrd

**Desktop (please complete the following information):**
Windows

**Rerun version**
0.16.0

**Additional context**
The feature worked in 0.15.0

**Comment by Wumpf** [comment]
* Duplicate to https://github.com/rerun-io/rerun/issues/6383
* Fixed in https://github.com/rerun-io/rerun/pull/6384
