### ISSUE TITLE
`log_components` and `log`'s extra argument should take single components/component batches

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6445]
Let's say I don't want to put (e.g.) draw order on my archetype for some reason.

Then today I have to do:
```python
rr.log( "boxes", rr.Boxes2D(mins=[-1.5, -1.5], sizes=[2, 2]), [rr.components.DrawOrderBatch(12.0)])
# or
rr.log_components("boxes", [rr.components.DrawOrderBatch(14.0)])
```

When I'd rather do this:
```python
rr.log("boxes", rr.Boxes2D(mins=[-1.5, -1.5], sizes=[2, 2]), rr.components.DrawOrderBatch(12.0))
# or
rr.log_components("with_draw_order_after_the_fact", rr.components.DrawOrderBatch(14.0))
```

or even better this:
```python
rr.log("boxes", rr.Boxes2D(mins=[-1.5, -1.5], sizes=[2, 2]), rr.components.DrawOrder(12.0))
# or
rr.log_components("with_draw_order_after_the_fact", rr.components.DrawOrder(14.0))
```
(not entirely sure the last one can be done without bigger changes, but single component batches should be easy I reckon)

**Comment by teh-cmc** [comment]
We went back and forth a bunch of times on this one...

It was a matter of "do we really want to hide from the user that this thing really is a batch, _not_ a single value?".
At this point this ship has long sailed I guess, so better be consistent and allow single values everywhere possible.
