### ISSUE TITLE
Update `glam` and fork `macaw`

### ISSUE THREAD

**Issue by Danvil** [rerun-io/rerun#6467]
The glam dependency should be updated to version 0.27. Currently rerun 0.16 depends on a very old version of glam 0.22. This forces users who want to use the rerun/glam integration to also depend on this old version of glam.

**Comment by emilk** [comment]
We also use [`macaw`](https://crates.io/crates/macaw) which currently is on glam 0.25. Unfortunately `macaw` doesn't have a public repository where one can make PRs. Perhaps we need to fork it.

**Comment by Wumpf** [comment]
Wondering if we could actually drop macaw, don't think we use it that much.

**Comment by emilk** [comment]
We mostly use `BoundingBox` and `IsoTransform` from it, which we could copy-paste into a `re_math` crate

**Comment by Wumpf** [comment]
fwiw [Affine3A](https://docs.rs/glam/latest/glam/f32/struct.Affine3A.html) is actually glam we just happen to use reexports in some places it seems. Otherwise yes we use those. On the surface looks like our usage is quite trivial, so I think copying over what we need is the right call.
