### ISSUE TITLE
Non-interactive `ListItem` has hover-effect

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6481]
Repro:

```rs
list_item::ListItem::new(ctx.re_ui)
    .interactive(false)
    .show_flat(
        ui,
        list_item::LabelContent::new("Temporal component")
        .with_icon(icon)
        .exact_width(true),
    );
```

![listitem-bug](https://github.com/rerun-io/rerun/assets/1148717/76a00cd7-364b-4aec-b3f1-23f7676da40a)

Expected that `.interactive(false)` would make it not respond to any hovering.

Btw, should maybe `trait ListItemContent` have an `fn sense(&self) -> Sense` that controls this, instead of having the `.interactive(…)` call on `ListItem`?

**Comment by abey79** [comment]
> Btw, should maybe `trait ListItemContent` have an `fn sense(&self) -> Sense` that controls this, instead of having the `.interactive(…)` call on `ListItem`?

I'm not sure. interactive vs. non-interactive is orthogonal to the exact content that the `ListItem` displays. To me, it's a general-purpose feature that should be offered by `ListItem` itself, and every `impl ListItemContent` should be able to cope with both interactive or not context.
