### ISSUE TITLE
Fast determination of empty results without resolving promises

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6536]
Now that we are introducing defaults and overrides, we want to write a bunch of code that essentially looks like:
 - If override has value, return override.
 - If data has value, return data.
 - If defaults has value, return default.
 - Else return fallback.

However, making the determination of "has_value" is complicated.  It's insufficient to just check of the results contain a component because sometimes that component is empty, and we don't even know until the promise is resolved.

**Comment by teh-cmc** [comment]
Fine-grained promises are gone.
