### ISSUE TITLE
Improve tooltips for overrides and defaults as well as for enums 

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6556]
We should show the component's documentation here (showing the archetype field documentation isn't as clear cut since we don't necessarily know which archetype we're targeting)

<img width="310" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/179925ed-4ee0-4400-9089-6d018d2f51eb">

To achieve this we should codegen out the component's doc string which can be easily done!

Technically a separate issue, but same solution: we don't have tooltips for enum editors (see `re_edit_ui` `edit_enum`). Again the obvious solution is a `variant_documentation(Self) -> &'static str` method on enums.
<img width="292" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/008d4d8a-9eb2-4b25-9025-665e92fc6103">

**Comment by emilk** [comment]
We should add the enum variant docstring to the new `re_types_core::reflection` API added in https://github.com/rerun-io/rerun/pull/6609
