### ISSUE TITLE
Find a way to make common defaults more visible

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6557]
We should have a way to suggest changing certain component defaults per View.

Certain components are much more common candidates for overrides:
<img width="300" alt="image" src="https://github.com/rerun-io/rerun/assets/1220815/435d2ad9-f392-4479-861a-9e71889518ea">

The tricky part is that we can't show a "current value" in all cases since generally, the current value is dependent on the exact dataresult (e.g. color fallback is implemented per visualizer and typically entity path dependent).

-> Either we limit ourself to components where we rely strictly on the placeholder (how to enforce?) or we somehow indicate that the default was not yet set.
The later is generally preferable since we want to be able to express what data is actually in the blueprint store, i.e. what blueprint has been sent from the code. If we were to show properties as-if a default was set, this makes the blueprint-code to viewer relationship quickly confusing!

I believe we want a ui that has the effect of “hey, hey! I'm a component that's cool to set as a default!" with neither showing the value nor indicating that it was already set 🤔

**Comment by jleibs** [comment]
This is addressed by the new override UI: #6605

**Comment by Wumpf** [comment]
closing until we think it's not visible enough
