### ISSUE TITLE
Request For Security Contact

### ISSUE THREAD

**Issue by RedYetiDev** [rerun-io/rerun#6567]
Hi! I'm a security researcher, and it looks like your project doesn't have a `SECURITY.md` file. If possible, I'd like to get in touch with a security contact so I may report a vulnerability.

**CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H**

**Comment by Wumpf** [comment]
we don't have a dedicated contact yet, but you can send to opensource@rerun.io
All of the Rerun Viewer's network traffic is unencrypted at this point so I security flaws in this area would surprise me given that there's simply no security to be had, but still curious

**Comment by Wumpf** [comment]
reopening this as a placeholder for adding a security.md file
