### ISSUE TITLE
Double-axis when camera is logged beneath the transform

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6571]
Reproduces in structure from motion where we split the "camera" frame and the "image" frame.

Now shows two axes. Should only show the one on camera, though this might be tricky to figure out:
![image](https://github.com/rerun-io/rerun/assets/3312232/138b7911-ddfd-4b4b-9886-78d79c2e3b41)

**Comment by Wumpf** [comment]
this got fixed by now!
