### ISSUE TITLE
Add gzip, http2 and checksum-caching by default

### ISSUE THREAD

**Issue by k-bx** [rerun-io/rerun#6589]
I just built and run rerun via `pixi run rerun-web-release`, and upon opening `http://<server>:9090/?url=ws://http://<server>/:9877` in my browser, was surprised to see that it's not using GZIP nor does it use HTTP2 (or HTTP3) protocol. Would be great to add those to the way content is served.

As a person targeting running rerun on a remote Linux machine, it's a bit annoying to reload those 26MB after each rebuild.

<img width="300" alt="image" src="https://github.com/rerun-io/rerun/assets/107968/011c812e-3e41-4475-b431-319ac8dc1350">

**Comment by Wumpf** [comment]
bit more context: We used to have this, but it fell victim to trying to get rid of async code & extra dependencies.
Thinking at the time was that the data volume of the viewer doesn't matter compared with the amount of data that is sent over websocket (that part is actually compressed). But we don't want to get it back eventually
