### ISSUE TITLE
Not all items in override UI always apply to visualizers

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6595]
The value shown can be confusing and the fact that modifying it does nothing is more-so confusing.

- Common issues that impact multiple archetypes:
  - [x] Color shows up as white instead of previewing the resolved entity-hash color.
    - there's missing fallback providers (which we'd also ideally use, but that goes through annotation context resolve often, so exercise caution) 
    - Fixed in https://github.com/rerun-io/rerun/pull/6703
  - [x] Many visualizers allow you to override Text, but it does nothing
    - today, we don't show labels after a certain hardcoded threshold. This is bad and needs fixing in general, but not now. Still open question whether this should be a separate visualizer.
     - consider disabling this for everything except plots 
     - Fixed in https://github.com/rerun-io/rerun/pull/6741
  - [x] Radius shows 1.0 incorrectly making initial edit weird
    - Missing fallback providers
    - Part of #6540
  - [x] Drag to edit a float slider with negative values has too small of a velocity (observed with draw order)
    - fixed in https://github.com/rerun-io/rerun/pull/6718 

- Assessment for each visualizers:
  - [x] BarChartView
    - Override color doesn't work
    - Tensor -> set to fallback value is "weird" but also doesn't work
    - Fixed in https://github.com/rerun-io/rerun/pull/6717
  - [x] Arrows2D
  - [x] Arrows3D
  - [x]  Asset3D
  - [x] Boxes2D
  - [x] Boxes3D
  - [x] Cameras
  - [x] SegmentationImage
  - [x] Image
  - [ ] DepthImage
    - [ ] FillRatio doesn't do anything in 2D view
        - in 2D we don't show the depth cloud which would be affected by this 
        - documented better since https://github.com/rerun-io/rerun/pull/6745
  - [x] Lines2D
  - [x] Lines3D
  - [x] Mesh3D
  - [x] Points2D
  - [x] Points3D
  - [ ] Transform3DArrows
    - Kind of weird -- you can reset the Transform to the fallback value, but it has not effect.
    - Logged in https://github.com/rerun-io/rerun/issues/6743
  - [x] Tensor
  - [x] TextDocument
    -   Setting MediaType to fallback `application/octet-stream` doesn't do anything. Still shows as Markdown
    -  Editing the Text content does nothing
    - Fixed in https://github.com/rerun-io/rerun/pull/6714
  - [x] TextLog
    - All overrides broken: both color and text can be overridden but do nothing
    - Fixed in https://github.com/rerun-io/rerun/pull/6712 
  - [x] SeriesLine
  - [x] SeriesPoint

- Other observations:
  -  Overriding a color of a 3D asset in a 3D scene doesn't change it's color in the projection into the 2D scene. I know why this is the case, architecturally but as a user this feels somewhat unexpected.

**Comment by Wumpf** [comment]
left some notes from slack conversations on various items

**Comment by Wumpf** [comment]
Suggestions for resolving the label issue:
* link to an issue from `Text` component where we describe the issue in details
* document hiding behavior on `Text` component so it shows up on the tooltip (careful: it's used in places where this does _not_ apply)
* maybe: increase hiding threshhold, experiment!

**Comment by Wumpf** [comment]
label was resolved differently, we now place single labels at the center of visualizations

**Comment by Wumpf** [comment]
all addressed, mitigated or filed separately!
