### ISSUE TITLE
Table View Data browser design/roadmap

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#6610]
Write a design document for the data browser to bring clarity on:
- what it exactly is
- dev roadmap

**Comment by emilk** [comment]
Feature request: a toggle for viewing each component either as raw arrow data or using the `DataUi` for it (if any)

**Comment by nikolausWest** [comment]
Might be worth considering if it should be a [Tree Table](https://experience.sap.com/fiori-design-web/tree-table/) rather than a table

**Comment by abey79** [comment]
Closing this one in favour of this tracking issue: https://github.com/rerun-io/rerun/issues/4466
