### ISSUE TITLE
Changing color on a mesh doesn't have any effect

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6624]
This happens likely because we don't update the mesh in the mesh cache, so this likely applies to all properties of the mesh, but color is the only one where editing via ui makes sense.
(so if you were to override positions and send that to the viewer from a python repl, it would likely suffer the same issue)

**Comment by Wumpf** [comment]
(as expected:) now that I made material editable, we have the same problem there as well (on a branch as of writing)

**Comment by abey79** [comment]
Editing most components of mesh seems to have no effect. Should we have some per-archetype component exclusion list to just hide stuff from the UI?

**Comment by Wumpf** [comment]
better, we fix the issue. What needs to be done is that we use all rowids of whatever source the data is from is used as the cache key for the mesh
