### ISSUE TITLE
Viewer instances don't release memory when cell output is cleared

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6642]
A given notebook session can eventually run out of memory at which point the only way to fix it appears to be reloading the page.

My expectation is that when the output of a cell is cleared, the memory should be freed.

To repro, repeatedly execute a cell that outputs a viewer widget until it stops outputting.

At this point the console output for the page will show:
```
WebAssembly module validated with warning: failed to allocate executable memory for module
Uncaught (in promise) InternalError: out of memory 
```
![image](https://github.com/rerun-io/rerun/assets/3312232/7df9e9c2-db45-477b-ac7e-8c20aaae5d6b)

It would be nice if we could also catch this and show the error in the notebook. Instead all we get is an empty white canvas and the newly introduced timeout warning.
![image](https://github.com/rerun-io/rerun/assets/3312232/c5d1a32a-97ec-4dd7-8729-f13a0313352e)

**Comment by jleibs** [comment]
I noticed that every time I re-execute a cell, I another instance of WebAssembly.instantiate being tracked:
![image](https://github.com/rerun-io/rerun/assets/3312232/a2f63a0b-657e-461b-a05a-d9a0d90ea183)

**Comment by emilk** [comment]
Is this a new problem, or a pre-existing one? Not that it matters a lot, seems very high-priority to fix it

**Comment by jleibs** [comment]
It's new. The old notebook approach added an iframe to the page. When the previous iframe is removed from the DOM, it seems like the right cleanup happens.

**Comment by jleibs** [comment]
Digging into the memory inspector and taking snapshots after each cell execution, you can see we leak approximately 100MB per execution. Something is holding a reference that keeps it from being GC'd.

![image](https://github.com/rerun-io/rerun/assets/3312232/4d863d81-db45-4ff5-8cc3-1adeddc4526d)

**Comment by jleibs** [comment]
I believe this is actually an upstream anywidget issue: https://github.com/manzt/anywidget/issues/613
