### ISSUE TITLE
Selection panel touch-up

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#6655]
Follow up to #6637.

Many of these would be addressed by implementing LargeCollapsingHeader with a list item

---

- [x]  spacing within `LargeCollapsingHeader`

<img width="312" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/cd79d0c7-51d6-4fdc-869f-2005fb43b1a6">

<img width="309" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/603bca70-2662-41ca-901b-5ab62fc01c11">

---

- [x] add "empty" note when visualiser list is empty

<img width="312" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/cd79d0c7-51d6-4fdc-869f-2005fb43b1a6">

---

- [x] fix large collapsing header
  - do not change on-hover background on `LargeCollapsingHeader`: 
  - alignment bug
  - align background on round pixels
  - https://github.com/rerun-io/rerun/pull/6657

<img width="422" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/c1eac306-8c59-427d-97c3-b6ceec3e6ebb">

---

- [x] move the ?  and Edit buttons of the entity path filter
  - [x] ? button done in: https://github.com/rerun-io/rerun/pull/6657
  - [x] add support for action button (vs. menu button) to section header https://github.com/rerun-io/rerun/pull/6662

<img width="295" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/572bdd12-9fe5-4b78-8cd9-6f9d46d53688">

change to:

![image](https://github.com/rerun-io/rerun/assets/49431240/226d3715-c948-408a-aec7-bcb22b13de1c)

---

- [x] move the long Visible Time Range tooltip to a "?" button.
  - https://github.com/rerun-io/rerun/pull/6668

**Comment by emilk** [comment]
All done!
