### ISSUE TITLE
Replaying logs (e.g. rrd files) programatically in Python

### ISSUE THREAD

**Issue by vmayoral** [rerun-io/rerun#6682]
Similar to what's enabled by the `rerun` CLI command, are there any examples that show how to replay logs (e.g. a bunch of`.rrd` files) programatically in Python.

Thanks,

**Comment by teh-cmc** [comment]
Hey; getting data out of Rerun (e.g. as dataframes) in one of our focus points for this summer.

- Closing as duplicate of https://github.com/rerun-io/rerun/issues/1790 meanwhile.

**Comment by vmayoral** [comment]
> Hey; getting data out of Rerun (e.g. as dataframes) in one of our focus points for this summer.

All right, thanks a lot. Subscribed to that other ticket. Will be monitoring and contributing as/if possible.
