### ISSUE TITLE
Weird number alignment due to edit ui re-use for display

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6696]
![image](https://github.com/rerun-io/rerun/assets/1220815/aa5348ce-ee01-41e8-bfee-6f0624397452)

We use DragValue for some number displays now since edit_ui is used as a display fallback.

We should fix this for now by checking for enabledness and use a label instead.

Very related to
* https://github.com/rerun-io/rerun/issues/6661

**Comment by emilk** [comment]
The label colors are also quite inconsistent. If we always use labels for the non-interactive case, it should look consistent
