### ISSUE TITLE
Component tooltips are too wide, then shrink

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#6702]
https://github.com/rerun-io/rerun/assets/2910679/78e4cd90-3845-44f2-b38d-ce594787312f

**Comment by emilk** [comment]
I fail to reproduce

**Comment by teh-cmc** [comment]
I found a 100% repro:
```
git checkout main
rm -rf ~/.local/share/rerun/blueprints/*
pixi run -e examples py-build
pixi run -e examples python tests/python/release_checklist/check_static_components_ui.py
```

Now select any of the Position2D components in the streams view:
![image](https://github.com/rerun-io/rerun/assets/2910679/382df8b7-79ac-4979-a06c-10eb1af66810)

**Comment by emilk** [comment]
Is is because `egui_extras::Table` not respecting the `resizing_pass` flag

**Comment by emilk** [comment]
This turned into a rabbit hole of improving the layout and sizing of `egui_extras::Table`…

* First step a refactor: https://github.com/emilk/egui/pull/4755
* Next step: coming soon
