### ISSUE TITLE
Container selection panel UI has bad spacing

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#6704]
<img width="453" alt="image" src="https://github.com/rerun-io/rerun/assets/49431240/6047c861-85eb-4227-975f-be034cac7d9c">

**Comment by emilk** [comment]
The best fix is to change these to `ListItem`. The quick fix is to add this:

```rs
// TODO(#6075): Because `list_item_scope` changes it. Temporary until everything is `ListItem`.
ui.spacing_mut().item_spacing.y = ui.ctx().style().spacing.item_spacing.y;
```

**Comment by teh-cmc** [comment]
- See also https://github.com/rerun-io/rerun/issues/6699 which might be partially or fully duplicated

**Comment by abey79** [comment]
oh yeah, that's a duplicate.
