### ISSUE TITLE
Image view should handle empty dimesions

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#672]
If you log an image with `log_image` that happens to have an extra empty dimension (for instance batch size = 1), we should still show it as an image. #634 solves this by squeezing tensors (dropping empty dimensions) before logging them, but this is also not good since we should avoid modifying the data that the user logged.

The proper solution here would be to accept empty dimensions and just change the image view so that it can handle images (depth, segmentation, rgb) with extra empty dimensions.

**Comment by Wumpf** [comment]
We're doing this fairly consequently by now

```python
import rerun as rr
import numpy as np

rr.init("imagetest", spawn=True)
array = np.reshape(np.random.rand(100, 100), (100, 100, 1, 1, 1, 1))
rr.log("image", rr.Image(array))
```
![image](https://github.com/rerun-io/rerun/assets/1220815/e35c7e7e-ff54-44fe-ae9c-ad3557d6dd20)
