### ISSUE TITLE
Hover pop ups accumulate indefinitely as frame times go up

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#6722]
I have a problem with pop ups that just accumulate as i accidentally hover over stuff and never go away unless a click somewhere or remove focus from the Rerun window.
This barely happens at 60+ FPS, but it becomes more and more common when the viewer slows down (making OPF very painful to navigate on my dedicated GPU).

![image](https://github.com/rerun-io/rerun/assets/2910679/9bad2742-c46a-4c53-92b6-a35b5cb3106f)
![image](https://github.com/rerun-io/rerun/assets/2910679/fb60181c-14ef-49a6-8be2-8dbea98048b1)

**Comment by emilk** [comment]
I think the code for "the mouse is moving away from the tooltip, so close it" is somehow failing when framerate is low

**Comment by emilk** [comment]
Fix:
* https://github.com/emilk/egui/pull/4757
