### ISSUE TITLE
WSL: Lines are not being rendered

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#6749]
On WSL2 using `--renderer opengl`, the native viewer from latest `main` (https://github.com/rerun-io/rerun/commit/67a1705d1d7b2ef677f7e10ea054d6b906c5ac0a) does not render any lines. Software rasterization through `--renderer vulkan` (llvmpipe) works fine.

Tested with `0.16.1` and latest `main`. The issue only appears on latest `main`.

Running the `rgbd` example:

### 0.16.1

![image (6)](https://github.com/rerun-io/rerun/assets/1665677/5b13811a-c24b-4cb0-9264-98615aeab0ea)

### 0.17

![image](https://github.com/rerun-io/rerun/assets/1665677/d14f171b-2bb2-43c4-ad36-c9a3fe6de5b5)

**Comment by Wumpf** [comment]
Issue repros for me as well in this configuration
![image](https://github.com/rerun-io/rerun/assets/1220815/a9d0f126-8e92-424a-8933-d0f16796764d)
As reported, the software rasterizer works slowly but correctly
![image](https://github.com/rerun-io/rerun/assets/1220815/6bacc62d-bf35-4607-9d0b-be3b076432e0)
