### ISSUE TITLE
Configurable extent of 2D space views

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#683]
* allow different modes of how the viewport is set
  * today we only have "largest bounding box"
  * allow different options
    * allow implicit cropping to image
* consider killing off scroll bars

**Comment by nikolausWest** [comment]
Obviously related to https://github.com/rerun-io/rerun/issues/1510, probably a follow up. Ideally you should be able to specify a crop (position and extent). The easiest way to do that is probably through logging a 2D transform (position, rotation, scale), followed by an extent setting on the resulting space view (much easier than adding the crop operation to the transform tree).

**Comment by emilk** [comment]
Related:
* #2295

**Comment by abey79** [comment]
I'd consider adding configurable axes as well. One could emulate the perspective/front/left/top quad-views of CAD/3D modelling software with this.

**Comment by nikolausWest** [comment]
@abey79, could you expand a bit on this?

> I'd consider adding configurable axes as well. One could emulate the perspective/front/left/top quad-views of CAD/3D modelling software with this.

**Comment by abey79** [comment]
I'm referring to these kinds of views:

![image](https://github.com/rerun-io/rerun/assets/49431240/bbf31ba0-ce3b-4082-92cf-268dc4269c87)

One is a 3D space view, the other 3 are 2D space views, each attached to a different combination of axes, such as to display the 3D object from the front (X–Y), left (-Z–Y), and top (X–Z) views. Currently, one can duplicate a space view and set it to 2D, but it forces a (I believe) X-Y axes.

**Comment by nikolausWest** [comment]
I think that is an interesting direction, which I think is outside the scope of this particular issue though. It feels to me that what this should be is still a 3D view, but with a more configurable view-eye. We currently support a user controllable perspective eye but one could imagine Orthographic eyes as well + the ability to disable user navigation in the view. @abey79 would you mind opening a separate issue on this?

**Comment by emilk** [comment]
We should follow the lead of the `Background` component and add a space view component
