### ISSUE TITLE
Fix nightly build

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#6899]
It's been a month since our last green nightly build:
* https://github.com/rerun-io/rerun/actions/workflows/nightly.yml

😭 

---

The fixes involved disabling some broken examples. TODO added here:
* https://github.com/rerun-io/rerun/issues/6901

**Comment by emilk** [comment]
Shouldn't close this until we have verified…

**Comment by emilk** [comment]
Just the windows test wheels job broken now:

https://github.com/rerun-io/rerun/actions/runs/9951873366/job/27493385364

**Comment by Wumpf** [comment]
green nightly build sighted!!
https://github.com/rerun-io/rerun/actions/runs/10162257487
