### ISSUE TITLE
Rerun exits with - Error with one the underlying data table

### ISSUE THREAD

**Issue by gauthamnarayan** [rerun-io/rerun#6921]
**Describe the bug**

Rerun exits with the following error:
`ERROR re_viewer::app] Failed to add incoming msg: Error with one the underlying data table: The schema has a column "rerun.controls.EntityPath" that is missing in the data
`
I was able to connect to the same websocket from one computer. But when I tried to connect from another computer after a couple of minutes, I receive the error above. But I'm able to reconnect from the first computer again without any issues. 

This happens once in a while and not a common occurence.

**To Reproduce**
I'm not entirely sure what I can provide to reproduce the issue.

**Desktop (please complete the following information):**
 Ubuntu 22.04 LTS

**Rerun version**
rerun-cli 0.16.1 [rustc 1.76.0 (07dca489a 2024-02-04), LLVM 17.0.6] x86_64-unknown-linux-gnu 6447/merge d24e449, built 2024-05-29T15:06:39Z

**Comment by teh-cmc** [comment]
Your server and clients are very likely not running the same Rerun version.

Our ABI does not provide any backwards- nor forwards-compatibility at the moment, especially so at this time where we are making serious changes to our underlying storage and binary encodings.
