### ISSUE TITLE
Google Colab example linked in https://rerun.io/docs/howto/notebook fails with "ERROR:root:Could not import rerun_notebook. Please install `rerun-notebook`."

### ISSUE THREAD

**Issue by traversaro** [rerun-io/rerun#6938]
**Describe the bug**

The Google Colab example linked in https://rerun.io/docs/howto/notebook fails with "ERROR:root:Could not import rerun_notebook. Please install `rerun-notebook`, probably as the installation step should be modified to also install rerun-notebook. 

**To Reproduce**
1. Go to  https://rerun.io/docs/howto/notebook
2. Click on the Google Colab link in the https://rerun.io/docs/howto/notebook#running-in-google-colab
3. As of 2024/07/18 the link is https://colab.research.google.com/drive/1R9I7s4o6wydQC_zkybqaSRFTtlEaked_ (see https://github.com/rerun-io/rerun/blob/4258c48145dae06dbd66826568742ecd9a0e4cb4/docs/content/howto/notebook.md#L171)
4. If you execute all the cells, then the cell with `rr.notebook_show()` will fail with error "ERROR:root:Could not import rerun_notebook. Please install `rerun-notebook`.", probably as rerun-notebook is not installed in the first cell

**Expected behavior**
That the notebook runs without error.

**Screenshots**

Not relevant.

**Backtrace**

Not relevant.

**Desktop (please complete the following information):**
 - Google Colab
 - 
**Rerun version**

Documentation issue related to the latest version of documentation (not versioned).

**Additional context**

None.

**Comment by traversaro** [comment]
Changing in the notebook the line:

~~~
  !pip install numpy>=1.23 pandas-gbq==0.19 rerun-sdk==0.17.0
~~~

to 

~~~
  !pip install numpy>=1.23 pandas-gbq==0.19 rerun-sdk[notebook]==0.17.0
~~~

fixes the problem, but I quickly searched and I guess the notebook is not stored in a repo.

**Comment by jprochazk** [comment]
Thanks for looking into this, we'll fix the notebook shortly.

> I quickly searched and I guess the notebook is not stored in a repo

Yes, that notebook lives only on colab. It is based on https://github.com/rerun-io/rerun/tree/main/examples/python/notebook

**Comment by traversaro** [comment]
Thanks!
