### ISSUE TITLE
Allow configuring timeline splits

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#695]
The automatic splitting of the timeline means that it's impossible to replay a recording like it happened if there was a long computation without logs. To reproduce, run the tracking_hf_opencv example.

<img width="1054" alt="Screenshot 2023-01-05 at 22 00 34" src="https://user-images.githubusercontent.com/2624717/210880780-0b9475fa-fdb2-44d6-917d-72329200b6db.png">

**Comment by Wumpf** [comment]
Closing in favor of
* https://github.com/rerun-io/rerun/issues/1150
