### ISSUE TITLE
ViewCoordinates docs incorrect on 0.17.0

### ISSUE THREAD

**Issue by Parskatt** [rerun-io/rerun#6954]
https://github.com/rerun-io/rerun/blob/main/docs/content/concepts/spaces-and-transforms.md

>For 3D spaces it can be used to log what the up-axis is in your coordinate system. This will help Rerun set a good default view of your 3D scene, as well as make the virtual eye interactions more natural. This can be done with rr.log("world", rr.ViewCoordinates(up="+Z"), static=True).

```rr.ViewCoordinates(up="+Z"), static=True)``` returns error for 0.17.0. Not sure when using up etc was deprecated.

**Comment by Wumpf** [comment]
Good catch! I digged a bit and apparently we changed this in 0.9 https://rerun.io/docs/reference/migration/migration-0-9#logviewcoordinates but forgot to update the docs
