### ISSUE TITLE
Improve ellipsoid wireframe

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#6962]
Ellipsoid wireframe is today a wireframe of the on-the-fly generated triangle mesh
![image](https://github.com/user-attachments/assets/3085bc17-cb82-4954-a44e-1e6468d9401d)

This approach still has some shortcomings:
* this visualizes something that wasn't actually logged
    * what was logged was an abstract ellipsoid and in the future we may not even use a triangle representation to draw this (ellipsoids are trivial to raytrace, so we could render "perfect" ellipsoids just like we render perfect spheres for points today using raytracing on a small quad)
* users logging ellipsoids often want to express things like eigenvectors (e.g. of covariance matrices) or other abstract quantities
    * what we're interested in is specifically the extent of the primary axis

To that end, we should instead use a more abstract representation by drawing the lines of (2d) ellipses on the primary axis
![image](https://github.com/user-attachments/assets/987e0b57-dd87-4223-abcb-5b792900d033)
(both transparency and dotted lines we can't represent yet)
![image](https://github.com/user-attachments/assets/6e41fb87-8e41-4622-aa6e-2993e3db4bf6)
(this minus the solid, all outlines the same color)

Ideally, we'd also additionally render the view dependent outline on top as done here
![image](https://github.com/user-attachments/assets/f83a4ef8-1959-447c-b383-52f0a167c35d)
Doing this via our outline postprocessor is not feasible right now the way it is set up, so instead we'd need to re-compute these outlines every frame and use our line renderer. While our line renderer is afaik _decent_ with per-frame changing lines, this may be too much computation overhead though. Also, computing this outline "by hand" is probably too complicated to warrant the extra effort, which is why we should shelve this for the moment.

Other potential issues:
Fairly high line tessellation may be needed to hide the fact that our lines are still not connected 🫤
On the bright side, the line renderer is fairly well optimized for long strips, so data overhead wise this isn't as bad (total number of positions it has to send to gpu is n+2 where n is all line vertices in a single line batch + 64bit for each strip)
* https://github.com/rerun-io/rerun/issues/829

**Comment by emilk** [comment]
Closed by https://github.com/rerun-io/rerun/pull/7044

Having the "backface" lines be dashed would be awesome, but too much work right now

<img width="323" alt="Screenshot 2024-08-14 at 14 44 32" src="https://github.com/user-attachments/assets/ca34f80f-b828-4d04-abfe-216fce4caa2b">
