### ISSUE TITLE
`Boxes3DVisualizer` does not account for rotations when computing bounding boxes

### ISSUE THREAD

**Issue by kpreid** [rerun-io/rerun#6973]
**Describe the bug**

The visualizer ignores the `rotations` component when computing the bounding box of the batch of boxes.

https://github.com/rerun-io/rerun/blob/05853c6f408594db12af9ba668e0f8fe24ac7217/crates/viewer/re_space_view_spatial/src/visualizers/boxes3d.rs#L79-L85

**To Reproduce**

1. Open an example with rotated boxes, such as `cargo run --bin snippets -- box3d_batch`
2. Click on “Show bounding box”
3. Observe the boxes escaping the box.

**Screenshots**
<img width="490" src="https://github.com/user-attachments/assets/8c6d2383-07a6-47b3-bba9-8597e3876dc3">

**Rerun version**
Commit 05853c6f408594db12af9ba668e0f8fe24ac7217

**Comment by Wumpf** [comment]
Good find!
Taking this over - rotation is going to be removed as part of #6831 but we then need to make sure that the new transform / out of tree transform is handling the bbox correctly
