### ISSUE TITLE
Monochrome/Grayscale to heatmap

### ISSUE THREAD

**Issue by finnBsch** [rerun-io/rerun#6976]
When logging a lot of images, the data in rerun grows quickly. A lot of images are RGB heatmaps that stem from grayscale images. It would be nice being able to log images as grayscale and visualize them in rerun with a given heatmap.

**Comment by Wumpf** [comment]
Closing as duplicate of
* https://github.com/rerun-io/rerun/issues/6897

**Comment by Wumpf** [comment]
(but adding a comment there on the size motivation, interesting to capture that)
