### ISSUE TITLE
Colormap should include a configurable max value for the data range

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#6978]
This is currently determined heuristically based on the data for each frame, making the mapping inconsistent frame to frame.

Not only does this make it harder to compare values, but it results in visual flickering as outlier data is included and excluded from the depth image.

**Comment by Wumpf** [comment]
Closing as duplicate of
* https://github.com/rerun-io/rerun/issues/6106
* https://github.com/rerun-io/rerun/issues/1510
