### ISSUE TITLE
Buttons in Rerun

### ISSUE THREAD

**Issue by mukundbala** [rerun-io/rerun#7046]
Hi guys, I am planning to use Rerun as an interactive UI. While my camera (a ZED X camera) is running, I want to visualize the incoming RGB, Depth and Poses . I am wondering if there is a functionality for buttons (and callbacks) that allow a user to start, stop and pause the camera recording.

**Comment by teh-cmc** [comment]
Not yet:
-  https://github.com/rerun-io/rerun/issues/2691

(Closing as duplicate)
