### ISSUE TITLE
Wrong Online demo link in 0.18.0 release notes

### ISSUE THREAD

**Issue by andresv** [rerun-io/rerun#7225]
Wrong Online demo link (0.17.0) in https://github.com/rerun-io/rerun/releases/tag/0.18.0

Online demo: https://rerun.io/viewer/version/0.17.0/ should be Online demo: https://rerun.io/viewer/version/0.18.0/

**Comment by Wumpf** [comment]
oops, thank you for pointing this out. It also had the wrong C++ artifact link there. Fixed it!
