### ISSUE TITLE
Screenshot comparison tests

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7268]
Snapshot tests (aka comparing screenshots to a stored reference) are great to catch regression of all sorts and we should have them.

For it to be convenient, we'd need at least:
- a way to create/test them headless on CI, ideally on all runner architectures (Linux/Mac/Windows)—but any would do for starters
- a way to highlight differences between the reference and actual that is easily accessible also for CI jobs
- an easy way to update the snapshots when they break due to changes/new features
- a way to store the snapshots that doesn't clutter the git repo (vello apparently uses git-lfs: https://github.com/linebender/vello/pull/610)

## Related
* https://github.com/rerun-io/rerun/issues/2255

**Comment by Wumpf** [comment]
(renamed ticket because we already have "snapshot tests" using the "insta" framework)

**Comment by emilk** [comment]
Done
