### ISSUE TITLE
Experimental video support (web only)

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7271]
Initial experimental support for video. This will use the WebCodecs API to decode video.

To complete:
- [x] APIs marked as experimental
- [ ] Publish forked version of `mp4` library (`re_mp4`?)
- [x] ~~On native we just create an empty texture~~
  - https://github.com/rerun-io/rerun/issues/7298

Known issue:
- Without a concept of duration, if only a video is logged the timeline won't expand to fill the duration of the video. The user will need to log some other place-holder content to fill in the timeline.
  - https://github.com/rerun-io/rerun/issues/7272

**Comment by jleibs** [comment]
https://github.com/rerun-io/rerun/pull/7261

**Comment by jprochazk** [comment]
Only thing missing here at the moment is publishing `mp4`, but we can wait until we're closer to the 0.19 release for that.

**Comment by emilk** [comment]
* Closed in favor of https://github.com/rerun-io/rerun/issues/7374 and other more granular video issues
