### ISSUE TITLE
All data downloading in examples should use tqdm for progress

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#732]
For larger datasets or for users that have a slow network connection, it's frustrating to run an example and not get any feedback about why nothing is happening.

Solution: All examples that download data should use tqdm to show the download progress.

**Comment by Wumpf** [comment]
are there any demos where we don't at this point?

**Comment by nikolausWest** [comment]
I guess we need to go through and make sure

**Comment by Wumpf** [comment]
_squinting_... seems we do! can always reopen if we missed something
