### ISSUE TITLE
Support ui-interaction with video

### ISSUE THREAD

**Issue by jprochazk** [rerun-io/rerun#7353]
We have video frames available in regular GPU textures, so we should be able to do GPU picking for hover UIs

**Comment by Wumpf** [comment]
What's the task here exactly? We don't have gpu picking for images either at all, so what do we want to accomplish here?

**Comment by emilk** [comment]
There is several steps here:

A) support clicking videos to select them
B) showing a magnification of the video on hover
C) actual color picking on hover (read exact RGB value)

Only C requires reading back the texture to CPU, and is also the least urgent
