### ISSUE TITLE
Test wether UI thread wakes up on new messages

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7378]
@teh-cmc reports this not always working

We should be calling `egui_ctx.request_repaint()` to wake up UI thread and thus ingest more data.

Need a concrete demonstration of whether this is working and capture the contexts where it's broken

**Comment by emilk** [comment]
We now have a test for this, and we've tested, and this issue captures what we want to do:
* https://github.com/rerun-io/rerun/issues/7427
