### ISSUE TITLE
CI job sometime get stuck for a long time on some `cargo doc` steps

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7387]
Happened to me many times lately. e.g. https://github.com/rerun-io/rerun/actions/runs/10787136673/job/29915256091?pr=7386 (completed in 42 minutes)

**Comment by Wumpf** [comment]
```
 1070.24s 	 cargo doc --quiet --no-deps --all-features --workspace
1069.07s 	 cargo doc --quiet --document-private-items --no-deps --all-features --workspace
```

Looks like we're hitting a bug in cargo docs. Might be the same we fought with in wgpu (the "solution" there ended up being a major overhaul of wgpu-core to use less generics ;-))

**Comment by Wumpf** [comment]
It's likely (but not certainly) related to this issue which was the one that caused us so much grief in wgpu:
* https://github.com/rust-lang/rust/issues/114891
