### ISSUE TITLE
Document & test video support matrix

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7393]
We need to document what is supported where:

* [x] [What is supported on native?](https://github.com/rerun-io/rerun/issues/7298)
* [x] What is supported on browser X?
* [x] What container formats?
* [x] [What codecs?](https://github.com/rerun-io/rerun/issues/7375)
* [ ] What is the performance of multiple 4k videos?

Should bottom out in a page on our docs!
Can we document preferred codecs? (av1 we have a backup plan for native)

---

* Dependent on https://github.com/rerun-io/rerun/issues/7375

**Comment by Wumpf** [comment]
Useful guide on codecs https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs#AVC_(H.264)

**Comment by jprochazk** [comment]
We didn't mention performance at all in docs, I don't know if it makes sense at this point?

**Comment by emilk** [comment]
We should at least test some 4k videos and verify that it works

**Comment by Wumpf** [comment]
Several 4k work:

https://github.com/user-attachments/assets/32b78d48-1c22-4644-8068-0ff996710938

sorta, this is prone for me to run into 
* https://github.com/rerun-io/rerun/issues/7570

Even higher resolution video works as well. However, browsers tend to crash the tabs at random for me on some videos. (very distinctivvely not rerun crashing). Might be worth digging up respective browser bugs to link to and filing new ones if needed.

However HDR material is completely broken. We have to note that still down into the docs.
