### ISSUE TITLE
Add a "Get data out of Rerun" section to docs

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#7416]
As soon as we expose the dataframe APIs, we need a docs section under Getting Started called "Get data out of Rerun".

<img width="324" alt="Screenshot 2024-09-12 at 21 20 05" src="https://github.com/user-attachments/assets/fee3f700-d310-45b0-9ec0-25cff37c6de7">

**Comment by jleibs** [comment]
- Recover data passed into logline
- Query + feed into Polars or DuckDB and run a query

**Comment by emilk** [comment]
How would this differ from https://github.com/rerun-io/rerun/blob/main/docs/content/howto/dataframe-api.md ?

**Comment by nikolausWest** [comment]
- closed by: https://github.com/rerun-io/rerun/pull/7643
