### ISSUE TITLE
Can't show the same video in multiple space views

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7420]
We added the ability to reference videos, but our video decoder goes crazy if it has to show frames from different locations at the same time (that's expected the way it's written). Therefore:

* Either remove video reference feature for now
* Or add a hashmap of "decode tracks": Each decode track is just another decoder using the same video data (arc)
    * identification via entity path (+ override entity path if there. Super important otherwise overrides will cause this issue again!)
    * aggressively GC when unused for a frame

I think we can implement that track mechanism easily enough. But if it turns out to be a hassle we can cut back!

**Comment by emilk** [comment]
This should also be able to unlock playing back a video in the selection panel (preview selected video)

**Comment by Wumpf** [comment]
I don't think that's a good idea universally, at least not the simple solution of just looping a video in there: High resolution videos may take a serious amount of processing & memory that we don't want to waste on a small preview. Also if it just keeps playing in there that might be highly distractive. So at least some controls would be needed.
I'd rather pick a still from the video (how?) and discard the decoder once possible
