### ISSUE TITLE
Add splats to polars_util.rs

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#743]
https://github.com/rerun-io/rerun/pull/736 added support for splats to `re_query`

We should go back and add comparable logic to polars_util for completeness, but the ergonomics of doing so is surprisingly painful. I think the answer is going to be to pull in polar-lazy so we can use https://pola-rs.github.io/polars/polars_lazy/dsl/enum.Expr.html#method.repeat_by

Trying to do the equivalent directly on top of raw series and dataframes was not working well.

**Comment by teh-cmc** [comment]
We're moving away from polars.
