### ISSUE TITLE
Dataframes: by default, hide empty columns

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7459]
If we never logged non-empty data to a column, we should by default hide it from the dataframe view and the dataframe queries.

This is most important for all our transform components.

Both in GUI and in Python queries

**Comment by abey79** [comment]
See https://github.com/rerun-io/rerun/issues/7466 for a UI proposal

**Comment by abey79** [comment]
Blocked on #7615

**Comment by teh-cmc** [comment]
* Fixed via https://github.com/rerun-io/rerun/issues/7615
