### ISSUE TITLE
Consider if we can make point-of-view components optional in dataframe queries

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#7461]
How much work would it be?

The idea here would be to:
* By default, the POV-components is `None`
* Without a POV-component, you just return _all_ rows (one row per RowId)

This means by default we show _all_ the data.

(Both in GUI and in Python queries)

Or even: skip POV at all in this first release

**Comment by abey79** [comment]
FWIW, the pov-less, all the rows version is what 0.18's range dataframe view implemented (albeit with entities as rows instead of columns).

Implementation-wise, this should be addressed at `re_dataframe`-level, so technically not a "dataframe view" beyond the related query UI adjustment.

**Comment by jleibs** [comment]
Incorporated into: https://github.com/rerun-io/rerun/issues/7455
