### ISSUE TITLE
Some videos with sound track don't play

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7464]
We don't need sound to be audible, but [this video here](https://drive.google.com/open?id=1-9r20KaywaRECxI-PVZsMUE4xBKWS1n-&usp=drive_fs) doesn't play right now and it really should.
Removing the audio track with ffmpeg makes it work fine.

**Comment by emilk** [comment]
Works on main after
* https://github.com/rerun-io/rerun/pull/7470
