### ISSUE TITLE
Investigate memory usage & limits of browser video decoding

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7480]
* See also https://github.com/rerun-io/rerun/issues/7327#issuecomment-2367430091
* Check memory usage across browsers & OSes

-> Is it actually a concern is the browser just using ram generously on its own accord?
-> Is our strategy on feeding the decoder with all frames of a "segment" viable?

**Comment by emilk** [comment]
## Firefox
Using `about:performance`. Not sure if it includes VRAM use.

The welcome screen uses ~400MB already (!).
Drag-dropping in `bbb_video_av1_frag.mp4` (4.9 MB, 1280x720, 1min) adds ~30MB.

Scrubbing back in the video adds 5-10 MB _each time_, continuously building to around 1000MB before dropping down to 650 MB again.

**Comment by Wumpf** [comment]
At this point we're fairly sure behavior we're seeing is browser dependent on their memory budget and decoding strategy.
However, we still should test longer (30min+) & higher resolution (4k+) videos and see how the system behaves under these circumstances
