### ISSUE TITLE
Show rigid transforms as 3 arrows

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#753]
The axis shown for cameras should actually be a visualization of the rigid transform.
In particular this also means that the axis shown as part of the camera (i.e. projection/pinhole!) aren't part of that object(path) but of a transform that was logged elsewhere
<img width="238" alt="image" src="https://user-images.githubusercontent.com/1220815/212337331-fcd531e9-ade7-450e-8c97-b126813afe6b.png">

"bonus task": The size of the axis is right now completely screen space which can be problematic if there's many on screen and one zooms out! Need to think of something better

**Comment by emilk** [comment]
Related:
* https://github.com/rerun-io/rerun/issues/1111
