### ISSUE TITLE
Configurable background color for the 3D view

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#754]
The background colors we currently use don't always make sense. It might not look good together with the data or add unnecessary visual noise.

Add options:
- To change the colors used to produce the "skybox"
- Se a solid color background

**Comment by Wumpf** [comment]
another example/usecase/request where this came up https://discord.com/channels/1062300748202921994/1062300748777529379/1091954545325785169

**Comment by roym899** [comment]
This is also important for making publication-ready figures. Especially solid white would be important in that case.

**Comment by nsalminen** [comment]
This would be very useful! Is this feature on the roadmap?

**Comment by nikolausWest** [comment]
@nsalminen, it is but not until we've enabled setting properties of views from the SDK, which means on or after the second blueprint release (i.e. at least 2 releases from now).

**Comment by roym899** [comment]
A possible workaround is to log, for example, a large icosphere without vertex normals and vertex color set to whatever background color you would like. If you use Open3D this could be done like this:
```python
# create large white sphere to serve as background
sphere = o3d.geometry.TriangleMesh.create_sphere(radius=100.0)
sphere.paint_uniform_color([1.0, 1.0, 1.0])
rr.log(
    "world/background",
    rr.Mesh3D(
        vertex_positions=sphere.vertices,
        indices=sphere.triangles,
        vertex_colors=sphere.vertex_colors,
    ),
    timeless=True,
)
```

**Comment by nsalminen** [comment]
Thanks a lot for the update, @nikolausWest! My reasons are similar to those mentioned by @roym899 and related issues. It would be great to be able to use rerun for visualizations in papers/presentations. While more advanced solutions for off-screen rendering would be very nice, having the option for a white background so I can take high res screenshots is a good intermediate solution.

Thank you for the clever workaround, @roym899!
