### ISSUE TITLE
Test video playback with video part of pinhole camera & add release_checklist item

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7543]
It should just work out of the box, but we didn't test it out properly so who knows what we'll find!

* create a pinhole camera somewhere in 3D space
   * bonus points for moving the camera around over time
* log a video at the same path the camera sits
   * check the `video_auto_frames.py` snippet to learn how that's done 

⚠️ make sure to test with loading delays - the interaction with https://github.com/rerun-io/rerun/pull/7541 is likely not smooth!

**Comment by emilk** [comment]
Let's make a reusable example or test for this and commit it.
