### ISSUE TITLE
Remove ControlColumn / RowId from the public APIs

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7599]
Having a whole category of ControlColumnSelector / ControlColumnDescriptor at the query layer adds a lot of complexity just for RowId.

Also, we eventually want RowId to be able to act like an Index in the future. For example: `view(index=("frame", "row_id"), ...`,

So even when we expose it, we will want to make RowId a special kind of IndexColumn rather than a ControlColumn.

It may be helpful to give this a reserved name so that we can select("row_id", "log_time", ...) without worrying about ambiguity of a user-logged `row_id` timeline.

Short-term we don't need this to be an allowable timeline at all.

Longer term it would be nice to be able to use this as an index at query time, but this doesn't need to happen for 0.19.

Notably this could woud likely benefit from a specialized implementation that allowed for some documented exceptions:
- Sorting on RowId is less important
  - Since RowIds should be unique, sorted by chunk rather than row_id would let this be far more performant and return chunk-sized record-batches without the need to do any joining.
- LatestAt doesn't make sense on RowId index.

**Comment by jleibs** [comment]
I just remembered that according to: https://www.notion.so/rerunio/Repeated-Time-Values-10bb24554b1980d8a0cdcca3d8903502 we can't meaningfully expose RowId to users without introducing joint-index queries.

Most returned rows are sourced from multiple RowIds and choosing an arbitrary one (such as max) doesn't seem particularly useful since you don't know which data in the row it even corresponds to.

We should still hide RowId from the public APIs.

**Comment by teh-cmc** [comment]
Doing this now would save me from some complicated cross-feature interactions in the dataframe API code.
