### ISSUE TITLE
Unify GPU texture conversion (with focus on chroma downsampled formats)

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7608]
Today, we have a variety of formats that we directly support by out "rectangle" shader.
There's a few issues with this though:
* every time we make it longer we see issues on WebGL on Linux
* we keep appending to the shader that gets more and more complicated https://github.com/rerun-io/rerun/issues/3931

What we need instead is a flexible system for arbitrary (potentially) on-gpu texture conversion.
The interface we want is something that gives you a buffer to write in your special-format bytes and then get back a gpu texture. How the texture is filled then is up to the system and may scheduled more gpu operations.

The immediate need for this is chroma conversions for video data, but everything we enable there, we'd also like to remove from the rectangle shader.

Open questions:
* exact interface
* does this live on the 2d texture manager? Makes sense, but gets bulky. Have it as a extendable sub-system "under" it instead?
* any alternatives to scheduling work on the "global" per-frame encoder?
   * likely the easy go-to solution for the moment 
* Output format limited to RGBA8(srgb)?
    * good start definitely

**Comment by emilk** [comment]
The supported pixel formats should map 1-to-1 to `rerun::PixelFormat`.

We should consider following the naming convention of https://facebookresearch.github.io/ocean/docs/images/pixel_formats_and_plane_layout/

**Comment by emilk** [comment]
Here are the pixel formats we need to support for video: https://docs.rs/dav1d/0.10.3/dav1d/enum.PixelLayout.html

**Comment by Wumpf** [comment]
And these are the color primaries we have to support:
https://docs.rs/dav1d/0.10.3/dav1d/pixel/enum.ColorPrimaries.html

For the moment we shouldn't try to support everything and focus on the most common ones. Which is likely just `BT709` for now. I found BT2020 source material as well, but this gets us into HDR support territory, see
* #7594

**Comment by Wumpf** [comment]
We have what we needed for video. Closing this in favor of this follow-up task:
* https://github.com/rerun-io/rerun/issues/7700
