### ISSUE TITLE
Camera hover is borderline unusable on smaller screens

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#764]
**Describe the bug**
Running the objectron demo, when I hover over the image, the pop-up magnifier ends up taking up almost the entire window.

![image](https://user-images.githubusercontent.com/3312232/212533319-450f61fe-3cda-4bbb-8546-58caaacdd311.png)

**To Reproduce**
Run objectron. Shrink the size of the window.

**Expected behavior**
Hover should not significantly impede your ability to see the existing data.

**Comment by Wumpf** [comment]
![image](https://github.com/rerun-io/rerun/assets/1220815/d3d168dd-2c24-4ee9-8294-0c4cd010a05a)
Things got a lot better since back then. Good enough to close this.
