### ISSUE TITLE
Reconcile `ndarray` version

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7676]
- https://github.com/rerun-io/rerun/pull/7670 added a dep on an older ndarray which meant adding it to the skip list `deny.toml`

Once `numpy` 0.22 is out we should be able to fix this.

**Comment by jleibs** [comment]
We can do this as soon as: https://github.com/PyO3/rust-numpy/pull/453 is released

**Comment by Wumpf** [comment]
Related to:
* https://github.com/rerun-io/rerun/issues/6762
