### ISSUE TITLE
Fine grained ✨auto-viewport state and control

### ISSUE THREAD

**Issue by nikolausWest** [rerun-io/rerun#769]
It's currently really annoying that the "auto-populate viewport" button rearranges the whole layout of the scene. It's also currently hard to understand when the viewer is in a state where it automatically adds new space views, data blueprints, or updates blueprint options an when it isn't. The problem was explored [here](https://www.figma.com/file/JWWdDidzSK5v6fnTaRZtN6/(Public)-UI%2FUX-Sketching?node-id=19%3A3916&t=tgF81p1QvTA5bJ8I-1).

@martenbjork is working on a first sketch of a design but the solution will be about exposing more fine grained state on when we are ✨auto-updating or not, as well as more fine grained control over running the ✨auto-update.

**Comment by nikolausWest** [comment]
@martenbjork sketched up a solution design here: https://www.figma.com/file/3WX8yUqa8ECmhLwV6NIF3a/Rerun-Design-System?node-id=1845%3A12482&t=lEVwBMLP4JlII9CZ-1

**Comment by abey79** [comment]
@nikolausWest this seem at the same time very difficult to get right, and largely superseded by blueprints (and in particular the "export blueprint to code" story). OK to close?

**Comment by nikolausWest** [comment]
Alright, lets close for now then
