### ISSUE TITLE
`rr.serve` should be `rr.serve_websocket`, `rr.connect` should be `rr.connect_tcp`

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#7766]
And similarly, `rerun --serve` should be `rerun --serve-websocket` (or something along these lines, you get the idea).

Users get understandably confused by this. They expect a serving process (`rr.serve()`) to be ready to accept connections from other processes (`rr.connect()`), except the two things are in reality completely unrelated: one is hosting a websocket server to be polled by the web-viewer, while the other is trying to connect to the TCP sdk comms pipeline. 

See e.g. this thread: https://discord.com/channels/1062300748202921994/1295914647165210634

**Comment by zehiko** [comment]
+1, I ran into this confusion myself just yesterday

**Comment by teh-cmc** [comment]
Yet another thing that would make documenting the app model (#919) easier.

**Comment by emilk** [comment]
Let's just rename these and keep the old names as deprecated redirects
