### ISSUE TITLE
`rr.log_file_from_path` just hangs indefinitely

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#7791]
Try this:
```
curl 'https://app.rerun.io/version/latest/examples/dna.rrd' -o - > /tmp/dna.rrd
```
```python
import sys
import rerun as rr

path_to_rrd = sys.argv[1]
rr.init("rerun_example_dataframe", spawn=True)
rr.log_file_from_path(path_to_rrd)
```
```
python docs/snippets/all/reference/dataframe_view_query.py /tmp/dna.rrd
```

On 0.18.2, this works just fine.
On latest alpha, this does the logging as expected, but then hangs indefinitely. I literally cannot kill the logging process without resorting to the nuclear tools.

**Comment by teh-cmc** [comment]
This seems to be only true with rrd files, passing e.g. a jpeg to that program seems fine.

**Comment by emilk** [comment]
Likely caused by:
* https://github.com/rerun-io/rerun/pull/7475

**Comment by teh-cmc** [comment]
Oh interesting, I see...

**Comment by emilk** [comment]
Seems like there are two problems:
A) why doesn't the above .rrd have an `end-of-stream` marker?
B) why doesn't ctrl-C work?

**Comment by teh-cmc** [comment]
A) The file was saved from the viewer using the `File > Save` feature -- it seems this does not add the proper EOS marker
B) I don't know how this is implemented yet, but I assume this is constantly retrying to `read()`? which would eat the signal

**Comment by teh-cmc** [comment]
Okay I'll fix A to start with, that should be trivial.

**Comment by teh-cmc** [comment]
As for B), looking at the core dump it's relatively safe to assume that's what's happening in the RRD dataloader hangs forever, and therefore the dataloader manager is stuck waiting for its thread:
```
#2  0x000070b8f3253b91 in std::sys::pal::unix::thread::Thread::join () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
#3  0x000070b8f2de5b22 in std::thread::JoinInner<T>::join () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
#4  0x000070b8f2dd68d9 in re_sdk::recording_stream::RecordingStreamInner::wait_for_dataloaders () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
#5  0x000070b8f2ddd9bf in re_sdk::recording_stream::RecordingStream::disconnect () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
#6  0x000070b8f2be531d in pyo3::marker::Python::allow_threads () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
#7  0x000070b8f2c63287 in rerun_bindings::python_bridge::__pyfunction_shutdown () from /home/cmc/dev/rerun-io/rerun/rerun_py/rerun_bindings/rerun_bindings.abi3.so
```
