### ISSUE TITLE
Heuristic stacks video frames rather than giving them their own 2d views

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7821]
VideoAssets should follow the same heuristics as images

**Comment by emilk** [comment]
In particular: `rerun folder_of_videos/` should produce one space-view per video

**Comment by emilk** [comment]
Half of the work is done in:
* https://github.com/rerun-io/rerun/pull/7850

For the second half, we need to do one or both of the following:

* https://github.com/rerun-io/rerun/issues/7481
* Pass our `Caches` down to `MaxImageDimensionSubscriber`

**Comment by emilk** [comment]
* Closed by https://github.com/rerun-io/rerun/pull/7869

**Comment by Wumpf** [comment]
I'm still getting that error. For instance when using the video check from the checklist (update incoming) without a blueprint
