### ISSUE TITLE
VideoFrameReference should have an extension constructor for `seconds=`

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#7822]
The default signature doesn't make it clear:
```
class VideoFrameReference(
    timestamp: VideoTimestampLike,
    *,
    video_reference: EntityPathLike | None = None
)

Create a new instance of the VideoFrameReference archetype.

Parameters
timestamp
References the closest video frame to this timestamp.

Note that this uses the closest video frame instead of the latest at this timestamp in order to be more forgiving of rounding errors for inprecise timestamp types.
```

I would recommend we disallow casting from `int` on `VideoTimestampLike` and add optional kwargs such as:
```
VideoFrameReference(seconds=12.4)
VideoFrameReference(nanos=124000000)
```

**Comment by Wumpf** [comment]
the named arguments make sense to me but not allowing downcasting is weird for the batch constructor imho: `send_columns` should absolutely be able to take just an np array of integers

(also disallowing that is a breaking change, making this no longer eligible for a patch release)

**Comment by jleibs** [comment]
I think the issue is that for people working with video seconds is way more common than nanoseconds.

Accidentally just doing `VideoFrameReferance(timestamp =1.0)` is an annoying footgun.

At a minimum that should produce an error for floats.
