### ISSUE TITLE
Changelog generator seems to ignore changes between last patch & minor releases

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#7825]
Need to dig deeper but we have at least a single example of this happening:
#7238 was not mentioned in the 0.19 release changelog. On the pr it says that it’s on 0.18.1/2. However, the PR landed on Aug 20, 0.18.1 was published on Aug 29 but 0.18.0 on Aug 16. But from the looks of it we did a proper branch of for 0.18.1 (and then pushed out 0.18.2 on the same, yanking 0.18.1 because we forgot something).

(this concrete one has been added manually to the changelog by now, but it should still possible to repro this!)

**Comment by emilk** [comment]
This was user error - I did

> scripts/generate_changelog.py --commit-range 0.18.2..HEAD

and should have done

> scripts/generate_changelog.py --commit-range 0.18.0..HEAD

I'll see if I can make the same mistake impossible in the future.
