### ISSUE TITLE
Add a global setting to set a mapbox access token

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7849]
#6561 adds a new map view to rerun. In order to enable mapbox as background, a mapbox token must be provided. Initially, it's done via the `RERUN_MAPBOX_ACCESS_TOKEN`, but that setting should be editable from the UI and persisted with the rest of the app settings.

**Comment by tfoldi** [comment]
it is not just a Mapbox token; we can easily add Google Bing, or other map providers - most need tokens for access. (I believe what you eventually need is some sort of centralized secret management.)
