### ISSUE TITLE
Assume real-world meters instead of UI unit for "scene unit" `Radius` values

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7872]
That would make it consistent with our definition of `Radius` and how it's used in the 2D view. 

Would be facilitated by:
- https://github.com/podusowski/walkers/issues/196

**Comment by Wumpf** [comment]
`Radius` is specified to both hold  "units" (context dependend) and ui units, so I think the title is actually wrong. You want its scene units to mean meters instead of whatever it is you're doing now
