### ISSUE TITLE
Cannot find datatype for `ShowLabels` error (due to custom placeholder not being generated)

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#7940]
Related error:
```
[2024-10-30T07:17:01Z ERROR re_viewer_context::viewer_context] Could not find datatype for component rerun.components.ShowLabels. Using null array as placeholder.
[2024-10-30T07:17:01Z ERROR re_viewer_context::component_ui_registry] Failed to deserialize component of type rerun.components.ShowLabels: Failed to deserialize "rerun.datatypes.Bool#value"
```

If I understand correctly, ShowLabel has no custom placeholder in the reflection, and can very well never been logged in either stores. So basically nowhere to pick up a datatype. Reading the codegen code, it looks like it should have a placeholder but it doesn't. The component is not `Default`.

Repro:
- commit 10233944f7492aeff5f21d2db03dbd2c3930351a from https://github.com/grtlr/rerun
- run the node_link rust example in lattice mode
- select the graph entity for the visualizer UI to appear (which include a `ShowLabel` component)

**EDIT**: the key aspect of this repro is that there exists no fallback provider for `ShowLabel` (contrary to, eg., the 2d view, which doesn't trigger that error)

https://github.com/user-attachments/assets/a22d672b-045b-4817-b6aa-c06fb3d63fda

**Comment by grtlr** [comment]
An ad-hoc fix seems to be adding a fallback provider for `ShowLabels`:
```rs
impl TypedComponentFallbackProvider<ShowLabels> for NodeVisualizer {
    fn fallback_for(&self, ctx: &QueryContext<'_>) -> ShowLabels {
        true.into()
    }
}

re_viewer_context::impl_component_fallback_provider!(NodeVisualizer => [ShowLabels]);
```
