### ISSUE TITLE
LineStrips3D ignores color if num_strips divisible by four or equals three

### ISSUE THREAD

**Issue by eskjorg** [rerun-io/rerun#8035]
**Describe the bug**
`rr.LineStrips3D(strips, colors)` ignores the `colors` argument and makes all lines white if `len(strips) % 4 = 0 or len(strips) == 3`.

**To Reproduce**
```
strips = [[[0, 0, 0], [0, 0, 1]]]
colors = [0x00FF00FF] # green
for n in range(30):
    rr.log(
        "linestrips3d", rr.LineStrips3D(strips=n * strips, colors=n * colors)
    )
```

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.1

**Rerun version**
Local client: `rerun-cli 0.18.2 [rustc 1.76.0 (07dca489a 2024-02-04), LLVM 17.0.6] aarch64-apple-darwin release-0.18.2 59ff15b, built 2024-08-29T13:55:42Z`

**Comment by Wumpf** [comment]
wow. that's.. impressive Oo
Repros cleanly on `main`. It's an SDK issue given that the data doesn't get through. Given how language dependent this is I suspect it's a Python SDK only issue.

Good frame:
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/3fae0cdc-6df9-439a-a5f7-5a2dcf147cf0">
Bad frame:
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/b1fdbe77-8238-462c-8a9c-de689d43ed84">

**Comment by eskjorg** [comment]
Thanks @Wumpf for jumping on this fast!

Also, I think you mixed up "good" and "bad" there.

**Comment by jleibs** [comment]
This is a bug in `rgba32_ext.py`. Confirmed it affects other primitives such as Points3D.

In short, the python API is trying to be way too clever with precedence of multi-representation of colors combined with our lazy batch-conversion.

Concretely consider we support:
- color = int (`0x00ff00`)
- color = [int] (`[0, 255, 0]` or `[0, 255, 0, 255]`)
- colors = [color1, color2, color3, color4] (`[0x00ff00, 0x00ff00, 0x00ff00, 0x00ff00]`, ...)
- colors = color (`[0, 255, 0, 255]`, ...)

It's clear there's an ambiguity between an array of colors represented as ints, and a single RGBA represented as an array.

**Comment by jleibs** [comment]
fwiw, we actually try to handle this ambiguity here, but you need to be explicit about your types.
https://github.com/rerun-io/rerun/blob/jleibs/rrdp_wheels/rerun_py/rerun_sdk/rerun/datatypes/rgba32_ext.py#L76

Confirmed this works around the issue:
```
import rerun as rr
import numpy as np

rr.init("rerun_example_colorbad", spawn=True)

point = [[0, 0, 0]]
colors = [0x00FF00FF]  # green


for n in range(30):
    colors = np.array(n * colors, dtype=np.uint32)
    rr.log("points3d", rr.Points3D(positions=n * point, colors=colors))
```

**Comment by eskjorg** [comment]
Thanks @jleibs for the help!
