### ISSUE TITLE
Warn when `Geo*` entities are logged and the viewer wasn't compiled with the `map_view` feature

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#8052]
The map view is behind a `map_view` cargo feature on `rerun-cli`, which is enabled in release build but not in default build (aka when building from source). This leads to a footgun where people don't see a map when they expect one. We should warn the user when that happens, indicating that the `map_view` feature needs to be enabled.

The proposed mechanism for that is to have a store subscribers that reacts to some specific indicator components, and emit warnings as required.

**Level 1**: hard code `GeoPoints` and `GeoLineStrings` (subject to bitrot, eg when we introduce `GeoPolygons`

**Level 2**: use the information already contained in `attribute.docs.view_types` to populate the reflection structures, and use said structure to generate warnings for all kinds of view that might be missing.
.
.
.

**Level ∞**: "unsupported data, click [here](https://www.youtube.com/watch?v=E4WlUXrJgy4) to download the Map view plugin"

**Comment by emilk** [comment]
We log a warning, but that's not good enough. We should show the error message in the space view with the problem:

![Image](https://github.com/user-attachments/assets/8a93751a-ae9e-4fa8-959e-e52f972f0068)
