### ISSUE TITLE
Apply Blueprint on specific recording 

### ISSUE THREAD

**Issue by EtaLoop** [rerun-io/rerun#8135]
In some cases, I use Blueprint to change background color of a recording view in the viewer.
I would like to specify the recording_id and the application_id in which it should change the background color.

**Comment by EtaLoop** [comment]
Hello, I can see that send_blueprint() can take a recording as parameter. That's not the recording_id and application_id but in the end it works the same, no?
https://ref.rerun.io/docs/python/0.20.1/common/initialization_functions/#rerun.send_blueprint

**Comment by teh-cmc** [comment]
* Dupe of #8287
