### ISSUE TITLE
Handle self-edges, duplicated nodes, and duplicated edges in graph viewer

### ISSUE THREAD

**Issue by grtlr** [rerun-io/rerun#8238]
Right now we can't draw self-edges. Also, our model around how to handle duplicated nodes and duplicated edges is ambiguous.

@abey79 I think the following makes sense:
* Duplicated nodes is undefined behavior.
* Self-edges are ignored by the force-based layout algorithm but shown in the graph view, with a length depending on the `distance` parameter (potentially multiplied for multiple self edges).

**Comment by abey79** [comment]
Makes sense to me 👍🏻
