### ISSUE TITLE
Need to run `rerun reset` after running a few times?

### ISSUE THREAD

**Issue by bsodmike** [rerun-io/rerun#8307]
I'm using a quick script https://github.com/bsodmike/gravity-simulator/blob/master/run.sh as this gravity sim sometimes causes rerun to stop rendering.

I'm not sure if this is an issue with the original implementation or whether logs are getting corrupted on the rerun end - it'll need some investigation by someone who has time to do this.

**Desktop (please complete the following information):**
 - OS: Sonoma 14.5

**Rerun version**
```
rerun = "0.18.0"
```

**Comment by Wumpf** [comment]
I tried it out and it seems that sometimes the simulation explodes and thus the camera (which by default tries to have the entire scene in focus) moves out very very far.
So what you're then experiencing is that on the next (probably sane) run the camera is still in the same spot. You don't have to do `rerun reset` for the camera to reset, double clicking the view does it just the same.

This could be also addressed by setting a default camera once
* #8265 
is addressed
