### ISSUE TITLE
Multi-selection selection panel reborn

### ISSUE THREAD

**Issue by abey79** [rerun-io/rerun#8336]
#### Context

The current implementation of the selection panel is comically useless when multiple items are selected, and incurs undue code complexity (e.g. `UiLayout::SelectionPanelLimitHeight`). For the longest time, our dream has been to come up with some "merged" view of the current selection, but this hardly is actionable as a starting point:
- https://github.com/rerun-io/rerun/issues/4251

#### Proposal

This issue is about getting the ball rolling on this front with a two-step, actionable, minimalistic take on the  selection panel with multi-selection:

1) show a list of what is currently selected
2) ...and that's basically it

**Comment by emilk** [comment]
Current attempt:
![Image](https://github.com/user-attachments/assets/c2aa2750-8a26-45ef-aa6e-cd413cf50026)
