### ISSUE TITLE
Controlling pinhole camera rendering size and arrow length

### ISSUE THREAD

**Issue by rafaelspring** [rerun-io/rerun#8353]
**Describe the annoyance**
I'm outputting cameras and points to debug/control a bundle adjustment operation.
The size of the cameras seems kind of random and is also changing when adding more logs.

**To Reproduce**
Here's my code. It is run for every iteration of the bundle adjustment. I'm using C++.

There's probably a very easy way to fix or control this but it'd take me hours to research and get right while I'm pretty sure you guys can figure it out in a couple of minutes.
Issue #6544 mentions something like that but it's way above my level of expertise with rerun.io to make sense to me.

```cpp
rerun::RecordingStream& rec = *(debugObject->recStream);
rec.set_time_sequence("Initial tracking", mKeyframes.size());

rec.log_static("/", rerun::ViewCoordinates::RIGHT_HAND_Y_DOWN);

auto logPose = [&rec](const Keyframe& kf, const std::string& entityName){
  //...
  rec.log(entityName, rerun::Transform3D(rerun::Vec3D(trlVec.get_data_ptr()),
                                         rerun::Mat3x3(rotMatf.get_data_ptr())));
  //...
  rec.log(entityName, rerun::Pinhole::from_focal_length_and_resolution({fx, fy}, {float(calibSize.x), float(calibSize.y)}));
};

// Send KF poses to rerun.
for (const auto& el : mKeyframes) {
  const KeyframeSPtr& kf = el.second;
  const std::string entityName = "kf_" + std::to_string(el.first);
  logPose(*kf, entityName);
}

// Send current pose.
logPose(this->currentFrame(), "cframe");

// ======== Point cloud ========
std::vector<rerun::Position3D> keyPoints3D;
std::vector<rerun::Color> keyPointsColors;
//...

for (const auto& wPtr : mKeypointRegistry) {
  //...
  keyPoints3D.push_back(rerun::Position3D(worldPos[0], worldPos[1], worldPos[2]));
  keyPointsColors.push_back(rerun::Color(0,200,0,255));
}
```

The camera's size is likely determined by the scene bounding box size and since a single bad point with a very large coordinate suffices to make a very large bounding box, the cameras become huge, as shown in the image below. Points are drawn in green.

![Image](https://github.com/user-attachments/assets/31255928-f067-4d63-8001-bfc690faabce)

**Expected behavior**
Constant camera sizes and/or one that I can control.

**Your goals**
Debug bundle adjustment.

**Screenshots**
See above.

**Desktop (please complete the following information):**
Windows 10

**Comment by Wumpf** [comment]
For camera size set `imagePlaneDistance` on the pinhole camera https://rerun.io/docs/reference/types/archetypes/pinhole
For arrow length of transforms set `AxisArrowLength` on the transform https://rerun.io/docs/reference/types/archetypes/transform3d

If you're in python you can also set this as a view-wide default (blueprint api for C++ is still missing as of writing), see https://rerun.io/docs/concepts/visualizers-and-overrides#perview-component-default

> The camera's size is likely determined by the scene bounding box size and since a single bad point with a very large coordinate suffices to make a very large bounding box

correct. the viewer is scrambling to make up meaningful defaults, but it's not always working great
