### ISSUE TITLE
Native F16 support for arrow tensors

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#854]
arrow2 currently does not support a native f16 primitive array. For now we are upscaling floats -> f32 in the client library, but would be ideal not to have to touch user-data.

**Comment by emilk** [comment]
We should create an up-stream issue for this in the `arrow2` repository.

There is a `DataType::Float16`: https://docs.rs/arrow2/0.16.0/arrow2/datatypes/enum.DataType.html#variant.Float16

**Comment by emilk** [comment]
Blocked on this being merged and released:
* https://github.com/DataEngineeringLabs/arrow2-convert/pull/104
