### ISSUE TITLE
Versioned .rrd files and streams

### ISSUE THREAD

**Issue by emilk** [rerun-io/rerun#873]
Add a version number to .rrd files and connections so we can detect mismatched versions.

On mismatch we log a warning, then do our best to try to load anyways.

The easiest approach would be to add the current Rerun version (e.g. 0.1.0), perhaps as three bytes. We could then do a semver compare.

**Comment by andresv** [comment]
It seems this:
⚠️ [RRD files don't yet handle versioning!](https://github.com/rerun-io/rerun/issues/873) ⚠️

In here https://www.rerun.io/docs/getting-started/logging-python is not relevant anymore.

**Comment by Wumpf** [comment]
@andresv thanks! since this shows up in a bunch of places and there should be some replacement text I created a new issue for this here
* https://github.com/rerun-io/rerun/issues/5027
