### ISSUE TITLE
viewer: double clicking an entity in the spatial view should put it into focus

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#918]
(Following a standup discussion)

The controversial follow-up to #917: generally the same idea, except that it would also work when directly double-clicking on an entity through the spatial view.

This requires some design work; some ideas/thoughts that were thrown around:
- only do so if the entity was already selected to begin with
- what's the expected with e.g. point clouds (i.e. how does one click on a point cloud vs. a point in the point cloud)

**Comment by Wumpf** [comment]
Our current behavior is that we focus on the 3d space position that is double clicked.
This _can_ be more useful than focusing on an entity, but we could at the very least use the entity's/visualizer's bounding box that we need for
* #917 
anyways to position the camera a bit better.
