### ISSUE TITLE
Support rerun on python-3.7

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#922]
A few features have crept in that depend on python-3.8.  Would be nice to make these optional and get to a point where python-3.7 still works. Once we do that that we should also add a CI test for python-3.7 to avoid breaking it again.

**Comment by emilk** [comment]
Ubuntu 20.04 is on Python 3.8

For now we've decided to have Python 3.8 as our minimum supported Python version.

If anyone needs 3.7 support, feel free to re-open this issue.
