### ISSUE TITLE
re_analytics: track git hash's dirtiness in real-time

### ISSUE THREAD

**Issue by teh-cmc** [rerun-io/rerun#925]
Right now we're watching `.git/refs/heads/**` to detect hash changes, but of course this is not enough to detect changes to the repo dirty state as they happen.

@jleibs came up with an evil plan for that:
> You could do it with a two-stage process
> one build.rs that conditionally updates a file if it changes
> and a second build.rs that watches for changes on that file

**Comment by emilk** [comment]
Related: https://github.com/rerun-io/rerun/pull/1388

**Comment by teh-cmc** [comment]
We don't keep track of dirty state no more.
