### ISSUE TITLE
Loading of data is extremely slow in web on Chrome

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#963]
Repro is relatively straight forward with even simple demos like car demo.

Happens on both chrome and edge browsers, but not on firefox.

Symptom is that new messages arrive at a rate of 2/sec.

You can see this happening in the profile view in chrome:
![image](https://user-images.githubusercontent.com/3312232/215136081-eb39b0f5-3cae-4826-ad4c-18299c814e80.png)
![image](https://user-images.githubusercontent.com/3312232/215136498-2148fa54-58c4-40c9-bf3d-ff5e67a42554.png)

I don't know enough about the web task worker model to understand why these get scheduled so infrequently or why the task waits for ~15 ms before starting the deserialization function.

**Comment by emilk** [comment]
What Jeremy has found is that the render task starves the websocket task.

A potential fix is to replace `egui_ctx.request_repaint` with `egui_ctx.request_repaint_after(10ms)` when there are messages to process.

**Comment by jleibs** [comment]
The call to repaint from within the websocket `decode_log_msg` handler seems to be part of the problem. As suggested, `request_repaint_after` dramatically improves the performance. However, this is somewhat broken on web and can leave us in a situation where the next render never happens (https://github.com/rerun-io/rerun/issues/1607)

**Comment by jleibs** [comment]
An additional unfortunate finding is that the google-chrome profiler itself further exacerbates the issue.

**Comment by teh-cmc** [comment]
Would be nice to redo these measurements when #1880 lands
