### ISSUE TITLE
Reference documentation for all the data-types

### ISSUE THREAD

**Issue by jleibs** [rerun-io/rerun#973]
See: https://github.com/rerun-io/rerun-docs/blob/main/docs/reference/data-types/

This mostly be a reference from a data-model / consumption perspective.
* How is the type represented?
* What components does it have?
* What additional object-properties does it have?
* How does it map to a scene/renderer?
* Screen-shot of a rendered view of just this type.
* Cross-link to the python/rust API docs 
* Code-sample in both python & rust

Types:
 - [ ] Points
 - [ ] Rects
 - [ ] Bounding Boxes
 - [ ] Paths & Line Segments
 - [ ] Images
 - [ ] Meshes
 - [ ] Annotations
 - [ ] Scalars / Plots
 - [ ] Transforms

**Comment by Wumpf** [comment]
We introduced a new concept, "Primitives"  for this and documented all of the above.
There is more to be documented but we have a good start, let's create a new ticket later once we figure out more details there
